//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ScanDlgsRes.rc
//
#define IDS_COL_NAME                    1
#define IDS_COL_ORIG                    2
#define IDS_COL_VIRUS                   3
#define IDS_COL_DATE_ADDED              4
#define IDS_COL_FILE_DATE               5
#define IDS_INCORRECT_PASSWORD          6
#define IDS_FS_SCAN_STAT                7
#define IDS_FILE                        8
#define IDHELP                          9
#define IDS_ACTION                      10
#define IDS_FOUNDFILE                   11
#define IDS_FOUNDFOLDER                 12
#define IDS_CLOSE                       13
#define IDS_S_STARTING                  13
#define IDS_AC_MOVE                     14
#define IDS_AC_RENAME                   15
#define IDS_AC_DELETE                   16
#define IDS_AC_NOTHING                  17
#define IDS_AC_CLEAN                    18
#define IDS_AC_BAD                      19
#define IDS_ERROR_MOVE                  20
#define IDS_ERROR_RENAME                21
#define IDS_ERROR_DELETE                22
#define IDS_ERROR_CLEAN                 23
#define IDS_ERROR_ACTION_TAKEN          25
#define IDS_S_STOPPING                  27
#define IDS_S_SCANNING_DIRS             28
#define IDS_S_SCANNING_MEM              29
#define IDS_S_SCANNING_BOOT             30
#define IDS_S_SCANNING_FILES            31
#define IDS_S_INTERRUPTED               32
#define IDS_S_NEVER_RUN                 33
#define IDS_S_DONE                      34
#define IDS_S_STARTED                   35
#define IDS_FILES_TO_SCAN               36
#define IDS_DIRECTORIES                 37
#define IDS_FILES_SCANNED               38
#define IDS_VIRUSES_FOUND               39
#define IDS_FAILED_TO_SCAN              40
#define IDS_TIME                        41
#define IDS_EXCLUSION_COL_HEADING       42
#define IDS_EXCLUSION_COL_CLEANABLE     43
#define IDS_EXCLUSION_COL_TYPE          44
#define IDS_SERVICES_NOT_RUNNING        45
#define IDS_ERROR_REG_FAIL              46
#define IDS_ERROR_SERVICE_HUNG          47
#define IDS_ERROR_UNKNOWN               48
#define IDS_CREATE_ERROR                48
#define IDS_APP_NAME                    49
#define IDS_AC_UNDONE                   50
#define IDS_S_QUEUED                    51
#define IDS_CANNOT_ABORT_QUEUED_SCANS   52
#define IDS_NO_VIEW_SCAN_IN_PROGRESS    53
#define IDD_MOVE_FILE_TEMPLATE          101
#define IDD_SCAN_DIALOG                 129
#define IDR_POPUP_MENU                  133
#define IDD_PASSWORD                    137
#define IDI_SCANNET_PASSWORD            138
#define IDI_GETSTATUS                   139
#define IDD_RESULTS_VIEW                140
#define IDD_TEST                        142
#define IDR_AVI1                        145
#define IDD_GETSTATUS                   146
#define IDR_VIRUS_TOOLBAR               148
#define IDR_RESULTS_TOOLBAR             150
#define IDD_LIST_VIRUSES                152
#define IDR_AVI3                        154
#define IDD_SENDTOINTEL                 155
#define IDD_GETUPLOADFILES              156
#define IDD_VIRUS_FOUND                 157
#define IDR_VIRUS_FOUND                 158
#define IDD_PROPERTY_PAGE               161
#define IDI_SHIELD                      167
#define IDD_RELOAD_SERVICES             169
#define IDD_CONFIG_HISTORY              170
#define IDI_HISTORY                     171
#define IDD_DIALOG1                     186
#define IDD_WAIT                        186
#define IDR_AVI2                        187
#define IDD_CONFIG_QUARANTINE_PURGE     188
#define IDD_PAUSE_DIALOG                189
#define IDD_PROMPT_SVC_STOP_PROC_TERMINATE 191
#define IDD_RESULTS_ACTION_REQUIRED     192
#define IDD_MESSAGE_DIALOG              233
#define IDD_WARNING_DIALOG              234
#define IDD_EMAIL_MESSAGE               235
#define IDC_WARNING                     326
#define IDC_EDIT                        341
#define IDC_BEEP                        342
#define IDC_CHANGE_SUBJECT              343
#define IDC_SUBJECT                     344
#define IDC_INFECTION_INFO              345
#define IDC_PROGRESS                    1000
#define IDC_STATIC_PATH                 1001
#define IDC_STATIC_FILE                 1002
#define IDC_CLOSE                       1003
#define IDC_LIST                        1006
#define IDC_RESULT_STATIC               1007
#define IDC_MESSAGE                     1008
#define IDC_PASSWORD                    1008
#define IDC_STATUS                      1009
#define IDC_PURGE_BY_SIZE_EDIT          1010
#define IDC_EDIT1                       1011
#define IDC_FILEPATH                    1011
#define IDC_TOTAL_FILES                 1011
#define IDC_NAME                        1011
#define IDC_KEN                         1012
#define IDC_FILTER                      1013
#define IDC_DETAILS                     1014
#define IDC_REPORT                      1015
#define IDS_DLG_SVC_STOP_PROC_TERM_NOT_CREATED 1016
#define IDS_S_SUSPENDED                 1017
#define IDC_STOP                        1018
#define IDC_LDVPRESULTS                 1019
#define IDS_S_RESUMED                   1019
#define IDS_AC_CLEAN_PARTIAL            1020
#define IDC_FILENAME                    1021
#define IDS_S_ERASER_SCANS              1021
#define IDS_WARNING                     1022
#define IDC_AVI                         1023
#define IDS_CLOSE_PROMPT                1023
#define IDS_REMOVE_RISK                 1024
#define IDC_COMBO                       1025
#define IDS_REMOVE_RISK_TEXT            1025
#define IDC_ADD                         1026
#define IDS_ERROR_RESTORE_SELECTED_ITEMS 1026
#define IDC_DELETE_NOW                  1027
#define IDS_NO_THREAT_DETECTED          1027
#define IDC_PAUSE_PAUSE_BUTTON          1028
#define IDS_NO_THREAT_NOT_CLEANED       1028
#define IDC_TERMINATE_PROCESS           1029
#define IDS_NO_THREAT_CLEANED           1029
#define IDS_CLEANED                     1030
#define IDS_PATH_UNAVAILABLE            1031
#define IDS_S_SCANNING_PROCS_AND_LOADPOINTS 1032
#define IDS_S_SCANNING_PROCS_AND_ERASER_DEFS 1033
#define IDS_S_SCANNING_LOADPOINTS_AND_ERASER_DEFS 1034
#define IDS_S_SCANNING_PROCS_AND_LOADPOINTS_AND_ERASER_DEFS 1035
#define IDS_REMOVE_RISK_FIRST_TEXT      1036
#define IDS_REMOVE_RISK_FIRST_CAPTION   1037
#define IDC_INFO                        1038
#define IDS_CAP_REMOVE_RISK             1038
#define IDC_VIRUS_LIST                  1039
#define IDS_CAP_REMOVE_RISK_AND_REBOOT  1039
#define IDC_ANIMATE1                    1040
#define IDS_CAP_REBOOT                  1040
#define IDC_STATUS_TEXT                 1041
#define IDS_MSG_REMOVE_RISK             1041
#define IDS_MSG_REMOVE_RISK_AND_REBOOT  1042
#define IDS_MSG_REBOOT                  1043
#define IDC_DEL                         1044
#define IDS_RADIO_REMOVE_AND_REBOOT     1044
#define IDC_EMail                       1045
#define IDS_RADIO_REMOVE_NO_REBOOT      1045
#define IDC_PO                          1046
#define IDS_RADIO_NO_REMOVE_RISKS       1046
#define IDC_EMAIL_ADDRESS               1047
#define IDS_RADIO_REBOOT                1047
#define IDC_ADDRESS                     1048
#define IDS_RADIO_NO_REBOOT             1048
#define IDC_CITY                        1049
#define IDS_RADIO_REMOVE_RISKS          1049
#define IDC_STATE                       1050
#define IDS_RADIO_NO_REMOVE_OR_REBOOT   1050
#define IDC_ZIP                         1051
#define IDS_STATUS_ANALYZING            1051
#define IDC_DESCRIPTION                 1052
#define IDS_STATUS_ACTED                1052
#define IDC_SEND_DATA                   1053
#define IDS_STATUS_ACTED_ANALYZING      1053
#define IDS_STATUS_MUSTREMOVE           1054
#define IDC_STATUSICON                  1055
#define IDS_STATUS_MUSTREMOVE_ANALYZING 1055
#define IDC_TEXT                        1056
#define IDS_RESTORE_FILE_TITLE          1056
#define IDC_KENS_DETAILS                1058
#define IDS_TERMINATE_SCAN              1058
#define IDC_LDVPRESULTSCTRL1            1066
#define IDC_CHECK1                      1067
#define IDC_HO_APPLYTOCLIENTS           1067
#define IDC_VALUE                       1069
#define IDC_SPIN2                       1070
#define IDC_TYPE                        1071
#define IDC_COMBO2                      1072
#define IDC_CONFIGURE_HISTORIES         1073
#define IDC_PAUSE                       1074
#define IDC_NEXT                        1075
#define IDC_PREV                        1076
#define CONFIG_HISTORY_HELP             1076
#define IDC_EXPORT                      1077
#define IDC_WORKING_AVI                 1077
#define IDC_START                       1078
#define IDC_PAUSE_DELAY_COUNT_TEXT      1079
#define IDC_PAUSE_CONTINUE_BUTTON       1080
#define IDC_PAUSE_STOP_BUTTON           1081
#define IDC_PAUSE_DELAY_1HOUR_BUTTON    1082
#define IDC_PAUSE_DELAY_4HOUR_BUTTON    1083
#define IDC_ACTIONS                     1089
#define IDC_UNDO                        1090
#define IDC_STOP_SVC_TERM_PROC_STATIC   1090
#define IDC_RESTORE                     1091
#define IDC_STOP_SVC_PROC_TERM_STATIC1  1091
#define IDC_REPAIR                      1092
#define IDC_DELETE                      1093
#define IDC_QUARANTINE_INFECTED_ITEM    1094
#define IDC_SCANDELIVER                 1095
#define IDC_ADD_TO_QUARANTINE           1096
#define IDC_REBOOT_SYSTEM               1097
#define IDC_PURGE_BY_SIZE_CHECK         1098
#define IDC_CHECK_ENABLE_QPURGE_BYSIZE  1099
#define IDC_WARNING_ICON                1101
#define IDC_GENERIC_WARNING             1102
#define IDC_RADIO1                      1103
#define IDC_RADIO2                      1104
#define IDC_LIST1                       1104
#define IDC_RADIO3                      1105
#define IDC_PURGEBYSIZE_DIRUNIT         1106
#define IDS_DO_DELETE                   32769
#define IDS_DO_SAVE                     32770
#define ID_ACTION_MOVE                  32771
#define ID_ACTION_RENAME                32772
#define ID_ACTION_DELETE                32773
#define ID_ACTION_CLEAN                 32774
#define ID_REPORT                       32778
#define IDS_INFECTED                    32779
#define IDS_CLEAN                       32780
#define IDS_NA                          32781
#define IDS_DO_MOVE                     32782
#define IDS_DO_RENAME                   32783
#define IDS_DO_SEND                     32786
#define IDS_DO_RESTORE                  32787
#define IDS_DO_CLEAN                    32788
#define IDS_AC_SAVE                     32789
#define IDS_AC_SEND                     32790
#define IDS_AC_UNDO                     32791
#define IDS_GETSTATUSDONE               32792
#define IDS_FILENAME                    32793
#define IDS_LOCATION                    32794
#define IDS_STATUS                      32795
#define IDS_ST_MOVE                     32796
#define IDS_ST_RENAME                   32797
#define IDS_ST_DELETE                   32798
#define IDS_ST_SAVE                     32799
#define IDS_ST_SEND                     32800
#define IDS_ST_RESTORE                  32801
#define IDS_ST_CLEAN                    32802
#define IDS_ST_UNDO                     32807
#define IDS_STATUSDONE                  32810
#define IDS_TOTAL_NOTIFICATIONS         32811
#define IDS_CURRENT_POS                 32812
#define IDS_FILTER_TODAY                32813
#define IDS_FILTER_ALL                  32814
#define IDS_FILTER_MONTH                32815
#define IDS_FILTER_WEEK                 32816
#define IDS_FILTER_RANGE                32817
#define IDS_LOG_DAYS                    32819
#define IDS_LOG_MONTHS                  32820
#define IDS_LOG_YEARS                   32821
#define IDS_NO_ACTION                   32822
#define IDS_TITLE                       32823
#define IDS_SUCCEEDED                   32824
#define IDS_FAILED                      32825
#define IDS_SCAN_VIEWED                 32826
#define IDS_ABORT_SCAN                  32827
#define IDS_INBIN                       32828
#define IDS_RESTORE_OVERWRITE_TITLE     32829
#define IDS_RESTORE_OVERWRITE_FORMAT    32830
#define IDS_ADD_FILE_TITLE              32831
#define IDS_ADD_BUTTON                  32832
#define IDS_ADD_FILTER_STRING           32833
#define IDC_DELETE_CHECK                32834
#define IDS_ERROR_DELETING_FILE         32834
#define IDS_ERROR_ADDING_TO_QUARANTINE  32835
#define IDS_AC_RESTORE                  32836
#define IDS_HTML_HELP_ERROR             32837
#define IDS_DRIVE_NOT_READY             32838
#define IDS_WARN_AND_RESTORE            32839
#define IDS_UNDO_NO_PATH_TITLE          32840
#define IDS_UNDO_NO_PATH_FORMAT         32841
#define IDS_ERROR_NO_SCANNING_INTERFACE 32842
#define IDS_WEEKLY_SCAN_RUNNING         32843
#define IDS_DELAY_ONEMORE               32846
#define IDS_S_DELAYED                   32847
#define IDS_DELAY_NTIMES                32848
#define IDS_SCAN_TIME_FORMAT            32849
#define IDC_CHECK_ENABLE_QPURGE         32850
#define IDS_PAUSE1HOUR                  32850
#define IDC_PURGE_QUARANTINE            32852
#define IDS_QUEUED_SCAN_WILL_ABORT      32853
#define IDS_S_SCANNING_PROCESSES        32854
#define IDS_S_SCANNING_LOADPOINTS       32855
#define IDS_S_SCANNING_ERASER_DEFS      32856
#define IDS_ERROR_LOADING_SCAN_ENGINE   32857
#define IDS_REBOOT_REQUIRED             32858
#define IDS_REBOOT_WARNING              32859
#define IDS_AC_RESTORE_PARTIAL          32860
#define IDS_AC_UNDO_PARTIAL             32861

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        193
#define _APS_NEXT_COMMAND_VALUE         32862
#define _APS_NEXT_CONTROL_VALUE         1107
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
