// Configurable items

#define CONFIG_PROFILE_NAME			"AVISACSampleComm.prf"
#define MAIN_LOGFILE_NAME			"AVISACSampleComm.log"
#define MAIN_TRACEFILE_NAME			"AVISACSampleComm.trc"
#define MAIN_AGENT_NAME				"AVISACSampleComm:"

#define SOCKS_ADDRESS_KEYNAME					"socksAddress"
#define PROXY_ADDRESS_KEYNAME					"proxyAddress"
#define PROXY_USERNAME_KEYNAME					"proxyUsername"
#define PROXY_PASSWORD_KEYNAME					"proxyPassword"
#define CONNECTION_TIMEOUT_KEYNAME				"connectTimeout"
#define CONNECTION_RETRIES_KEYNAME				"connectRetries"
#define SEND_REQUEST_TIMEOUT_KEYNAME			"sendRequestTimeout"
#define SEND_REQUEST_DATA_TIMEOUT_KEYNAME		"sendRequestDataTimeout"
#define RECEIVE_RESPONSE_TIMEOUT_KEYNAME		"receiveResponseTimeout"
#define RECEIVE_RESPONSE_DATA_TIMEOUT_KEYNAME	"receiveResponseDataTimeout"
#define WININET_DEBUGGING_KEYNAME				"enableWinInetLogging"
#define GATEWAY_COUNT_KEYNAME					"gatewayCount"
#define GATEWAY_ADDRESS_BASE_KEYNAME			"gatewayAddress"
#define FIREWALL_TYPE_KEYNAME					"firewallType"
#define SAMPLE_STORAGE_PATH_KEYNAME				"SampleStoragePath"
#define ENABLE_TRACING_KEYNAME					"enableTracing"
#define SAMPLE_IMPORTER_DELAY_AFTER_NO_SAMPLES_AT_GATEWAY_KEYNAME	"sampleImporterDelayAfterNoSamplesAtGateway"
#define CLIENT_DELAY_AFTER_NETWORK_ERROR_KEYNAME	"ClientDelayAfterNetworkError"
#define STATUS_REPORTER_POLLING_INTERVAL_KEYNAME	"StatusReporterPollingInterval"
#define SAMPLE_IMPORTER_USE_SSL_KEYNAME			"sampleImporterUseSSL"
#define SAMPLE_IMPORTER_USE_SSL_DEFAULT			FALSE
#define ALLOW_USER_TO_RESPOND_TO_CRITICAL_ERROR_KEYNAME "allowUserToRespondToCriticalError"
#define SOUND_ALARM_ON_CRITICAL_ERROR_KEYNAME "soundAlarmOnCriticalError"

#define IGNORE_XERROR_CRUMBLED_KEYNAME			"ignoreXErrorCrumbled"
#define IGNORE_XERROR_CRUMBLED_DEFAULT			FALSE

#define IGNORE_INVALID_CERTIFICATE_SERVER_NAME_KEYNAME	"ignoreInvalidCertificateServerName"
#define IGNORE_INVALID_CERTIFICATE_SERVER_NAME_DEFAULT	FALSE

#define TIMEOUT_TRANSACTION_CONNECTED_KEYNAME	"timeoutTransactionConnected"
#define TIMEOUT_TRANSACTION_CONNECTED_DEFAULT	30

#define TIMEOUT_IMPORT_SAMPLE_TRANSACTION_COMPLETED_KEYNAME	"timeoutImportSampleTransactionCompleted"
#define TIMEOUT_IMPORT_SAMPLE_TRANSACTION_COMPLETED_DEFAULT	60

#define TIMEOUT_REPORT_STATUS_TRANSACTION_COMPLETED_KEYNAME	"timeoutReportStatusTransactionCompleted"
#define TIMEOUT_REPORT_STATUS_TRANSACTION_COMPLETED_DEFAULT	10

#define CONNECTION_TIMEOUT_DEFAULT				5
#define CONNECTION_RETRIES_DEFAULT				2
#define SEND_REQUEST_TIMEOUT_DEFAULT			3
#define SEND_REQUEST_DATA_TIMEOUT_DEFAULT		3
#define RECEIVE_RESPONSE_TIMEOUT_DEFAULT		3
#define RECEIVE_RESPONSE_DATA_TIMEOUT_DEFAULT	3
#define SAMPLE_IMPORTER_DELAY_AFTER_NO_SAMPLES_AT_GATEWAY_DEFAULT	5
#define CLIENT_DELAY_AFTER_NETWORK_ERROR_DEFAULT 5
#define STATUS_REPORTER_POLLING_INTERVAL_DEFAULT 1

#define ALL_TX_REQUIRED_HEADERS				"Connection: close" "\n" "Pragma: no-cache"
#define IMPORT_SAMPLE_TX_REQUIRED_HEADERS	"Accept: application/x-avis-sample" "\n" ALL_TX_REQUIRED_HEADERS
#define REPORT_STATUS_TX_REQUIRED_HEADERS	ALL_TX_REQUIRED_HEADERS

#define FIREWALL_TYPE_SOCKS "socks"
#define FIREWALL_TYPE_PROXY "proxy"
#define FIREWALL_TYPE_DEFINED_IN_REGISTRY "definedInRegistry"

#define SAMPLE_IMPORTER_AGENT_NAME	"AVIS Sample Importer"
#define INITIAL_STATUS_AGENT_NAME	"AVIS Sample Importer(initial status)"
#define STATUS_REPORTER_AGENT_NAME	"AVIS Status Reporter"

#define SAMPLE_IMPORTER_SHUTDOWN_TIMEOUT 1800
#define STATUS_REPORTER_SHUTDOWN_TIMEOUT 1800

#define READ_RESPONSE_BLOCK_SIZE	1024*4
#define NEW_SAMPLE_FILENAME			"sample.original"
#define SAMPLE_ATTRIBUTE_DIR		"SampleAttributes"
#define SAMPLE_ATTRIBUTE_FILE		"attributes.txt"

#define REPORT_STATUS_SERVLET_NAME	"/AVIS/postSampleStatus"
#define IMPORT_SAMPLE_SERVLET_NAME	"/AVIS/getSuspectSample"

#define SINGLE_INSTANCE_MUTEX_NAME "CAVISACSampleCommAppSingleInstanceObject"
