/////////////////////////////////////////////////////////////////////
// NAVRPC.H
//
// This header file defines our RPC stuff.
//

#if !defined (__NAVRPC_H)
#define __NAVRPC_H

/////////////////////////////////////////////////////////////////////
// defines for our protocols
//
// Use these to specify what protocols and endpoints the differnet
// RPC Servers / Clients are going to use.

#define NAVAPSVC_PROTOCOL "ncalrpc"
#define NAVAPSVC_ADDRESS  ""
#define NAVAPSVC_ENDPOINT "Navapsvc"

#define ALERTSVC_PROTOCOL "ncalrpc"
#define ALERTSVC_ADDRESS  ""
#define ALERTSVC_ENDPOINT "Alertsvc"

#define NAVW_PROTOCOL "ncalrpc"
#define NAVW_ADDRESS  ""
#define NAVW_ENDPOINT "Navw"


#endif // !defined (__NAVRPC_H)
