//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LDVPViewRes.rc
//
#define IDS_LDVPVIEW                    1
#define IDB_LDVPVIEW                    1
#define IDS_LDVPVIEW_PPG                2
#define IDS_CLOSE                       3
#define IDS_VIRUSNAME                   4
#define IDS_FAILED                      4
#define IDS_FILENAME                    5
#define IDS_MOVE                        5
#define IDS_RENAME                      6
#define IDS_SCHEDULE_OPTIONS            7
#define IDS_DELETE                      7
#define IDS_LEAVEALONE                  8
#define IDS_CLEAN                       9
#define IDC_EXTENSIONS                  10
#define IDS_INVALID                     10
#define IDS_CONFIG_SCAN                 11
#define IDS_ENABLED                     11
#define IDS_EXTENSION_EXECUTABLES       12
#define IDS_DISABLED                    12
#define IDS_CONFIG_RTS                  13
#define IDS_DATE_AT                     13
#define IDS_IDLE_SCAN                   14
#define IDS_TASK_VIRUS_HISTORY          14
#define IDS_CONFIG_SCAN_DESCRIPTION     15
#define IDS_TASK_VIRUS_HISTORY_DESCRIPTION 15
#define IDS_CONFIG_ACTIONS_DESCRIPTION  16
#define IDS_TASK_EVENT_LOG              16
#define IDS_CONFIG_RTS_DESCRIPTION      17
#define IDS_TASK_EVENT_LOG_DESCRIPTION  17
#define IDS_CONFIG_IDLE_DESCRIPTION     18
#define IDS_TASK_VIRUS_BIN              18
#define IDS_GROUP_CONFIGURATION         19
#define IDS_TASK_VIRUS_BIN_DESCRIPTION  19
#define IDS_EXTENSION_DOCUMENTS         20
#define IDS_GROUP_HISTORIES             20
#define IDS_EXTENSION_BAD_EXTENSION     21
#define IDS_TASK_SCAN_HISTORY           21
#define IDS_CONFIGURATION               22
#define IDS_TASK_SCAN_HISTORY_DESCRIPTION 22
#define IDS_SAVE_OPTIONS                23
#define IDS_DEFAULT_MESSAGE             23
#define IDS_SCAN_PROMPT_DAILY           23
#define IDS_SAVE                        24
#define IDS_SCAN_PROMPT_MONTHLY         24
#define IDS_SCAN                        25
#define IDS_SCAN_PROMPT_WEEKLY          25
#define IDS_EXTENSIONS_DESCRIPT         26
#define IDS_APP_NAME                    26
#define IDS_DEFAULT_EXTENSIONS          27
#define IDS_SCANDIALOGS_ERROR           27
#define IDS_COULD_NOT_CLEAN             28
#define IDS_MERIDIAN_POST               29
#define IDS_GROUP_MONITORING            30
#define IDS_VIEW_LOG                    31
#define IDS_VIEW_LOG_DESCRIPTION        32
#define IDS_FILE_READ_ERROR             33
#define IDS_LOG_FILTER                  34
#define IDS_LOCKED_OPTION               35
#define IDS_NO_WHATS_THIS_HELP          36
#define IDS_DIR_NOT_EXISTS              37
#define IDS_DIR_NOT_CREATE              38
#define IDS_INCORRECT_PASSWORD          39
#define IDS_NEXT                        40
#define IDS_SUNDAY                      41
#define IDS_MONDAY                      42
#define IDS_TUESDAY                     43
#define IDS_WEDNESDAY                   44
#define IDS_THURSDAY                    45
#define IDS_FRIDAY                      46
#define IDS_SATURDAY                    47
#define IDS_AM                          48
#define IDS_PM                          49
#define IDS_NO_SCHEDULE                 50
#define IDS_START                       51
#define IDS_STOP                        52
#define IDS_AC_NOTHING                  53
#define IDS_AC_BAD                      54
#define IDS_GL_EVENT_IS_ALERT           55
#define IDS_GL_EVENT_SCAN_STOP          56
#define IDS_GL_EVENT_SCAN_START         57
#define IDS_GL_EVENT_PATTERN_UPDATE     58
#define IDS_GL_EVENT_INFECTION          59
#define IDS_GL_EVENT_FILE_NOT_OPEN      60
#define IDS_GL_EVENT_LOAD_PATTERN       61
#define IDS_GL_STD_MESSAGE_INFO         62
#define IDS_GL_STD_MESSAGE_ERROR        63
#define IDS_GL_EVENT_CHECKSUM           64
#define IDS_GL_EVENT_TRAP               65
#define IDS_GL_EVENT_CONFIG_CHANGE      66
#define IDS_LOGGER_Scheduled            67
#define IDS_LOGGER_Manual               68
#define IDS_LOGGER_Real_Time            69
#define IDS_LOGGER_Integrity_Shield     70
#define IDS_LOGGER_Console              71
#define IDS_LOGGER_VPDOWN               72
#define IDS_LOGGER_SYSTEM               73
#define IDS_LOGGER_Forwarded            74
#define IDS_GL_CAT_INFECTION            75
#define IDS_GL_CAT_SUMMARY              76
#define IDS_GL_CAT_PATTERN              77
#define IDS_GL_CAT_SECURITY             78
#define IDS_GL_EVENT_STARTUP            79
#define IDS_GL_EVENT_PATTERN_DOWNLOAD   80
#define IDS_GL_EVENT_SHUTDOWN           81
#define IDS_GL_EVENT_TOO_MANY_VIRUSES   82
#define IDS_ACTION_MOVE                 83
#define IDS_ACTION_RENAME               84
#define IDS_ACTION_DELETE               85
#define IDS_ACTION_CLEAN                86
#define IDS_ACTION_LEAVEALONE           87
#define IDS_VIRUSES_FOUND               88
#define IDS_NOON                        89
#define IDS_LOGGER_IDLE                 90
#define IDS_MACRO                       91
#define IDS_NON_MACRO                   92
#define IDS_OPTION_MOVE                 93
#define IDS_OPTION_RENAME               94
#define IDS_OPTION_DELETE               95
#define IDS_OPTION_LEAVEALONE           96
#define IDS_OPTION_CLEAN                97
#define IDS_LANGUAGE_LOCAL              98
#define IDS_SERVICE_CANT_START          99
#define IDS_LDVPVIEW_PPG_CAPTION        100
#define IDD_PROPPAGE_LDVPVIEW           100
#define IDC_EXTENSION                   100
#define IDS_GROUP_HEADER                101
#define IDC_EXTENSION_ADD               101
#define IDS_SCAN_FLOPPY                 102
#define IDC_EXTENSIONS_LIST             102
#define IDC_EXTENSION_LIST              102
#define IDS_SCAN_FLOPPY_DESCRIPTION     103
#define IDC_EXTENSION_REMOVE            103
#define IDS_SCAN_DRIVE_DESCRIPTION      104
#define IDC_EXTENSION_EXECUTABLE        104
#define IDS_SCAN_DRIVE                  105
#define IDC_EXTENSION_DOCUMENTS         105
#define IDS_SCAN_SELECTED               106
#define IDS_SCAN_SELECTED_DESCRIPTION   107
#define IDS_TRANSLATION_NOTE1           110
#define IDS_TRANSLATION_NOTE2           111
#define IDD_RTS_MONITOR                 126
#define IDS_ERR_CREATE_SHELLSEL         147
#define IDS_TASK_1                      148
#define IDS_TASK_1_DESCRIPTION          149
#define IDS_ERROR_READ_DIRECTORY        182
#define IDS_ERROR_SHELLSEL_NONE_SELECTED 199
#define IDC_DESCRIPTION                 201
#define IDC_PLACE_HOLDER                202
#define IDC_DAY_OF_WEEK                 203
#define IDC_DAY_OF_MONTH                204
#define IDC_SCAN_PROGRESS               206
#define IDC_SCANNING_MEMORY             207
#define IDC_SCANNING_BOOT_SECTOR        208
#define IDC_SCANNING_DISK               209
#define IDB_OBJECTS                     219
#define IDC_DRIVES                      220
#define IDC_SPEC                        221
#define IDB_LOCKS                       221
#define IDC_CLEAN                       222
#define IDC_DELETE                      223
#define IDI_WAIT                        224
#define IDC_VIRUSES_FOUND               225
#define IDI_EXTENSIONS                  225
#define IDC_STOP_SCAN                   226
#define IDB_SCANSELECTEDISK             226
#define IDB_SCANFLOP                    227
#define IDC_DAILY                       228
#define IDC_WEEKLY                      229
#define IDC_DEFAULTS                    229
#define IDC_MONTHLY                     230
#define IDI_SCHEDULE                    230
#define IDC_SPIN_DAYS                   231
#define IDI_CUSTOMSCAN                  231
#define IDC_PH_CTRL                     237
#define IDD_SELECT_FOLDER               238
#define IDC_TYPES_ALL                   258
#define IDC_TYPES_SELECTED              259
#define IDC_ACTIONS_FOR                 260
#define IDC_FILE_TYPES                  261
#define IDC_COMPRESSED                  262
#define IDC_ACTION                      263
#define IDC_IF_ACTION_FAILS             265
#define IDC_ALL_DRIVES                  266
#define IDC_SELECTED_DRIVES             267
#define IDC_BROWSE_SELECTED_DRIVES      268
#define IDC_EXCLUDE_FILES               269
#define IDC_CHECK3                      270
#define IDC_BROWSE_EXCLUDE_FILES        271
#define IDC_CHECKSUM                    273
#define IDC_DISPLAY_ON_CONSOLE          274
#define IDC_CONFIGURE                   275
#define IDC_MESSAGE                     276
#define IDC_MOVE_FOLDER                 277
#define IDC_BROWSE_MOVE_FOLDER          278
#define IDC_SCAN_FLOPPY                 279
#define IDC_SCAN_CDROM                  280
#define IDC_SCAN_WHEN_MODIFIED          281
#define IDC_SCAN_WHEN_ACCESSED          282
#define IDC_ENABLE_RTS                  283
#define IDC_BROWSE_FILE_TYPES           285
#define IDC_BROWSE_EXCLUDE_SIGS         286
#define IDC_SELECTED_SIGS               287
#define IDC_ZIP_FILES                   288
#define IDC_ZIP_EXE                     289
#define IDC_EXCLUDE_SIGS                290
#define IDC_STATIC_PATH                 290
#define IDC_OPTIONS                     292
#define IDC_PATTENRNS                   296
#define IDC_LOG                         298
#define IDC_OPEN                        299
#define IDC_FILENAMES                   300
#define IDC_MONTHLY_TEXT                301
#define IDC_MONTHLY_AT                  302
#define IDC_WEEKLY_TEXT                 303
#define IDC_WEEKLY_AT                   304
#define IDC_DAILY_TEXT                  305
#define IDC_ONOFF                       306
#define IDC_PASSWORD                    310
#define IDC_IDLE_MINUTES                311
#define IDC_MINUTE_SPIN                 312
#define IDC_TITLE                       313
#define IDC_FILES                       314
#define IDC_SCHEDULE_INFO               315
#define IDC_SCHEDULE                    316
#define IDC_PASSWORD_TEXT               318
#define IDC_DENY_ACCESS                 319
#define IDC_MESSAGE_BEEP                320
#define IDC_FOLDERS                     321
#define IDC_COMPRESSED_STATIC           323
#define IDC_TOTAL_SCANED                324
#define IDC_LAST_FILE_SCANED            325
#define IDC_LAST_USER                   326
#define IDC_LAST_VIRUS_FOUND            327
#define IDC_LAST_VIRUS_FOUND_FILE       329
#define IDC_LAST_VIRUS_ACTION           330
#define IDC_DRIVER_ERROR                331
#define IDC_EXCPTIONS                   332
#define IDC_EXCPTIONS_TEXT              333
#define IDC_DRIVER_ERROR_TEXT           334
#define IDD_TASK_SCHEDULE               334
#define IDC_LIST1                       335
#define IDC_STATUS_GROUP                335
#define IDD_VIRUS_HISTORY               335
#define IDB_ASCENDING                   335
#define IDC_SCANNED_GROUP               336
#define IDD_EVENT_LOG                   336
#define IDB_DESCENDING                  336
#define IDC_VIRUSES_GROUP               337
#define IDD_VIRUS_BIN                   337
#define IDB_NONE                        337
#define IDD_SCAN_HISTORY                338
#define IDB_HISTORY_IMAGES              338
#define IDD_BACKUP                      339
#define IDC_TIME_STARTED                340
#define IDD_REPAIRED_ITEMS              340
#define IDC_LOCATION_TEXT               341
#define IDD_LICENSING                   341
#define IDC_LOCATION                    342
#define IDD_LS_LICENSING                343
#define IDC_TIME_OF_LAST_INFECTION      344
#define IDD_SCAN_HISTORY1               344
#define IDD_TAMPERBEHAVIOR_HISTORY      344
#define IDC_INSTRUCTIONS_TEXT           345
#define IDC_INSTALL_LICENSE             346
#define IDC_LIC_STATUS                  347
#define IDC_LIC_SERIAL_NUM              348
#define IDC_LIC_EXPIRY_DATE             349
#define IDC_LIC_START_DATE              350
#define IDC_INSTRUCTIONS_LINK           351
#define IDC_LIC_SKU_ID                  352
#define IDC_LIC_VENICE_ID               354
#define IDC_SYNC                        355
#define IDC_STARTED_STATUS              356
#define IDS_STARTING                    500
#define IDS_STOPPING                    501
#define IDS_SCANNING_DIRS               502
#define IDS_SCANNING_BOOT               503
#define IDS_SCANNING_MEM                504
#define IDS_STARTED                     505
#define IDS_SCANNING_FILES              506
#define IDS_NONE                        507
#define IDS_DAY                         508
#define IDS_WEEK                        509
#define IDS_MONTH                       510
#define IDS_SELEXT                      511
#define IDS_TASK_RTS                    512
#define IDS_TASK_RTS_DESCRIPTION        513
#define IDS_TASK_SCHEDULE               514
#define IDS_TASK_SCHEDULE_DESCRIPTION   515
#define IDS_ALLEXT                      516
#define IDS_NEVER                       517
#define IDS_SUBS                        518
#define IDS_NOT_RUNNING                 519
#define IDS_ABORTED                     520
#define IDS_NEVER_RUN                   521
#define IDS_COL_NEXT_TIME               522
#define IDS_COL_ICON                    522
#define IDS_COL_STATUS                  523
#define IDS_COL_NAME                    523
#define IDS_COL_FREQUENCEY              524
#define IDS_COL_WHEN                    524
#define IDS_COL_TIME                    525
#define IDS_COL_ORIGIN                  525
#define IDS_COL_FILES                   526
#define IDS_STATUS                      526
#define IDS_COL_DIRS                    527
#define IDS_COL_SCHEDULED_BY            528
#define IDS_BY_ADMIN                    529
#define IDS_BY_USER                     530
#define IDS_SCANDLVR                    532
#define IDS_TASK_BACKUP                 533
#define IDS_TASK_REPAIRED               534
#define IDS_TASK_BACKUP_DESCRIPTION     535
#define IDS_TASK_REPAIR_DESCRIPTION     536
#define IDS_NEW_DEFS                    537
#define IDS_REPAIRED_ITEMS              538
#define IDS_SCANNING_LOADPOINTS         539
#define IDS_SCANNING_ERASER_DEFS        540
#define IDS_STARTED2					541
#define IDS_ERROR_SCANDLVR_START        800
#define IDS_SCANDLVR_ITEMS_ALREADY_SUBMITTED 801
#define IDS_TASK_LICENSING              802
#define IDS_TASK_LICENSING_DESCRIPTION  803
#define IDS_LICENSE_ADMINTEXT           807
#define IDS_LICENSE_LINK                808
#define IDS_LS_LICENSE_ADMINTEXT        809
#define IDS_LS_LICENSE_LINK             810
#define IDS_NO_VENICEID                 811
#define IDS_COBRANDED_WEBSITE           812
#define IDS_LICENSE_RENEW_LINK          813
#define IDC_NAME                        1007
#define IDC_TASK_DESCRIPTION            1008
#define IDC_CHILDREN                    1015
#define IDC_PATH                        1029
#define IDS_TASK_TAMPERBEHAVIOR_HISTORY 1030
#define IDS_TASK_TAMPERBEHAVIOR_HISTORY_DESCRIPTION 1031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        344
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         357
#define _APS_NEXT_SYMED_VALUE           334
#endif
#endif
