// This is the Norton AntiVirus Build.h file

#define VER_STR_PRODUCT_SIRNAME "Norton AntiVirus"
#define VER_STR_BUILDNUMBER "1"
#define VER_NUM_BUILDNUMBER 1
#define VER_STR_PRODVERMAJOR "12"
#define VER_NUM_PRODVERMAJOR 12
#define VER_STR_PRODVERMINOR "0"
#define VER_NUM_PRODVERMINOR 0
#define VER_STR_PRODVERSUBMINOR "6"
#define VER_NUM_PRODVERSUBMINOR 6
#define VER_STR_PRODVERYEAR "2006"
#define VER_NUM_PRODVERYEAR 2006
#define VER_STR_PRODVERTUPLE  VER_STR_PRODVERMAJOR "." VER_STR_PRODVERMINOR "." VER_STR_PRODVERSUBMINOR
#define VER_STR_PRODVERDUO  VER_STR_PRODVERMAJOR "." VER_STR_PRODVERMINOR
#define VER_STR_COMPANYNAME "Symantec Corporation"
#define VER_STR_COPYRIGHT "Norton AntiVirus 2006 for Windows 2000/XP Copyright © 2005 Symantec Corporation. All rights reserved."
#define VER_NUM_BUILDMONTH 05
#define VER_NUM_BUILDDAY 10
#define VER_NUM_BUILDYEAR 2006
#define VER_STR_BUILDDATETUPLE "05/10/2006"
