//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NAVError.rc
//
#define IDR_NAVCOMERROR								101
#define IDS_CAPTION									102
#define IDS_NAVERROR_INTERNAL_REINSTALL    			103
#define IDS_NAVERROR_INTERNAL              			104
#define IDS_NAVERROR_NAVAPSCR_REGISTRYPERMISSIONS	105
#define IDS_NAVERROR_NAVAPSCR_SAFE_MODE				106
#define IDS_NAVERROR_NAVLNCH_NO_QCONSOLE			107
#define IDS_NAVERROR_NAVLNCH_NO_LU					108
#define IDS_NAVERROR_NAVLNCH_NO_RESCUE				109
#define IDS_NAVERROR_NAVLNCH_RESCUE_NOT_INSTALLED	110
#define IDS_NAVERROR_NAVLNCH_NO_HELP				111
#define IDS_NAVERROR_NAVLNCH_FAILED_START_EMAIL		112
#define IDS_NAVERROR_NAVLNCH_NO_UEW					113
#define IDS_NAVERROR_NAVLNCH_NO_WIPEINFO			114
#define IDS_NAVERROR_NO_COMPONENT           		115 
#define IDS_NAVERROR_NAVLNCH_FAILED_LAUNCH_SUBSWIZ	116
#define IDS_NAVERROR_NAVLNCH_NO_NAV					117
#define IDS_NAVERROR_NDSCHEDULER					118



// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
