//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AvProdServiceRes.rc
//
#define IDS_APNOTIFY_TEXT_START_THREATNAME 103
#define IDS_APNOTIFY_TEXT_FINISHED_NOTHREATNAME 104
#define IDS_APNOTIFY_TEXT_START_NOTHREATNAME 105
#define IDS_APNOTIFY_THREAT_BLOCKED_TEXT 106
#define IDS_THREAT_STATE_NOT_REMOVED    107
#define IDS_EMAILSCAN_DETAILS_THREAT_ENTRY 108
#define IDS_THREAT_STATE_REMOVED        109
#define IDS_ACTIONREQUIRED_REBOOT_TEXT  110
#define IDS_APNOTIFY_HEIGHT             111
#define IDS_APNOTIFY_WIDTH              112
#define IDS_APNOTIFY_MORE_INFO_TEXT     113
#define IDS_APNOTIFY_TEXT_FINISHED_THREATNAME 114
#define IDS_OEHACTION_IGNORED           115
#define IDS_OEHACTION_QUARANTINED       116
#define IDS_OEHACTION_ABORTED           117
#define IDS_OEHACTION_AUTHORIZED        118
#define IDS_APNOTIFY_TEXT_UNRESOLVED_THREATS 119
#define IDS_OEHACTION_ABORTED_QUARANTINED 120
#define IDS_APNOTIFY_TEXT_PROCESSING    121
#define IDS_APNOTIFY_TITLE              122
#define IDS_APNOTIFY_AVACTION_IGNORED   123
#define IDS_APNOTIFY_AVACTION_REMOVED   124

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        123
#define _APS_NEXT_COMMAND_VALUE         50001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
