// Copyright 1998 Symantec Corporation. 
//*************************************************************************
// defwatch.h - created 11/6/98 1:57:15 PM
//
// $Header$
//
// Description:
//
// Contains:
//
//*************************************************************************
// $Log$
//*************************************************************************

#ifndef _DEFWATCH_H_
#define _DEFWATCH_H_

// 
// This file is generated by the MC message compiler.
// 
#include "dwmsg.h"

// 
// Macros
// 
#define DEFWATCH_SERVICE_NAME           TEXT( "DefWatch" )
#define SYMANTEC_INSTALLED_APPS_KEY     _T( "SOFTWARE\\Symantec\\InstalledApps" )
#define AVENGEDEFS_VAL                  _T( "AVENGEDEFS" )
#define DEFINFO_DAT                     _T( "DEFINFO.DAT" )
#define DEFWATCH_REG_KEY                _T( "SOFTWARE\\Symantec\\Norton AntiVirus\\DefWatch" )
#define DEFWATCH_HANDLERS_REG_KEY       _T( "SOFTWARE\\Symantec\\Norton AntiVirus\\DefWatch\\Handlers" )
#define DEFWATCH_DEFVER_VAL             _T( "DefVersion" )
#define HAWKING_APP_ID                  "NAVNT_50_NAVW"


// 
// Prototypes
// 
#ifdef _DEBUG
void DefWatchDebugOut(LPSTR String, DWORD Status = 0);
#else
#define DefWatchDebugOut
#endif


void DefWatchLogEvent( DWORD dwMsgID,
					   WORD wType = EVENTLOG_ERROR_TYPE,
					   LPSTR lpszParam1 = NULL ,
					   LPSTR lpszParam2 = NULL ,
					   LPSTR lpszParam3 = NULL ,
					   LPSTR lpszParam4 = NULL  );
#endif