[InstallShield Silent]
Version=v5.00.000
File=Response File
[File Transfer]
OverwriteReadOnly=NoToAll
[DlgOrder]
Dlg0=SdWelcome-0
Count=10
Dlg1=SdLicense-0
Dlg2=SdAskDestPath-0
Dlg3=DlgNavSetupType-0
Dlg4=DlgInitialSettings-0
Dlg5=SdStartCopy-0
Dlg6=DlgAdvo1-0
Dlg7=DlgAdvo2-0
Dlg8=DlgScanForViruses-0
Dlg9=SdFinish-0
[SdWelcome-0]
Result=1
[SdLicense-0]
Result=1
[SdAskDestPath-0]
szDir=Default
Result=1
[DlgNavSetupType-0]
SetupTypeConnected=0
Result=1
[DlgInitialSettings-0]
StartAutoProtect=1
ScheduleScan=1
Result=1
[SdStartCopy-0]
Result=1
[Application]
Name=Symantec AntiVirus Corporate Edition
Version=7.0
Company=Symantec
Lang=0009
[DlgAdvo1-0]
Result=1
[DlgAdvo2-0]
Result=1
[DlgScanForViruses-0]
RunLiveUpdateAfterInstall=1
RunScanAfterInstall=1
Result=1
[SdFinish-0]
Result=1
bOpt1=0
bOpt2=0
