//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DFGui.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DFGUITYPE                   129
#define IDB_BITMAP1                     130
#define IDD_DIALOG1                     133
#define IDD_CONFIGURE_DIALOG            133
#define IDD_STATISTICS_DIALOG           134
#define IDD_CHANGE_PRIORITY             136
#define IDB_BITMAP2                     137
#define IDB_BITMAP4                     147
#define IDB_BITMAP5                     148
#define IDD_SAMPLEATTRIBUTES            150
#define IDC_UNCPATH                     1002
#define IDC_STATIC0                     1002
#define IDC_CACHECHECKINTERVAL          1003
#define IDC_STATIC1                     1003
#define IDC_DIRECTORYCACHEEXPIRYTIME    1004
#define IDC_STATIC2                     1004
#define IDC_SAMPLESUBMISSIONINTERVAL    1005
#define IDC_STATIC3                     1005
#define IDC_SAMPLEARRIVALCHECKINTERVAL  1006
#define IDC_STATIC4                     1006
#define IDC_CONCURRENTNUMBEROFSAMPLES   1007
#define IDC_STATIC5                     1007
#define IDC_EDIT1                       1008
#define IDC_TRACKING_NUMBER             1008
#define IDC_STATIC6                     1008
#define IDC_EDIT2                       1009
#define IDC_MAX_SAMPLES                 1009
#define IDC_PRIORITY                    1009
#define IDC_EDIT4                       1011
#define IDC_CACHE_INTERVAL              1011
#define IDC_DEF_BASE_DIR                1011
#define IDC_EDIT5                       1012
#define IDC_DIR_INTERVAL                1012
#define IDC_BUILD_DEF_FILENAME          1012
#define IDC_EDIT6                       1013
#define IDC_ARRIVAL_INTERVAL            1013
#define IDC_UNC                         1014
#define IDC_NUMBER_OF_SAMPLES           1015
#define IDC_DATABASE_RESCAN_INTERVAL    1015
#define IDC_NUMBER_OF_SUCCESS_SAMPLES   1016
#define IDC_AVERAGE_TIME                1017
#define IDC_START_TIME                  1018
#define IDC_NUMBER_OF_RESCANNED_SAMPLES 1019
#define IDC_EDIT3                       1020
#define IDC_SUBMISSION_INTERVAL         1020
#define IDC_BUILDNUMBER                 1020
#define IDC_NUMBER_OF_DEFERRED_SAMPLES  1020
#define IDC_DEF_IMPORT_INTERVAL         1028
#define IDC_STATUS_UPDATE_INTERVAL      1029
#define IDC_DEF_IMPORTER_DIR            1032
#define IDC_UNDEFERRER_INTERVAL         1033
#define IDC_SAMPLEID                    1035
#define IDC_ATTRIBUTE_INTERVAL          1036
#define ID_END                          32772
#define ID_POSTPONE                     32773
#define ID_TIMEOUT                      32774
#define ID_IGNORE                       32775
#define ID_ACCEPT                       32776
#define ID_LAUNCHER_SHOW                32777
#define ID_SAMPLE_HOLD                  32778
#define ID_SAMPLE_IGNORE                32779
#define ID_RESUME                       32780
#define ID_DELETE                       32781
#define ID_HOLD                         32782
#define ID_STOP                         32783
#define ID_DISABLE                      32784
#define ID_ENABLE                       32785
#define ID_HOLDALL                      32786
#define ID_RESUMEALL                    32787
#define ID_STATISTICS                   32789
#define ID_CONFIGURE                    32790
#define ID_CHANGEPRIORITY               32791
#define ID_DEFER                        32792
#define ID_STOPIMPORT                   32794
#define ID_STOPUNDEFERRER               32795
#define ID_STOPUPDATER                  32796
#define ID_SAMPLEATTRIBUTES             32797
#define ID_STOPATTRCOLLECTOR            32798
#define IDS_OPEN_FILE_ERROR             61446
#define IDS_LIST_SAMPLE                 61447
#define IDS_LIST_CURRENT_STATE          61448
#define IDS_LIST_STATUS                 61449
#define IDS_LIST_NEXT_STATE             61450
#define IDS_LIST_JOBS                   61451
#define IDS_LIST_SAMPLE_TIP             61452
#define IDS_LIST_CURRENT_STATE_TIP      61453
#define IDS_LIST_STATUS_TIP             61454
#define IDS_LIST_NEXT_STATE_TIP         61455
#define IDS_LIST_JOBS_TIP               61456
#define IDS_AVIS_TITLE                  61457
#define IDS_EVALUATOR_ERROR             61458
#define IDS_TEMP_STATUS                 61459
#define IDS_INDICATOR_COUNT             61460
#define IDS_INDICATOR_SAMPLECOUNT       61461
#define IDS_INDICATOR_SAMPLE            61462
#define IDS_LIST_HOLD                   61463
#define IDS_DATAFLOW_STATUS             61464
#define IDS_INDICATOR_DATAFLOWSTATUS    61465
#define IDS_STATUS_ENABLE               61466
#define IDS_STATUS_DISABLE              61467
#define IDS_REPOSITORY                  61468
#define IDS_PATH                        61469
#define IDS_NAME                        61470
#define IDS_CONFIG_FILE_ERROR           61471
#define IDS_IMPORTED                    61472
#define IDS_AFTERDEFQUEUE               61473
#define IDS_AFTERDEFBUILDER             61474
#define IDS_RESULT                      61475
#define IDS_UNCPATH                     61476
#define IDS_CFG_FILE                    61477
#define IDS_CONFIRM_MSG1                61478
#define IDS_CONFIRM_MSG2                61479
#define IDS_CHECK_CASH_INT              61480
#define IDS_CHECK_DIR_INT               61481
#define IDS_TIMER_INTERVAL              61482
#define IDS_SAMPLE_REQUEST_DELAY        61483
#define IDS_MAX_SAMPLES                 61484
#define IDS_MAX_SAMPLES2                61485
#define IDS_CONFIG_FILE_CREATE_ERROR    61486
#define IDS_CONFIG_FILE_CREATE_WARNING  61487
#define IDS_CONFIG_FILE_UNC_EMPTY       61488
#define IDS_CONFIG_FILE_EMPTY_FIELDS    61488
#define IDS_CONFIG_FILE_SAVE_INFO       61489
#define IDS_DATABASE_OPEN_ERROR         61490
#define IDS_DATABASE_CLOSE_ERROR        61491
#define IDS_PRIORITY                    61492
#define IDS_LIST_PRIORITY               61493
#define IDS_DEFER                       61494
#define IDS_DABASE_ADD_NEW_STATE_ERROR  61495
#define IDS_HOLD                        61496
#define IDS_DATABASE_UPDATE_PRIORITY_ERROR 61497
#define IDS_WAIT                        61498
#define IDS_DATABASE_GET_RECORD_ERROR   61499
#define IDS_DATABASE_UPDATE_RECORD_ERROR 61500
#define IDS_DATABASE_ADD_NEW_STATE_ERROR 61501
#define IDS_SUCCESS                     61502
#define IDS_INPROGRESS                  61503
#define IDS_FAIL                        61504
#define IDS_FINAL                       61505
#define IDS_BUILD_DEF_FILENAME          61506
#define IDS_DEF_BASE_DIR                61507
#define IDS_RESCAN_STRING               61508
#define IDS_DATABASE_GET_LATEST_SIGNATURE_ERROR 61509
#define IDS_RESCAN_FILTER               61510
#define IDS_INITIAL_RESCAN              61511
#define IDS_CRITICAL_ERROR              61512
#define IDS_MAIL_STRING                 61513
#define IDS_MAIL_STRING1                61514
#define IDS_DEFER_MSG                   61515
#define IDS_BLOCK_MSG                   61516
#define IDS_DATABASE_RESCAN_INTERVAL    61517
#define IDS_DEF_IMPORT_INTERVAL         61518
#define IDS_STATUS_UPDATE_INTERVAL      61519
#define IDS_DEF_IMPORTER_DIR            61520
#define IDS_UNDEFERRER_INTERVAL         61521
#define IDS_BLOCK_MSG1                  61522
#define IDS_SCHED_TASKS_IND             61523
#define IDS_SCHED_TASKS_IND1            61524
#define IDS_STOP_IMPORTER               61525
#define IDS_STOP_UNDEFERRER             61526
#define IDS_STOP_UPDATER                61527
#define IDS_STOP_ATTRIBUTECOLLECTOR     61527
#define IDS_SAMPLE_DEFER_QST            61528
#define IDS_ATTRIBUTE_FILE_ERROR        61529
#define IDS_SELECTION_ERROR             61530
#define IDS_ATTRIBUTE_INTERVAL          61531
#define IDS_STOP_UPDATER1               61532
#define IDS_WAIT_FOR_NEWDEF_MSG         61533
#define IDS_CFG_PROLOG                  61534

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32799
#define _APS_NEXT_CONTROL_VALUE         1038
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
