//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MigApp.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MIGAPP_DIALOG               102
#define IDS_MIGRATE_TEXT1               102
#define IDS_MIGRATE_CAPTION             103
#define IDR_MAINFRAME                   128
#define IDC_MIGRATE_TEXT1               1001
#define ID_CONTACT_INFO                 1002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
