/////////////////////////////////////////////////////////////////////
// File: stdafx.cpp
//
// Copyright 1992-1997 Symantec, Peter Norton Product Group
/////////////////////////////////////////////////////////////////////
// $Header:   S:/ATMIGAPP/VCS/STDAFX.H_v   1.0   27 May 1998 17:27:40   SEDWARD  $
//
// Description:
// stdafx.h : include file for standard system include files,
//  or project specific include files that are used frequently, but
//      are changed infrequently
//
/////////////////////////////////////////////////////////////////////
//
// $Log:   S:/ATMIGAPP/VCS/STDAFX.H_v  $
// 
//    Rev 1.0   27 May 1998 17:27:40   SEDWARD
// Initial revision.
//
//
/////////////////////////////////////////////////////////////////////


#if !defined(AFX_STDAFX_H__EB9F509D_659D_11D1_9D4A_00C04FB906C0__INCLUDED_)
#define AFX_STDAFX_H__EB9F509D_659D_11D1_9D4A_00C04FB906C0__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#define VC_EXTRALEAN		// Exclude rarely-used stuff from Windows headers

#include <afxwin.h>         // MFC core and standard components
#include <afxext.h>         // MFC extensions
#include <afxdisp.h>        // MFC OLE automation classes
#ifndef _AFX_NO_AFXCMN_SUPPORT
#include <afxcmn.h>			// MFC support for Windows Common Controls
#endif // _AFX_NO_AFXCMN_SUPPORT


//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_STDAFX_H__EB9F509D_659D_11D1_9D4A_00C04FB906C0__INCLUDED_)