//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Sav9UninstallFix.rc
//
#define IDS_ERROR_DETECTINGSAV9         501
#define IDS_ERROR_DETECTINGSCS2         502
#define IDS_WARNING_TOOMANYPRODUCTCODES 503
#define IDS_WARNING_NODETECTIONS        504
#define IDS_ERROR_ADDINGBINARYTABLERECORD 505
#define IDS_ERROR_ADDINGCUSTOMACTION    506
#define IDS_ERROR_ADDINGSEQUENCERECORD  507
#define IDS_ERROR_EXTRACTINGFILE        508
#define IDS_ERROR_OPENINGFILE           509
#define IDS_INFO_BANNERLINE1            510
#define IDS_ERROR_LOCATINGPACKAGE       511
#define IDS_ERROR_FINDINGINSTALLDIR     512
#define IDS_INFO_ALREADYAPPLIED         512
#define IDS_ERROR_LOCATINGPRODUCT       513
#define IDS_WARNING_LOCATIONGBASEACTION 514
#define IDS_INFO_BANNERLINE2            515
#define IDS_INFO_APPLYSUCCESS           516
#define IDS_ERROR_DETECTINGSAV10        517
#define IDS_ERROR_DETECTINGSCS3         518
#define IDS_PRODUCT_VERSION_FOUND       519

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        504
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           501
#endif
#endif
