//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NavWinX.rc
//
#define IDS_NODENAME                    3
#define IDS_NAVEXTENSION_DESC           6
#define IDS_PROJNAME                    100
#define IDS_MENU_CONFIG_95              101
#define IDS_MENU_CONFIG_95_DESC         102
#define IDS_MENU_CONFIG_NT              103
#define IDS_MENU_CONFIG_NT_DESC         104
#define IDS_MENU_CONFIG_NTS             105
#define IDS_MENU_CONFIG_NTS_DESC        106
#define IDS_PRODUCT_FAMILY              107
#define IDS_PRODUCT_NAV95               108
#define IDS_PRODUCT_NAVNT               109
#define IDS_PRODUCT_NAVNTS              110
#define IDS_PRODUCT_COMPONENT_VERSION   111
#define IDS_PRODUCT_COMPONENT_DESC      112
#define IDS_SNAPIN_DESC                 113
#define IDS_VERSION                     114
#define IDS_VENDOR                      115
#define IDI_NAV_BAG                     201
#define IDI_NAVSERVER_BAG               202
#define IDB_MAINAPP_32                  203
#define IDB_MAINAPP_16                  204
#define IDI_MAINAPP                     205

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        206
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
