// Copyright 1992 - 1994 Symantec, Peter Norton Group
// ************************************************************************
//
// $Header:   S:/NAVWINX5/VCS/STDAFX.CPv   1.0   01 Jun 1998 16:07:48   DBuches  $
//
// Description:
//
// See Also:
//
// ************************************************************************
// $Log:   S:/NAVWINX5/VCS/STDAFX.CPv  $
// 
//    Rev 1.0   01 Jun 1998 16:07:48   DBuches
// Initial revision.
// 
//    Rev 1.0   01 Mar 1998 18:51:54   pagbabi
// Initial revision.
// ************************************************************************

// stdafx.cpp : source file that includes just the standard includes
//  stdafx.pch will be the pre-compiled header
//  stdafx.obj will contain the pre-compiled type information

#include "stdafx.h"

#ifdef _ATL_STATIC_REGISTRY
#include <statreg.h>
#include <statreg.cpp>
#endif

#include <atlimpl.cpp>
