//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DefAnnty.rc
//
#define IDS_SUBSCRIBE_DIRECTIONS        1
#define IDS_DEFANNUITY_TITLE            2
#define IDS_TRIAL_LAST_DAY_WARNING      3
#define IDS_FREE_LAST_DAY_WARNING       4
#define IDS_TRIAL_WARNING               5
#define IDS_FREE_WARNING                6
#define IDS_TRIAL_EXPIRED               7
#define IDS_FREE_EXPIRED                8
#define IDS_SUBSCRIPTION_LAST_DAY_WARNING 9
#define IDS_SUBSCRIPTION_WARNING        10
#define IDS_SUBSCRIPTION_EXPIRED        11
#define IDOK2                           12
#define IDOK3                           13
#define IDS_WIZTITLE                    101
#define IDS_BADCONFIRMATION             102
#define IDS_WIZARDFMT1                  103
#define IDS_WIZARDFMT1_ONE_DAY          104
#define IDS_WIZARDFMT2                  105
#define IDS_WIZARDFMT2_ONE_DAY          106
#define IDS_PHONES                      107
#define IDS_PHONE01                     108
#define IDS_PHONE01A                    109
#define IDS_PHONE02                     110
#define IDS_PHONE03                     111
#define IDS_PHONE03A                    112
#define IDS_PHONE04                     113
#define IDS_PHONE04A                    114
#define IDS_PHONE05                     115
#define IDS_PHONE06                     116
#define IDS_PHONE07                     117
#define IDS_PHONE08                     118
#define IDS_PHONE08A                    119
#define IDS_PHONE08B                    120
#define IDS_PHONE08C                    121
#define IDS_PHONE09                     122
#define IDS_PHONE10                     123
#define IDS_PHONE10A                    124
#define IDS_PHONE11                     125
#define IDS_PHONE12                     126
#define IDS_PHONE12A                    127
#define IDS_PHONE13                     128
#define IDS_PHONE14                     129
#define IDS_PHONE15                     130
#define IDS_PHONE15A                    131
#define IDS_PHONE15B                    132
#define IDS_PHONE16                     133
#define IDS_PHONE17                     134
#define IDS_PHONE17A                    135
#define IDD_DIALOG7                     135
#define IDS_PHONE18                     136
#define IDD_DIALOG8                     136
#define IDS_PHONE18A                    137
#define IDD_DIALOG9                     137
#define IDS_PHONE19                     138
#define IDR_MAINFRAME                   138
#define IDD_DIALOG10                    138
#define IDS_PHONE20                     139
#define IDD_DIALOG11                    139
#define IDS_PHONE20A                    140
#define IDD_DIALOG12                    140
#define IDS_PHONE20B                    141
#define IDD_DIALOG13                    141
#define IDS_PHONE21                     142
#define IDD_DIALOG14                    142
#define IDS_PHONE21A                    143
#define IDD_DIALOG15                    143
#define IDS_PHONE21B                    144
#define IDS_PHONE21C                    145
#define IDB_BITMAP2                     145
#define IDS_PHONE21D                    146
#define IDB_BITMAP3                     146
#define IDS_PHONE21E                    147
#define IDB_BITMAP4                     147
#define IDS_PHONE21F                    148
#define IDD_SYMANTEC_WORLDWIDE          148
#define IDS_PHONE21G                    149
#define IDB_BITMAP2_256                 149
#define IDS_PHONE21H                    150
#define IDB_BITMAP3_256                 150
#define IDS_PHONE21I                    151
#define IDB_BITMAP4_256                 151
#define IDS_PHONE21J                    152
#define IDD_DIALOG11PRE                 152
#define IDS_PHONE21K                    153
#define IDD_DIALOG16                    153
#define IDS_PHONE22                     154
#define IDB_BITMAP7_256                 154
#define IDB_BITMAP8_256                 155
#define IDB_BITMAP9_256                 156
#define IDB_BITMAP10_256                157
#define IDB_BITMAP11P_256               158
#define IDB_BITMAP11_256                159
#define IDB_BITMAP12_256                160
#define IDB_BITMAP13_256                161
#define IDB_BITMAP14_256                162
#define IDB_BITMAP15_256                163
#define IDB_BITMAP16_256                164
#define IDC_HAND_CURSOR                 165
#define IDS_HEADER_FONT                 166
#define IDC_WORLDWIDE                   1000
#define IDC_WORLDWIDE_TEXT              1001
#define IDC_TITLESTATIC                 1002
#define IDC_RADIO1                      1003
#define IDC_RADIO2                      1004
#define IDC_EDIT2                       1005
#define IDC_WIZFORMAT                   1006
#define IDC_STATIC_BMP256               1008
#define IDC_STATIC_BMP16                1009
#define IDC_INTERLINK                   1010

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        166
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1012
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
