/////////////////////////////////////////////////////////////////////
// NPSSTR.STR
//
// This is where we will have all the strings that would normally
// be loaded from a string table in the Windows half of the program.
//

#include "platform.h"

                                        // File Names
char    *szNPSBinFile    = "Schedule.Dat";
char    *szNPSBinBakFile = "Schedule.Bak";

char    *szNPSHeaderFile  = "NPSFILE";
char    *szNPSHeaderEntry = "NPSENTRY";

char    *szNPSReloadDataEventName = "NPS Data Reload Event";

char    *szNPSUIWndClassName = "npsWClass";
char    *szNPSServiceName = "Norton Program Scheduler";

char    *szNPS95Binary = "NSched32.exe";
char    *szNPSNTBinary = "NPSSvc.exe";
