// PROPRIETARY/CONFIDENTIAL. Use of this product is subject to license terms.
// Copyright (c) 2005 Symantec Corporation. All rights reserved.
// AvisEventRulesData.h 


#ifndef _AVIS_EVENT_RULES_DATA_H_INCLUDED
#define	_AVIS_EVENT_RULES_DATA_H_INCLUDED


// EVENT NAMES

#define GENERAL_ATTENTION_UNAVAILABLE_EVENTNAME_ID    IDSTABLE_UNAVAILABLE_EVENTNAME           //   _T("Waiting for needed definitions")
#define GENERAL_ATTENTION_SHUTDOWN_EVENTNAME_ID       IDSTABLE_SHUTDOWN_EVENTNAME              //   _T("The Quarantine Agent service has stopped")
#define GENERAL_ATTENTION_DEFCAST_EVENTNAME_ID        IDSTABLE_DEFCAST_EVENTNAME               //   _T("DefCast Error")
#define GENERAL_ATTENTION_DISK_EVENTNAME_ID           IDSTABLE_DISK_EVENTNAME                  //   _T("Unable to access definition directory")
#define GENERAL_ATTENTION_SCANEXPLICIT_EVENTNAME_ID   IDSTABLE_SCANEXPLICIT_EVENTNAME          //   _T("Cannot connect to the ScanExplicit Service")
#define GENERAL_ATTENTION_TARGET_EVENTNAME_ID         IDSTABLE_TARGET_EVENTNAME                //   _T("Cannot install definitions on one or more machines")
#define GENERAL_ATTENTION_GATEWAY_COMM_EVENTNAME_ID   IDSTABLE_GATEWAY_COMM_EVENTNAME          //   _T("Unable to connect to the Gateway")
#define DEF_ALERT_NEW_BLESSED_DEFS_EVENTNAME_ID       IDSTABLE_BLESSED_DEFS_EVENTNAME          //   _T("New Blessed definitions arrived")
#define DEF_ALERT_NEW_UNBLESSED_DEFS_EVENTNAME_ID     IDSTABLE_UNBLESSED_DEFS_EVENTNAME        //   _T("New Unblessed definitions arrived")


#define SAMPLE_ALERT_HELD_EVENTNAME_ID                IDSTABLE_SAMPLE_HELD_EVENTNAME           //   _T("Sample: held for submission")
#define SAMPLE_ALERT_ATTENTION_EVENTNAME_ID           IDSTABLE_SAMPLE_ATTENTION_EVENTNAME      //   _T("Sample: needs attention from Tech Support")
#define SAMPLE_ALERT_ERROR_EVENTNAME_ID               IDSTABLE_SAMPLE_ERROR_EVENTNAME          //   _T("Sample: processing error")
#define DEF_ALERT_NOT_INSTALLED_EVENTNAME_ID          IDSTABLE_SAMPLE_NOTINSTALLED_EVENTNAME   //   _T("Sample: new definitions failed to be delivered")
#define SAMPLE_ALERT_AVAILABLE_EVENTNAME_ID           IDSTABLE_SAMPLE_AVAILABLE_EVENTNAME      //   _T("Sample: new definitions held for delivery")
#define SAMPLE_ALERT_QUARANTINED_EVENTNAME_ID         IDSTABLE_SAMPLE_QUARANTINED_EVENTNAME    //   _T("Sample: too long with Quarantined status")
#define SAMPLE_ALERT_SUBMITTED_EVENTNAME_ID           IDSTABLE_SAMPLE_SUBMITTED_EVENTNAME      //   _T("Sample: too long with Submitted status")
#define SAMPLE_ALERT_RELEASED_EVENTNAME_ID            IDSTABLE_SAMPLE_RELEASED_EVENTNAME       //   _T("Sample: too long with Released status")
#define DEF_ALERT_INSTATE_NEEDED_EVENTNAME_ID         IDSTABLE_DEF_NEEDED_EVENTNAME            //   _T("Sample: too long with Needed status")
#define DEF_ALERT_INSTATE_DISTRIBUTED_EVENTNAME_ID    IDSTABLE_DEF_DISTRIBUTED_EVENTNAME       //   _T("Sample: too long with Distributed status")
#define DEF_ALERT_INSTATE_DISTRIBUTE_EVENTNAME_ID     IDSTABLE_DEF_DISTRIBUTE_EVENTNAME        //   _T("Sample: too long without installing new defs")

// LOCAL QUARANTINE
#define SAMPLE_ALERT_QUARANTINE_NOT_REPAIRED_ID       IDSTABLE_Q_NOT_REPAIRED_EVENTNAME        //   _T("Sample: was not repaired")

// SEND TEST EVENT
#define SEND_TEST_EVENT_NAME_ID                       IDSTABLE_SEND_TEST_EVENTNAME             //   _T("Central Quarantine Test Event")
//#define SEND_TEST_EVENT_TEXT                        IDSTABLE_TEXT_SEND_TESTEVENT             //   _T("A test alert will be sent to the AMS server, the next scheuled time Quarantine Server is configured to look for events.")
#define SEND_TEST_EVENT_TEXT_ID                       IDSTABLE_TEXT_SEND_TESTEVENT             // _T("A test alert will be sent to the AMS server, the next scheuled time Quarantine Server is configured to look for events.")


// MISC STRINGS
#define STAB_TEXT_UNABLE_TO_DISTRIBUTE_DEFS_ID        IDSTABLE_TEXT_UNABLE_TO_DISTRIBUTE_DEFS   //  _T("Unable to distribute definitions to target")


// typedef struct
// {
//     TCHAR*      lpszIcePackToken;
//     DWORD       dwIsConfigurable;             // Can the user configure this one?
// 	   DWORD	   dwEnabled;                    // Is this event enabled?
//     DWORD       dwIsConfigMinTimeInState;     // Can the user set dwMinTimeInStateSecs
//     DWORD       dwMinTimeInStateSecs;         // Is there a min interval? 0== immediate
//     DWORD       dwInStateTimerExpire;         // Stop time for the timer
//     BOOL	       bIsDataChanged;               // Has the record been modified?
// 	   DWORD	   dwEventGroupType;
//     DWORD       dwEventId;
// 	   DWORD	   dwAlertSeverityLevel;         // Severity level of the alert. Table is listed below.
//     DWORD	   dwOperationalStatusLevel;     // Resulting operational status of the application. 
//     DWORD       dwIcePackTokenTableID;        // Which IcePack token table to use
//     TCHAR*      lpszDefaultMessage;
//     LPCTSTR     lpszRegValue;                 // Registry value name for this event configuration
//     TCHAR*      lpszEventName;                // Name of the event
// 
// }  AVIS_EVENT_RULES;


#ifndef g_AvisEventRulesGeneralAttention
// GLOBAL
AVIS_EVENT_RULES  g_AvisEventRulesGeneralAttention[] =
{
    // DISK SPACE WARNING EVENTS
    TOKEN_DISKSPACE_LOW_WATER, 1, 1,1,30, 0, 0, 0, EVENT_GROUP_DISK_WARNING      , GENERAL_ATTENTION_DISKSPACE_LOW_WATER   , _SEVERITY_MINOR   , OP_STATUS_OPERATIONAL, ICEPACK_TOKEN_ATTENTION_TABLE, NULL, REGVALUE_DISKSPACE_LOW_WATER, NULL, IDSTABLE_DISKSPACE_LOW_TEXTID, IDSTABLE_DISKSPACE_LOW_EVENTNAME_ID, 0, 
    TOKEN_DISKQUOTA_LOW_WATER, 1, 1,1,30, 0, 0, 0, EVENT_GROUP_DISK_WARNING      , GENERAL_ATTENTION_DISKQUOTA_LOW_WATER   , _SEVERITY_MINOR   , OP_STATUS_OPERATIONAL, ICEPACK_TOKEN_ATTENTION_TABLE, NULL, REGVALUE_DISKQUOTA_LOW_WATER, NULL, IDSTABLE_DISKQUOTA_LOW_TEXTID, IDSTABLE_DISKQUOTA_LOW_EVENTNAME_ID, 0, 
    TOKEN_QUARANTINE_FULL,	   1, 1,1,30, 0, 0, 0, EVENT_GROUP_DISK_WARNING      , GENERAL_ATTENTION_CENTRAL_QUARANTINE_FULL  , _SEVERITY_MAJOR   , OP_STATUS_DEGRADED, ICEPACK_TOKEN_ATTENTION_TABLE, NULL, REGVALUE_DISKQUOTA_CQ_FULL, NULL, IDSTABLE_DISKQUOTA_LOW_TEXTID, IDSTABLE_DISKQUOTA_QUARANTINE_FULL, 0, 

    // NEW DEFINITIONS ARRIVED       
    TOKEN_NEWUNBLESSEDDEF, 1, 1, 0,    0, 0, 0, 0, EVENT_GROUP_NEW_DEF_ARRIVAL   , DEF_ALERT_NEW_UNBLESSED_DEFS_EVENTID, _SEVERITY_INFORMATIONAL, OP_STATUS_OPERATIONAL, 0, NULL, REGVALUE_GENERAL_ERROR_NEWUNBLESSEDDEF , NULL, IDSTABLE_NEW_UNBLESSED_DEFS_TEXTID, DEF_ALERT_NEW_UNBLESSED_DEFS_EVENTNAME_ID, 0, 
    TOKEN_NEWBLESSEDDEF  , 1, 1, 0,    0, 0, 0, 0, EVENT_GROUP_NEW_DEF_ARRIVAL   , DEF_ALERT_NEW_BLESSED_DEFS_EVENTID  , _SEVERITY_INFORMATIONAL, OP_STATUS_OPERATIONAL, 0, NULL, REGVALUE_GENERAL_ERROR_NEWBLESSEDDEF   , NULL, IDSTABLE_NEW_BLESSED_DEFS_TEXTID  , DEF_ALERT_NEW_BLESSED_DEFS_EVENTNAME_ID  , 0, 

    // ATTENTION TABLE  
    TOKEN_UNAVAILABLE    , 1, 1, 1,  180, 0, 0, 0, EVENT_GROUP_GENERAL_ERROR     , GENERAL_ATTENTION_UNAVAIABLE_EVENTID,_SEVERITY_INFORMATIONAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ATTENTION_TABLE, NULL, REGVALUE_GENERAL_ERROR_UNAVAIABLE   , NULL, IDSTABLE_HELPTEXT_ATTN_UNAVAILABLE , GENERAL_ATTENTION_UNAVAILABLE_EVENTNAME_ID , 0,       
    TOKEN_SHUTDOWN       , 1, 1, 1,   15, 0, 0, 0, EVENT_GROUP_GENERAL_ERROR     , GENERAL_ATTENTION_SHUTDOWN_EVENTID      , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ATTENTION_TABLE, NULL, REGVALUE_GENERAL_ERROR_SHUTDOWN     , NULL, IDSTABLE_HELPTEXT_ATTN_SHUTDOWN    , GENERAL_ATTENTION_SHUTDOWN_EVENTNAME_ID    , 0,       
    TOKEN_SCANEXPLICIT   , 1, 1, 0,    0, 0, 0, 0, EVENT_GROUP_GENERAL_ERROR     , GENERAL_ATTENTION_SCANEXPLICIT_EVENTID  , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ATTENTION_TABLE, NULL, REGVALUE_GENERAL_ERROR_SCANEXPLICIT , NULL, IDSTABLE_HELPTEXT_ATTN_SCANEXPLICIT, GENERAL_ATTENTION_SCANEXPLICIT_EVENTNAME_ID, 0,       
    TOKEN_DISK           , 1, 1, 0,    0, 0, 0, 0, EVENT_GROUP_GENERAL_ERROR     , GENERAL_ATTENTION_DISK_EVENTID          , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ATTENTION_TABLE, NULL, REGVALUE_GENERAL_ERROR_DISK         , NULL, IDSTABLE_HELPTEXT_ATTN_DISK        , GENERAL_ATTENTION_DISK_EVENTNAME_ID        , 0, 
    TOKEN_TARGET         , 1, 1, 0,    0, 0, 0, 0, EVENT_GROUP_GENERAL_ERROR     , GENERAL_ATTENTION_TARGET_EVENTID        , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ATTENTION_TABLE, NULL, REGVALUE_GENERAL_ERROR_TARGET       , NULL, IDSTABLE_HELPTEXT_ATTN_TARGET      , GENERAL_ATTENTION_TARGET_EVENTNAME_ID      , 0, 
    TOKEN_DEFCAST        , 1, 1, 0,    0, 0, 0, 0, EVENT_GROUP_GENERAL_ERROR     , GENERAL_ATTENTION_DEFCAST_EVENTID       , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ATTENTION_TABLE, NULL, REGVALUE_GENERAL_ERROR_DEFCAST      , NULL, IDSTABLE_HELPTEXT_ATTN_DEFCAST     , GENERAL_ATTENTION_DEFCAST_EVENTNAME_ID     , 0, 
    TOKEN_GATEWAYCOMM    , 1, 1, 1,   60, 0, 0, 0, EVENT_GROUP_GATEWAY_COMM_ERROR, GENERAL_ATTENTION_GATEWAY_COMM_EVENTID  , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ATTENTION_TABLE, NULL, REGVALUE_GENERAL_ERROR_GATEWAY_COMM , NULL, IDSTABLE_HELPTEXT_ATTN_GATEWAY     , GENERAL_ATTENTION_GATEWAY_COMM_EVENTNAME_ID, 0, 

    // SEND TEST EVENT
    TOKEN_SEND_TEST_EVENT, 0, 1, 0,    0, 0, 0, 0, EVENT_GROUP_GENERAL_INFORMATIONAL, GENERAL_ATTENTION_SEND_TEST_EVENT    , _SEVERITY_MAJOR   , OP_STATUS_OPERATIONAL    , ICEPACK_TOKEN_ATTENTION_TABLE, NULL, REGVALUE_SEND_TEST_EVENT, NULL, SEND_TEST_EVENT_TEXT_ID, SEND_TEST_EVENT_NAME_ID, 0, 


    // DEFAULT
    NULL, 0, 0, 1, 0, 0, 0, 0, EVENT_GROUP_GENERAL_ERROR, 0, _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ATTENTION_TABLE, L"Default settings", _T(""), NULL, 0, 0, 0, 
    NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 0, 0
};
#endif


#ifndef g_AvisEventRulesSampleIntervention
// GLOBAL  SAMPLE INTERVENTION TABLE
AVIS_EVENT_RULES g_AvisEventRulesSampleIntervention[] =
{
    // STATUS TIME IN STATE                                                                            
    TOKEN_AVAILABLE   , 1, 1, 1,      60, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_AVAILABLE_EVENTID       , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_STATUS_TABLE, NULL, REGVALUE_SAMPLE_ERROR_AVAILABLE    , NULL, IDSTABLE_HELPTEXT_SAMPLE_AVAILABLE     , SAMPLE_ALERT_AVAILABLE_EVENTNAME_ID          , 0, 
    TOKEN_QUARANTINED , 1, 1, 1,   24*60, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_QUARANTINED_EVENTID     , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_STATUS_TABLE, NULL, REGVALUE_SAMPLE_ERROR_QUARANTINED  , NULL, IDSTABLE_HELPTEXT_SAMPLE_QUARANTINED   , SAMPLE_ALERT_QUARANTINED_EVENTNAME_ID        , 0, 
    TOKEN_SUBMITTED   , 1, 1, 1,   24*60, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_SUBMITTED_EVENTID       , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_STATUS_TABLE, NULL, REGVALUE_SAMPLE_ERROR_SUBMITTED    , NULL, IDSTABLE_HELPTEXT_SAMPLE_SUBMITTED     , SAMPLE_ALERT_SUBMITTED_EVENTNAME_ID          , 0, 
    TOKEN_RELEASED    , 1, 1, 1,   24*60, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_RELEASED_EVENTID        , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_STATUS_TABLE, NULL, REGVALUE_SAMPLE_ERROR_RELEASED     , NULL, IDSTABLE_HELPTEXT_SAMPLE_RELEASED      , SAMPLE_ALERT_RELEASED_EVENTNAME_ID           , 0, 
    TOKEN_NEEDED      , 1, 1, 1,      60, 0, 0, 0, EVENT_GROUP_DEFINITION_ERROR, DEF_ALERT_INSTATE_NEEDED_EVENTID     , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_STATUS_TABLE, NULL, REGVALUE_SAMPLE_ERROR_NEEDED       , NULL, IDSTABLE_HELPTEXT_DEF_NEEDED           , DEF_ALERT_INSTATE_NEEDED_EVENTNAME_ID        , 0, 
    TOKEN_DISTRIBUTED , 1, 1, 1,      60, 0, 0, 0, EVENT_GROUP_DEFINITION_ERROR, DEF_ALERT_INSTATE_DISTRIBUTED_EVENTID, _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_STATUS_TABLE, NULL, REGVALUE_SAMPLE_ERROR_DISTRIBUTED  , NULL, IDSTABLE_HELPTEXT_SAMPLE_DISTRIBUTED   , DEF_ALERT_INSTATE_DISTRIBUTED_EVENTNAME_ID   , 0, 
    TOKEN_DISTRIBUTE  , 1, 1, 1, 3*24*60, 0, 0, 0, EVENT_GROUP_DEFINITION_ERROR, DEF_ALERT_INSTATE_DISTRIBUTE_EVENTID , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, 0                         , NULL ,REGVALUE_SAMPLE_ERROR_DISTRIBUTE   , NULL, IDSTABLE_TEXT_UNABLE_TO_DISTRIBUTE_DEFS, DEF_ALERT_INSTATE_DISTRIBUTE_EVENTNAME_ID    , 0, 
    
    // STATUS STATUS ERRORS
    TOKEN_HELD        , 1, 1, 0,       0, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_HELD_EVENTID            , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_STATUS_TABLE, NULL, REGVALUE_SAMPLE_ERROR_HELD         , NULL, IDSTABLE_HELPTEXT_SAMPLE_HELD          , SAMPLE_ALERT_HELD_EVENTNAME_ID               , 0, 
    TOKEN_ATTENTION   , 1, 1, 0,       0, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_ATTENTION_EVENTID       , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_STATUS_TABLE, NULL, REGVALUE_SAMPLE_ERROR_ATTENTION    , NULL, 0                                      , SAMPLE_ALERT_ATTENTION_EVENTNAME_ID          , 0, 
    TOKEN_ERROR       , 1, 1, 0,       0, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_ERROR_EVENTID           , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ERROR_TABLE , NULL, REGVALUE_SAMPLE_ERROR_ERROR        , NULL, 0                                      , SAMPLE_ALERT_ERROR_EVENTNAME_ID              , 0, 
    TOKEN_NOTINSTALLED, 1, 1, 0,       0, 0, 0, 0, EVENT_GROUP_DEFINITION_ERROR, DEF_ALERT_NOT_INSTALLED_EVENTID      , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_STATUS_TABLE, NULL, REGVALUE_SAMPLE_ERROR_NOTINSTALLED , NULL, IDSTABLE_HELPTEXT_SAMPLE_NOTINSTALLED2 , DEF_ALERT_NOT_INSTALLED_EVENTNAME_ID         , IDSTABLE_HELPTEXT_DEF_FTP_ADDRESS, 
                                                                                                       
    // LOCAL QUARANTINE ALERT
    TOKEN_NOTREPAIRED , 1, 1, 0, 0, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , QUARANTINE_ALERT_NOT_REPAIRED_EVENTID , _SEVERITY_INFORMATIONAL, OP_STATUS_OPERATIONAL    ,ICEPACK_TOKEN_RESULT_TABLE, NULL, REGVALUE_SAMPLE_ERROR_NOTREPAIRED   , NULL, IDSTABLE_HELPTEXT_SAMPLE_NOTREPAIRED, SAMPLE_ALERT_QUARANTINE_NOT_REPAIRED_ID, 0, 

    // ICEPACK ERROR TABLE                                                                                             
    TOKEN_ABANDONED   , 0, 1, 0, 0, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_ABANDONED_EVENTID        , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ERROR_TABLE, NULL, REGVALUE_SAMPLE_ERROR_ABANDONED   , NULL, 0, SAMPLE_ALERT_ERROR_EVENTNAME_ID, 0,  // jhill 2/12/00
    TOKEN_CONTENT     , 0, 1, 0, 0, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_CONTENT_EVENTID          , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ERROR_TABLE, NULL, REGVALUE_SAMPLE_ERROR_CONTENT     , NULL, 0, SAMPLE_ALERT_ERROR_EVENTNAME_ID, 0, 
    TOKEN_CRUMBLED    , 0, 1, 0, 0, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_CRUMBLED_EVENTID         , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ERROR_TABLE, NULL, REGVALUE_SAMPLE_ERROR_CRUMBLED    , NULL, 0, SAMPLE_ALERT_ERROR_EVENTNAME_ID, 0, 
    TOKEN_DECLINED    , 0, 1, 0, 0, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_DECLINED_EVENTID         , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ERROR_TABLE, NULL, REGVALUE_SAMPLE_ERROR_DECLINED    , NULL, 0, SAMPLE_ALERT_ERROR_EVENTNAME_ID, 0, 
    TOKEN_INTERNAL    , 0, 1, 0, 0, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_INTERNAL_EVENTID         , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ERROR_TABLE, NULL, REGVALUE_SAMPLE_ERROR_INTERNAL    , NULL, 0, SAMPLE_ALERT_ERROR_EVENTNAME_ID, 0, 
    TOKEN_LOST        , 0, 1, 0, 0, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_LOST_EVENTID             , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ERROR_TABLE, NULL, REGVALUE_SAMPLE_ERROR_LOST        , NULL, 0, SAMPLE_ALERT_ERROR_EVENTNAME_ID, 0, 
    TOKEN_MALFORMED   , 0, 1, 0, 0, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_MALFORMED_EVENTID        , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ERROR_TABLE, NULL, REGVALUE_SAMPLE_ERROR_MALFORMED   , NULL, 0, SAMPLE_ALERT_ERROR_EVENTNAME_ID, 0, 
    TOKEN_MISSING     , 0, 1, 0, 0, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_MISSING_EVENTID          , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ERROR_TABLE, NULL, REGVALUE_SAMPLE_ERROR_MISSING     , NULL, 0, SAMPLE_ALERT_ERROR_EVENTNAME_ID, 0, 
    TOKEN_OVERRUN     , 0, 1, 0, 0, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_OVERRUN_EVENTID          , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ERROR_TABLE, NULL, REGVALUE_SAMPLE_ERROR_OVERRUN     , NULL, 0, SAMPLE_ALERT_ERROR_EVENTNAME_ID, 0, 
    TOKEN_SAMPLE      , 0, 1, 0, 0, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_SAMPLE_EVENTID           , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ERROR_TABLE, NULL, REGVALUE_SAMPLE_ERROR_SAMPLE      , NULL, 0, SAMPLE_ALERT_ERROR_EVENTNAME_ID, 0, 
    TOKEN_SUPERCEDED  , 0, 1, 0, 0, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_SUPERCEDED_EVENTID       , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ERROR_TABLE, NULL, REGVALUE_SAMPLE_ERROR_SUPERCEDED  , NULL, 0, SAMPLE_ALERT_ERROR_EVENTNAME_ID, 0, 
    TOKEN_TYPE        , 0, 1, 0, 0, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_TYPE_EVENTID             , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ERROR_TABLE, NULL, REGVALUE_SAMPLE_ERROR_TYPE        , NULL, 0, SAMPLE_ALERT_ERROR_EVENTNAME_ID, 0, 
    TOKEN_UNAVAILABLE , 0, 1, 0, 0, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_UNAVAILABLE_EVENTID      , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ERROR_TABLE, NULL, REGVALUE_SAMPLE_ERROR_UNAVAILABLE , NULL, 0, SAMPLE_ALERT_ERROR_EVENTNAME_ID, 0, 
    TOKEN_UNDERRUN    , 0, 1, 0, 0, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_UNDERRUN_EVENTID         , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ERROR_TABLE, NULL, REGVALUE_SAMPLE_ERROR_UNDERRUN    , NULL, 0, SAMPLE_ALERT_ERROR_EVENTNAME_ID, 0, 
    TOKEN_UNPACKAGE   , 0, 1, 0, 0, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_UNPACKAGE_EVENTID        , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ERROR_TABLE, NULL, REGVALUE_SAMPLE_ERROR_UNPACKAGE   , NULL, 0, SAMPLE_ALERT_ERROR_EVENTNAME_ID, 0, 
    TOKEN_UNPUBLISHED , 0, 1, 0, 0, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR    , SAMPLE_ALERT_UNPUBLISHED_EVENTID      , _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, ICEPACK_TOKEN_ERROR_TABLE, NULL, REGVALUE_SAMPLE_ERROR_UNPUBLISHED , NULL, 0, SAMPLE_ALERT_ERROR_EVENTNAME_ID, 0, 

   
    // DEFAULT          
    NULL, 0, 1, 0, 0, 0, 0, 0, EVENT_GROUP_SAMPLE_ERROR, 0, _SEVERITY_CRITICAL, OP_STATUS_NON_OPERATIONAL, EVENT_TOKEN_SAMPLE_INTERVENTION_TABLE, L"Default settings", _T(""), NULL, 0, 0, 0, 
    NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0, 0, 0   
};

#endif










#endif