/////////////////////////////////////////////////////////////////////
// DLLMAIN.H - Created - 11/14/96
//
// Copyright 1992-1996 Symantec, Peter Norton Product Group
/////////////////////////////////////////////////////////////////////
// $Header:   S:/NETBREXT/VCS/dllmain.h_v   1.0   21 Nov 1997 11:52:02   KSACKIN  $
//
// Description:
//    This header file will contain definitions and externs
//    reguarding this instance of this dll.  It will include such
//    things as out extension struct
//
/////////////////////////////////////////////////////////////////////
//
// $Log:   S:/NETBREXT/VCS/dllmain.h_v  $
// 
//    Rev 1.0   21 Nov 1997 11:52:02   KSACKIN
// Initial revision.
// 
//    Rev 1.0   18 Apr 1997 14:03:08   DSACKIN
// Ported from Tesla
// 
//    Rev 1.0   13 Mar 1997 15:16:32   RFULLER
// Initial revision
// 
//    Rev 1.0   20 Nov 1996 02:28:06   ksackin
// Initial revision.
//
/////////////////////////////////////////////////////////////////////

#if !defined(__DLLMAIN_H)
#define __DLLMAIN_H

/////////////////////////////////////////////////////////////////////
// Includes

#include "afxwin.h"

/////////////////////////////////////////////////////////////////////
// Externals

extern AFX_EXTENSION_MODULE extMyExtension;




#endif // if !defined(__DLLMAIN_H)
