[Components]
component0=System Files
component1=Program Files
component2=Shared Files
component3=AMS Install Files

[TopComponents]
component0=Program Files
component1=Shared Files
component2=System Files
component3=AMS Install Files

[System Files]
SELECTED=Yes
FILENEED=CRITICAL
HTTPLOCATION=
STATUS=Copying system files...
UNINSTALLABLE=Yes
TARGET=<WINSYS_NS>
FTPLOCATION=
VISIBLE=Yes
DESCRIPTION=
DISPLAYTEXT=
IMAGE=
DEFSELECTION=Yes
filegroup0=System DLL Files
COMMENT=
INCLUDEINBUILD=Yes
INSTALLATION=NEWERVERSION\NEWERDATE
COMPRESSIFSEPARATE=No
MISC=
ENCRYPT=No
DISK=ANYDISK
TARGETDIRCDROM=
PASSWORD=
TARGETHIDDEN=Script-defined Folders\<WINSYS_NS>

[SetupType]
setuptype0=Network

[Shared Files]
SELECTED=Yes
FILENEED=STANDARD
HTTPLOCATION=
STATUS=Copying shared files...
UNINSTALLABLE=Yes
TARGET=<COMMONFILES>\Symantec Shared\SSC
FTPLOCATION=
VISIBLE=Yes
DESCRIPTION=
DISPLAYTEXT=
IMAGE=
DEFSELECTION=Yes
filegroup0=Transport Manager Files
COMMENT=
INCLUDEINBUILD=Yes
INSTALLATION=NEWERVERSION\NEWERDATE
COMPRESSIFSEPARATE=No
MISC=
ENCRYPT=No
DISK=ANYDISK
TARGETDIRCDROM=
PASSWORD=
TARGETHIDDEN=Program Files Folder\Common Files Folder\Symantec Shared\SSC

[Program Files]
SELECTED=Yes
FILENEED=STANDARD
HTTPLOCATION=
STATUS=Copying program files...
UNINSTALLABLE=Yes
TARGET=<TARGETDIR>
FTPLOCATION=
VISIBLE=Yes
DESCRIPTION=
DISPLAYTEXT=
IMAGE=
DEFSELECTION=Yes
filegroup0=COM objects
COMMENT=
INCLUDEINBUILD=Yes
filegroup1=IcePack Files
INSTALLATION=ALWAYSOVERWRITE
filegroup2=Program DLLs
COMPRESSIFSEPARATE=No
MISC=
ENCRYPT=No
DISK=ANYDISK
TARGETDIRCDROM=
PASSWORD=
TARGETHIDDEN=General Application Destination

[AMS Install Files]
SELECTED=Yes
FILENEED=STANDARD
HTTPLOCATION=
STATUS=Copying AMS files...
UNINSTALLABLE=Yes
TARGET=<TARGETDIR>\Ams2\Winnt
FTPLOCATION=
VISIBLE=Yes
DESCRIPTION=
DISPLAYTEXT=
IMAGE=
DEFSELECTION=Yes
filegroup0=AMS Install Files
COMMENT=
INCLUDEINBUILD=Yes
INSTALLATION=ALWAYSOVERWRITE
COMPRESSIFSEPARATE=No
MISC=
ENCRYPT=No
DISK=ANYDISK
TARGETDIRCDROM=
PASSWORD=
TARGETHIDDEN=General Application Destination\Ams2\Winnt

[Info]
Type=CompDef
Version=1.00.000
Name=

[SetupTypeItem-Network]
Comment=
Descrip=
DisplayText=

