//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by navabout.rc
//
#define IDS_COMPONENT_NAME              1
#define IDS_PRODUCT_WIN95               2
#define IDS_PRODUCT_NTS                 3
#define IDS_PRODUCT_NTWS                4
#define IDS_PRODUCT_TITLE               5
#define IDS_VIRUS_DEF_NOTICE_FORMAT_STR 6
#define IDS_WINDOWS_VERSION_WIN32S      7
#define IDS_WINDOWS_VERSION_WIN95       8
#define IDS_WINDOWS_VERSION_NT          9
#define IDS_BUILD_STR                   10
#define IDS_PART_NUMBER                 11
#define IDS_SCANNER_TITLE               12
#define IDS_WINDOWS_VERSION_WIN98       13
#define IDS_PRODUCT_TITLE_OEM           14
#define IDB_ABOUT                       103
#define IDI_NAVW                        104
#define IDD_ABOUT_EXT                   107
#define IDC_LBL_PRODUCT                 108
#define IDC_LBL_COPYRIGHT               109
#define IDD_NAVEGG                      110
#define IDB_NAVTEAM                     111
#define IDC_VIRUSNUM                    1000
#define IDC_DEFDATE                     1001

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

