//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LDVPTaskFSRes.rc
//
#define IDS_LDVPTASKFS                  1
#define IDB_LDVPTASKFS                  1
#define IDS_LDVPTASKFS_PPG              2
#define IDS_CLOSE                       3
#define IDS_VIRUSNAME                   4
#define IDS_FILENAME                    5
#define IDS_SCHEDULE_OPTIONS            7
#define IDS_SCAN_PROMPT_DAILY           8
#define IDS_SCAN_PROMPT_WEEKLY          9
#define IDS_SCAN_PROMPT_MONTHLY         10
#define IDC_EXTENSIONS                  10
#define IDS_CONFIG_SCAN                 11
#define IDS_EXTENSION_EXECUTABLES       12
#define IDS_NOT_READY                   12
#define IDS_CONFIG_RTS                  13
#define IDS_IDLE_SCAN                   14
#define IDS_CONFIG_SCAN_DESCRIPTION     15
#define IDS_CONFIG_ACTIONS_DESCRIPTION  16
#define IDS_CONFIG_RTS_DESCRIPTION      17
#define IDS_CONFIG_IDLE_DESCRIPTION     18
#define IDS_GROUP_CONFIGURATION         19
#define IDS_EXTENSION_DOCUMENTS         20
#define IDS_QUICKSCAN                   20
#define IDS_EXTENSION_BAD_EXTENSION     21
#define IDS_CONFIGURATION               22
#define IDS_SAVE_OPTIONS                23
#define IDS_DEFAULT_MESSAGE             23
#define IDS_SAVE                        24
#define IDS_SCAN                        25
#define IDS_EXTENSIONS_DESCRIPT         26
#define IDS_QUICKSCAN_DESCRIPTION       27
#define IDS_COULD_NOT_CLEAN             28
#define IDS_MERIDIAN_POST               29
#define IDS_GROUP_MONITORING            30
#define IDS_ACCESSED                    30
#define IDS_VIEW_LOG                    31
#define IDS_MODIFIED                    31
#define IDS_VIEW_LOG_DESCRIPTION        32
#define IDS_BOTH                        32
#define IDS_FILE_READ_ERROR             33
#define IDS_LOG_FILTER                  34
#define IDS_LOCKED_OPTION               35
#define IDS_NO_WHATS_THIS_HELP          36
#define IDS_DIR_NOT_EXISTS              37
#define IDS_FULL_SCAN                   37
#define IDS_DIR_NOT_CREATE              38
#define IDS_FULL_SCAN_DESCRIPTION       38
#define IDS_INCORRECT_PASSWORD          39
#define IDS_SELECT_SCAN_TYPE            39
#define IDS_NEXT                        40
#define IDS_SCAN_PROMPT_DAILY_RESUME    41
#define IDS_SCAN_PROMPT_WEEKLY_RESUME   42
#define IDS_SCAN_PROMPT_MONTHLY_RESUME  43
#define IDS_QUICKSCAN_DESCRIPTION_SHORT 44
#define IDS_QUCIKSCAN_DESCRIPTION_SHORT 44
#define IDS_FULLSCAN_DESCRIPTION_SHORT  45
#define IDS_NO_SCHEDULE                 50
#define IDS_START                       51
#define IDS_STOP                        52
#define IDS_AC_NOTHING                  53
#define IDS_AC_BAD                      54
#define IDS_GL_EVENT_IS_ALERT           55
#define IDS_GL_EVENT_SCAN_STOP          56
#define IDS_GL_EVENT_SCAN_START         57
#define IDS_GL_EVENT_PATTERN_UPDATE     58
#define IDS_GL_EVENT_INFECTION          59
#define IDS_GL_EVENT_FILE_NOT_OPEN      60
#define IDS_GL_EVENT_LOAD_PATTERN       61
#define IDS_GL_STD_MESSAGE_INFO         62
#define IDS_GL_STD_MESSAGE_ERROR        63
#define IDS_GL_EVENT_CHECKSUM           64
#define IDS_GL_EVENT_TRAP               65
#define IDS_GL_EVENT_CONFIG_CHANGE      66
#define IDS_LOGGER_Scheduled            67
#define IDS_LOGGER_Manual               68
#define IDS_LOGGER_Real_Time            69
#define IDS_LOGGER_Integrity_Shield     70
#define IDS_LOGGER_Console              71
#define IDS_LOGGER_VPDOWN               72
#define IDS_LOGGER_SYSTEM               73
#define IDS_LOGGER_Forwarded            74
#define IDS_GL_CAT_INFECTION            75
#define IDS_GL_CAT_SUMMARY              76
#define IDS_GL_CAT_PATTERN              77
#define IDS_GL_CAT_SECURITY             78
#define IDS_GL_EVENT_STARTUP            79
#define IDS_GL_EVENT_PATTERN_DOWNLOAD   80
#define IDS_GL_EVENT_SHUTDOWN           81
#define IDS_GL_EVENT_TOO_MANY_VIRUSES   82
#define IDS_ACTION_MOVE                 83
#define IDS_ACTION_RENAME               84
#define IDS_ACTION_DELETE               85
#define IDS_ACTION_CLEAN                86
#define IDS_ACTION_LEAVEALONE           87
#define IDS_VIRUSES_FOUND               88
#define IDS_NOON                        89
#define IDS_LOGGER_IDLE                 90
#define IDS_MACRO                       91
#define IDS_NON_MACRO                   92
#define IDS_OPTION_MOVE                 93
#define IDS_TASK_SCHEDULED_DEFAULT_NAME 93
#define IDS_OPTION_RENAME               94
#define IDS_TASK_SCHEDULED_DESCRIPTION  94
#define IDS_OPTION_DELETE               95
#define IDS_TASK_STARTUP_DEFAULT_NAME   95
#define IDS_OPTION_LEAVEALONE           96
#define IDS_TASK_STARTUP_DESCRIPTION    96
#define IDS_OPTION_CLEAN                97
#define IDS_TASK_NAME_DEFAULT           98
#define IDS_LDVPTASKFS_PPG_CAPTION      100
#define IDD_PROPPAGE_LDVPTASKFS         100
#define IDC_EXTENSION                   100
#define IDS_GROUP_HEADER                101
#define IDC_EXTENSION_ADD               101
#define IDD_QUICK_SCAN                  101
#define IDS_SCAN_FLOPPY                 102
#define IDC_EXTENSIONS_LIST             102
#define IDC_EXTENSION_LIST              102
#define IDS_SCAN_FLOPPY_DESCRIPTION     103
#define IDC_EXTENSION_REMOVE            103
#define IDS_SCAN_DRIVE_DESCRIPTION      104
#define IDC_EXTENSION_EXECUTABLE        104
#define IDS_SCAN_DRIVE                  105
#define IDC_EXTENSION_DOCUMENTS         105
#define IDS_SCAN_SELECTED               106
#define IDD_SCAN_FLOPPY                 106
#define IDS_SCAN_SELECTED_DESCRIPTION   107
#define IDD_SCAN_RESULTS                107
#define IDD_SCAN_FIXED                  108
#define IDS_EDIT                        108
#define IDD_SCAN_SELECTED               109
#define IDS_NO_SCAN_DIALOGS             109
#define IDD_CUSTOM_SCAN                 110
#define IDD_MONTHLY                     111
#define IDS_EXCLUSION_COL_HEADING       112
#define IDS_EXCLUSION_COL_CLEANABLE     113
#define IDS_EXCLUSION_COL_TYPE          114
#define IDS_SCHEDULE_TEXT               115
#define IDS_START_SCAN_ERROR            116
#define IDS_NO_I_SCAN                   117
#define IDS_ERR_CREATE_SHELLSEL         147
#define IDS_ERROR_READ_DIRECTORY        182
#define IDS_APP_NAME                    183
#define IDS_ERROR_SHELLSEL_NONE_SELECTED 199
#define IDS_SCAN_PCHEALTH               200
#define IDC_DESCRIPTION                 201
#define IDS_SCAN_PCHEALTH_DESCRIPTION   201
#define IDC_PLACE_HOLDER                202
#define IDS_TASK_NAME_WIZARDMODE        202
#define IDC_DAY_OF_WEEK                 203
#define IDD_DIRECTORY_TREE              203
#define IDS_TASK_NAME_NONWIZARDMODE     203
#define IDC_DAY_OF_MONTH                204
#define IDC_SCAN_PROGRESS               206
#define IDC_SCANNING_MEMORY             207
#define IDC_SCANNING_BOOT_SECTOR        208
#define IDD_PREPARING_DLG               208
#define IDC_SCANNING_DISK               209
#define IDD_DAILY                       209
#define IDD_WEEKLY                      211
#define IDD_SCHEDULE_OPTIONS            212
#define IDD_RTS_OPTIONS                 213
#define IDD_SCAN_OPTIONS                214
#define IDD_IDLE_OPTIONS                215
#define IDD_EXTENSIONS                  216
#define IDD_MESSAGE                     217
#define IDD_EXCLUDE_PATTERNS            218
#define IDD_VIEW_LOG                    219
#define IDC_DRIVES                      220
#define IDC_SPEC                        221
#define IDB_LOCKS                       221
#define IDD_PASSWORD                    221
#define IDC_CLEAN                       222
#define IDD_SAVEAS                      222
#define IDC_DELETE                      223
#define IDI_WAIT                        224
#define IDC_VIRUSES_FOUND               225
#define IDI_EXTENSIONS                  225
#define IDC_STOP_SCAN                   226
#define IDB_SCANSELECTEDISK             226
#define IDB_SCANFLOP                    227
#define IDC_DAILY                       228
#define IDC_WEEKLY                      229
#define IDC_DEFAULTS                    229
#define IDC_MONTHLY                     230
#define IDI_SCHEDULE                    230
#define IDC_SPIN_DAYS                   231
#define IDI_CUSTOMSCAN                  231
#define IDC_PH_CTRL                     237
#define IDD_SCAN_PCHEALTH               240
#define IDB_PCHEALTH                    245
#define IDB_SCANPCHEALTH                247
#define IDD_SCHEDULE_PAGE               253
#define IDD_FULL_SCAN                   255
#define IDD_SELECT_SCAN_TYPE            256
#define IDC_QSCAN_IMAGE_FRAME           257
#define IDC_TYPES_ALL                   258
#define IDC_FSCAN_IMAGE_FRAME           258
#define IDC_TYPES_SELECTED              259
#define IDC_ACTIONS_FOR                 260
#define IDC_CSCAN_IMAGE_FRAME           260
#define IDC_FILE_TYPES                  261
#define IDC_COMPRESSED                  262
#define IDC_ACTION                      263
#define IDC_IF_ACTION_FAILS             265
#define IDC_ALL_DRIVES                  266
#define IDB_SCAN_IMAGES                 266
#define IDC_SELECTED_DRIVES             267
#define IDC_BROWSE_SELECTED_DRIVES      268
#define IDC_EXCLUDE_FILES               269
#define IDC_CHECK3                      270
#define IDC_BROWSE_EXCLUDE_FILES        271
#define IDC_CHECKSUM                    273
#define IDC_DISPLAY_ON_CONSOLE          274
#define IDC_CONFIGURE                   275
#define IDC_MESSAGE                     276
#define IDC_MOVE_FOLDER                 277
#define IDC_BROWSE_MOVE_FOLDER          278
#define IDC_SCAN_FLOPPY                 279
#define IDC_SCAN_CDROM                  280
#define IDC_SCAN_WHEN_MODIFIED          281
#define IDC_SCAN_WHEN_ACCESSED          282
#define IDC_ENABLE_RTS                  283
#define IDC_BROWSE_FILE_TYPES           285
#define IDC_BROWSE_EXCLUDE_SIGS         286
#define IDC_SELECTED_SIGS               287
#define IDC_ZIP_FILES                   288
#define IDC_ZIP_EXE                     289
#define IDC_EXCLUDE_SIGS                290
#define IDC_STATIC_PATH                 290
#define IDC_MESSAGE_BOX                 291
#define IDC_OPTIONS                     292
#define IDC_PATTENRNS                   296
#define IDC_LOG                         298
#define IDC_OPEN                        299
#define IDC_FILENAMES                   300
#define IDC_MONTHLY_TEXT                301
#define IDC_MONTHLY_AT                  302
#define IDC_WEEKLY_TEXT                 303
#define IDC_WEEKLY_AT                   304
#define IDC_DAILY_TEXT                  305
#define IDC_ONOFF                       306
#define IDC_PASSWORD                    310
#define IDC_IDLE_MINUTES                311
#define IDC_MINUTE_SPIN                 312
#define IDC_TITLE                       313
#define IDC_FILES                       314
#define IDC_SCHEDULE_INFO               315
#define IDC_SCHEDULE                    316
#define IDC_PASSWORD_TEXT               318
#define IDC_DENY_ACCESS                 319
#define IDC_MESSAGE_BEEP                320
#define IDC_FOLDERS                     321
#define IDC_COMPRESSED_STATIC           323
#define IDC_WHEN_TO_SCAN                324
#define IDC_LDVPACTIONSCTRL1            325
#define IDC_ACTIONS                     328
#define IDC_RESULTS_PH                  334
#define IDC_REMEMBER_SETTINGS           339
#define IDC_UI                          345
#define IDC_MAKE_DEFAULT                349
#define IDC_NAME_STATIC                 355
#define IDC_QSCAN_RADIO                 356
#define IDC_FSCAN_RADIO                 357
#define IDC_CSCAN_RADIO                 358
#define IDC_CSCAN_STATIC                359
#define IDC_FSCAN_STATIC                360
#define IDC_QSCAN_STATIC                361
#define IDC_SCHEDULE_CONTROL            362
#define IDC_NAME                        1007
#define IDC_TASK_DESCRIPTION            1008
#define IDC_CHILDREN                    1015
#define IDC_PATH                        1029

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
