//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SavCustom.rc
//
#define IDS_DEFAULT_TITLE               4
#define IDS_NO_SELECTION                6
#define IDS_AMS_NAME                    7
#define IDS_CLIENT_MESSAGE              8
#define IDS_CONSOLE_MESSAGE             9
#define IDS_SERVER_MESSAGE              10
#define IDS_AMS2_MESSAGE                11
#define IDS_UNINSTALL_COMPLETE          12
#define IDS_COPYFILES                   13
#define IDS_DELETEFILES                 14
#define IDS_SETUPERROR                  15
#define IDS_SETUPCANCELED               16
#define IDS_REBOOT_MESSAGE              17
#define IDS_TDK_MESSAGE                 18
#define IDS_APPS_MESSAGE                19
#define IDS_ERROR_SERVER_NOT_FOUND_ABORT 20
#define IDS_ERROR_STOP_TRANSMAN         20
#define IDS_ERROR_FREE_TRANSMAN         21
#define IDS_BLANK_USERNAME              22
#define IDS_ERROR_FAILEDCREDENTIALS     23
#define IDS_ERROR_UNMANAGED_SECONDARY   24
#define IDS_ERROR_UNMANAGED_SECONDARY_TITLE 25
#define IDS_ERROR_NO_SERVER_NAME        26
#define IDS_ERROR_NO_SERVER_NAME_TITLE  27
#define IDS_ERROR_SERVER_NAME_TOO_LONG  28
#define IDS_ERROR_UNMANAGED_SECONDARY_SERVER 29
#define IDS_ERROR_UNMANAGED_SECONDARY_SERVER_TITLE 30
#define IDS_ERROR_SMALLPASS             31
#define IDS_ERR_PATHTOOLONG             32
#define IDS_ERROR_TIMEOUTOFSYNC         33
#define IDS_ERROR_USERNAME_TOO_LONG     34
#define IDS_ERROR_PASSWORD_TOO_LONG     35
#define IDS_ERR_MAN_NO_PARENT           36
#define IDS_ERR_MAN_NO_PARENT_CONTACT   37
#define IDS_ERR_MAN_PARENT_SECURE       38
#define IDS_ERROR_PRI_SERVERNOTFOUND    39
#define IDS_ERROR_SEC_SRV_MIG           40
#define IDS_ERROR_MIGSRV_PASS_TITLE     41
#define IDS_ERROR_MIGSRV_OLD_PASS_MISMATCH 42
#define IDS_ERROR_MIGSRV_NEW_PASS_MISMATCH 43
#define IDS_INVALID_PASSWD              44
#define IDS_ERROR_MIGSRV_NEW_PASS_LENGTH 45
#define IDS_ERROR_MIG_FAILEDCREDENTIALS 46
#define IDS_ERROR_MIG_TIMEOUTOFSYNC     47
#define IDS_ERROR_GROUPNAME_NOPOUND     48
#define IDS_ERROR_CANTCONTACTPRIMARY    49
#define IDS_NOINF_FILE                  58
#define IDS_UPDATE_SYSTEMFILES          75
#define IDD_VPREMOVE_DIALOG             102
#define IDD_CONTINUE_DIALOG             103
#define IDD_DISPLAY_DIALOG              108
#define IDD_DOMPASSWD_DLG               115
#define IDD_PROGRESS                    121
#define IDR_MAINFRAME                   128
#define IDD_SERVER_LIST                 132
#define IDB_BROWSER                     133
#define IDD_FINDCOMPUTER_DIALOG         134
#define IDB_IS_BITMAP                   135
#define IDI_FIND_ICON                   136
#define IDD_VERIFYPASSWORD              140
#define IDI_PASS                        142
#define IDD_NEW_PASS_DLG                145
#define IDD_SRV_LOGIN_DLG               146
#define IDS_MONITOR_LINK                201
#define IDS_CONSOLEHLP_LINK             203
#define IDS_CLIENT_LINK                 204
#define IDS_CLIENTHLP_LINK              205
#define IDS_SERVER_NORESPONSE           206
#define IDS_ERROR_SERVER_NOT_FOUND      207
#define IDS_INSTALL_APP                 208
#define IDS_UNINSTALL_APP               209
#define IDS_COL_SERVER                  210
#define IDS_COL_VERSION                 211
#define IDS_UNKNOWN_VERSION             212
#define IDS_INVALIDFINDSERVERNAME       213
#define IDS_CANTFINDSERVER              214
#define IDS_SEARCH_IPADDRESS            215
#define IDS_SEARCH_IPXADDRESS           216
#define IDS_SEARCH_SERVEREITHER         217
#define IDS_SEARCH_SERVERNT             218
#define IDS_SEARCH_SERVERNETWARE        219
#define IDS_ERROR_SERVERS_NOT_FOUND     220
#define IDS_PLEASE_WAIT                 222
#define IDS_REBOOT                      224
#define IDS_ERROR_AMSCLIENT             226
#define IDS_CAPTION_AMSCLIENT           227
#define IDS_ERRORCAPTION_AMSCLIENT      228
#define IDS_ERR_AMSCLIENT_INSTALLAMS    229
#define IDS_ERROR_UNABLE_BUILD_DOMAIN_LIST 230
#define IDS_ERROR_UNABLE_CLEANUP_DOMAIN_LIST 231
#define IDS_ERROR_SERVERNOTFOUND        232
#define IDS_ERROR_BLANKGROUP            233
#define IDS_ERROR_OLDVERSION            234
#define IDS_ERROR_BADGROUPNAME          235
#define IDS_GROUP_NEW                   236
#define IDS_ERROR_BLANKPASS             237
#define IDS_ERROR_NOMATCH               238
#define IDS_ERROR_NOMATCHSERVER         239
#define IDS_PATHTITLE                   240
#define IDS_ERR_BLANKPATH               241
#define IDS_ERR_PATHTOOSHORT            242
#define IDS_ERR_NOSEMICOLON             243
#define IDS_ERR_NOAMPERSAND             244
#define IDS_ERR_NOHIASCII               245
#define IDS_ERR_NODBCS                  246
#define IDS_ERR_NOLEADSPACE             247
#define IDS_ERR_NOPATH                  248
#define IDS_ERROR_NONSECURE             249
#define IDS_ERROR_NOPRIMARY             250
#define IDC_SERVER_CLIENT               1000
#define IDC_CONSOLE_ONLY                1001
#define IDC_CONTINUE_TEXT               1002
#define IDC_AMS_ONLY                    1002
#define IDC_BACK                        1007
#define IDC_RET_BACK                    1007
#define IDC_NEXT                        1008
#define IDC_RET_NEXT                    1008
#define IDC_RET_OK                      1008
#define IDC_STATIC_LOGO                 1009
#define IDC_SERVER_LIST                 1010
#define IDC_FINDCOMPUTER_BUTTON         1011
#define IDC_COMPUTER                    1013
#define IDC_COMPUTERTYPE                1014
#define IDC_RADIONAME                   1015
#define IDC_RADIOADDRESS                1016
#define IDC_DISPLAY_TEXT                1017
#define IDC_SERVER_NAME                 1017
#define IDC_RET_CANCEL                  1018
#define IDC_PROGRESS                    1019
#define IDC_CUTIN_LINE                  1019
#define IDC_FILETEXT                    1020
#define IDC_STATIC1                     1020
#define IDC_FOLDERTEXT                  1021
#define IDC_STATIC2                     1021
#define IDC_COMBOBOXEX1                 1023
#define IDC_PASSWORD                    1024
#define IDC_USERNAME                    1025
#define IDC_EDIT_OLDPASSWORD            1026
#define IDC_EDIT_NEWPASSWORD            1027
#define IDC_EDIT_SRV_NAME               1027
#define IDC_EDIT_VERIFYPASSWORD         1028
#define IDC_EDIT_USERNAME               1028
#define IDC_EDIT_PASSWORD               1029
#define IDC_PASSWORD_EDIT               1039
#define IDC_STATIC_DOMAIN               1040
#define IDC_FILE                        1060
#define IDC_FOLDER                      1061

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
