#define IDH_NAVW_WHATHIS_PROBLEMS_FOUND_QUARAN_BTN	2001
#define IDH_NAVW_WHATHIS_QUARAN_DLG_QUARAN_BTN	2002
#define IDH_NAVW_WHATHIS_QUARAN_DLG_QUARAN_ALL_BTN	2003
#define IDH_UNKNOWN	2004
#define IDH_NAVW_WHATHIS_MAINWIN_QUARANTINE_ICON	2005
