//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by d:\work\p4\Nav32trunk\Norton_AntiVirus\Consumer\src\SpywarePlus\HomePageProtectionResources\HomePageProtectionRes.rc
//
#define IDS_HPPLV_PLUGIN_NAME           101
#define IDS_CATNAME_ACTIVITY            102
#define IDS_CATDESC_ACTIVITY            103
#define IDR_HTM_LOGENTRY                103
#define IDS_CAT_ACTIVITY_COLNAME_TIME   104
#define IDS_CAT_ACTIVITY_COLNAME_PROCNAME 105
#define IDS_CAT_ACTIVITY_COLNAME_ACTION 106
#define IDS_CAT_DETAILS                 107
#define IDS_CAT_DETAILS_TIME            108
#define IDS_CAT_DETAILS_ACTOR           109
#define IDS_CAT_DETAILS_TARGET          110
#define IDS_CAT_DETAILS_ORIGINALVALUE   111
#define IDS_CAT_DETAILS_BLOCKEDVALUE    112
#define IDS_HTML_BEGINSCRIPT            113
#define IDS_HTML_SCRIPTCOMMENT          114
#define IDS_HTML_SCRIPTFUNCTION         115
#define IDS_HTML_ENDCOMMENT             116
#define IDS_HTML_ENDSCRIPT              117
#define IDS_HTML_LINK                   118
#define IDS_CAT_DETAILS_TARGETNAME      119
#define IDS_CAT_PID                     120
#define IDS_CAT_DETAILS_ALLOWEDVALUE    121
#define IDS_DESC_SOMETHING              122
#define IDS_CAT_CURRENTPAGEFINE         143
#define IDS_CAT_COL_UNKNOWN             144
#define IDS_CAT_COL_BLOCKED             145
#define IDS_CAT_COL_ALLOWED             146
#define IDS_CAT_RESETCONFIRM            147
#define IDS_CAT_RESETCONFIRMTITLE       148
#define IDI_NAVICON                     149
#define IDS_UNKNOWN_STRING_VALUE        149
#define IDB_ALERT_TITLE_BLUE            150
#define IDS_HPPALERT_PROCROW_NAME       150
#define IDB_INFO_ICON                   151
#define IDS_HPPALERT_LOCATIONROW_NAME   151
#define IDS_HPPALERT_SINGLE_BLOCKED_BRIEF_DESC 152
#define IDS_HPPALERT_BLOCKEDVALROW_NAME 155
#define IDS_HPPALERT_SINGLE_ALLOWED_BRIEF_DESC 156
#define IDS_HPPALERT_SINGLE_ALLOWED_ACTION_DO_NOTHING 157
#define IDS_HPPALERT_OLDHOMEPAGEROW_NAME 159
#define IDS_HPPALERT_NEWHOMEPAGEROW_NAME 160
#define IDS_HPPALERT_SINGLE_TITLE       161
#define IDS_HPPALERT_SINGLE_HELPTEXT    162
#define IDS_HPPALERT_SINGLE_PROMPT_TEXT 163
#define IDS_HPPALERT_MULTI_SEPARATOR_COL1 164
#define IDS_HPPALERT_MULTI_SEPARATOR_COL2 165
#define IDS_HPPALERT_ACTION_CHANGE      166
#define IDS_HPPALERT_MULTI_TITLE        167
#define IDS_HPPALERT_MULTI_HELPTEXT     168
#define IDS_HPPALERT_MULTI_BLOCKED_ALLOWED_BRIEF_DESC 169
#define IDS_HPPALERT_MULTI_BLOCKED_BRIEF_DESC 170
#define IDS_HPPALERT_MULTI_ALLOWED_BRIEF_DESC 171
#define IDS_HPPALERT_MULTI_ERROR_BRIEF_DESC 172
#define IDS_HPPALERT_MULTI_PROMPT_TEXT  173
#define IDS_HPPALERT_FIRSTRUNDIALOG_ACTION_DO_NOTHING 174
#define IDS_CAT_DETAILS_SEPERATOR_NORMAL 175
#define IDS_CAT_DETAILS_TIME_NORMAL     176
#define IDS_CAT_DETAILS_ACTOR_NORMAL    177
#define IDS_CAT_DETAILS_TARGET_NORMAL   178
#define IDS_CAT_DETAILS_ORIGINALVALUE_NORMAL 179
#define IDS_CAT_DETAILS_BLOCKEDVALUE_NORMAL 180
#define IDS_CAT_DETAILS_ALLOWEDVALUE_NORMAL 181
#define IDS_CAT_DETAILS_TARGET_HKLM     182
#define IDS_CAT_DETAILS_TARGET_HKLM_NORMAL 183
#define IDS_HPPALERT_BLOCKED_ACTION_DO_NOTHING 184
#define IDS_HPPALERT_MULTI_ALLOWED_ACTION_DO_NOTHING 185
#define IDS_HPPALERT_MULTI_BLOCKED_ALLOWED_ACTION_DO_NOTHING 186
#define IDS_HPPALERT_URL_HOME_PAGE_HELP 186
#define IDS_HPPALERT_URL_ABOUT_BLANK    187
#define IDS_HPPALERT_FIRSTRUNDIALOG_BLOCK_BRIEF_DESC 188
#define IDS_HPPALERT_FIRSTRUNDIALOG_TITLE 189
#define IDS_HPPALERT_FIRSTRUNDIALOG_ALLOW_BRIEF_DESC 190
#define IDS_HPPALERT_URL_HOME_PAGE_HELP_DESCRIPTION 191
#define IDS_HPPALERT_URL_ABOUT_BLANK_DESCRIPTION 192
#define IDS_HPPALERT_MULTI_ALLOWED_ACTION_REVERT 193
#define IDS_HPPALERT_ALLOWED_ACTION_REVERT 193
#define IDS_HPPALERT_FIRSTRUNDIALOG_ACTION_SHOW_IE_CPL 194

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
