
#ifndef SUPPORT_IDS_H
#define SUPPORT_IDS_H

const int SUPPORT_ID_ERROR_CRITICAL = 1;
const int SUPPORT_ID_ACCESED_DENIED = 2;
const int SUPPORT_ID_BAD_ITEM = 3;
const int SUPPORT_ID_ERROR_MEMORY = 4;
const int SUPPORT_ID_ERROR_VIRUS_DEFS = 5;
const int SUPPORT_ID_ERROR_SCANNER = 6;
const int SUPPORT_ID_EULA_NOT_ACCEPTED = 7;
const int SUPPORT_ID_ERASER_REBOOT_REQUIRED = 8;

#endif

