#define A2_NAME_SIG_INTER_MACRO_HIT_ARRAY_SIZE 1
#define A2_NAME_SIG_INTRA_MACRO_HIT_ARRAY_SIZE 1
#define A2_NAMED_CRC_SIG_HIT_ARRAY_SIZE 1
#define A2_MACRO_SIG_HIT_ARRAY_SIZE 1
#define A2_CRC_HIT_ARRAY_SIZE 1
extern WD_SIG_SET_T gstA2SigSet;
