#define WD7_NAME_SIG_INTER_MACRO_HIT_ARRAY_SIZE 135
#define WD7_NAME_SIG_INTRA_MACRO_HIT_ARRAY_SIZE 135
#define WD7_NAMED_CRC_SIG_HIT_ARRAY_SIZE 631
#define WD7_MACRO_SIG_HIT_ARRAY_SIZE 17
#define WD7_CRC_HIT_ARRAY_SIZE 452
extern WD_SIG_SET_T gstWD7SigSet;
