#define WD8_NAME_SIG_INTER_MACRO_HIT_ARRAY_SIZE 135
#define WD8_NAME_SIG_INTRA_MACRO_HIT_ARRAY_SIZE 135
#define WD8_NAMED_CRC_SIG_HIT_ARRAY_SIZE 165
#define WD8_MACRO_SIG_HIT_ARRAY_SIZE 24
#define WD8_CRC_HIT_ARRAY_SIZE 127
extern WD_SIG_SET_T gstWD8SigSet;
