#define XL95_NAME_SIG_INTER_MACRO_HIT_ARRAY_SIZE 11
#define XL95_NAME_SIG_INTRA_MACRO_HIT_ARRAY_SIZE 11
#define XL95_NAMED_CRC_SIG_HIT_ARRAY_SIZE 22
#define XL95_MACRO_SIG_HIT_ARRAY_SIZE 4
#define XL95_CRC_HIT_ARRAY_SIZE 22
extern WD_SIG_SET_T gstXL95SigSet;
