#define XL97_NAME_SIG_INTER_MACRO_HIT_ARRAY_SIZE 11
#define XL97_NAME_SIG_INTRA_MACRO_HIT_ARRAY_SIZE 11
#define XL97_NAMED_CRC_SIG_HIT_ARRAY_SIZE 17
#define XL97_MACRO_SIG_HIT_ARRAY_SIZE 4
#define XL97_CRC_HIT_ARRAY_SIZE 17
extern WD_SIG_SET_T gstXL97SigSet;
