#define XL4_NAME_SIG_INTER_MACRO_HIT_ARRAY_SIZE 1
#define XL4_NAME_SIG_INTRA_MACRO_HIT_ARRAY_SIZE 1
#define XL4_NAMED_CRC_SIG_HIT_ARRAY_SIZE 1
#define XL4_MACRO_SIG_HIT_ARRAY_SIZE 1
#define XL4_CRC_HIT_ARRAY_SIZE 1
extern WD_SIG_SET_T gstXL4SigSet;
