//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SymProtectManifestUpdaterRes.rc
//
#define IDS_SYMPROTECT_MANIFESTUPDATE_BANNER_TITLE 101
#define IDS_SYMPROTECT_MANIFESTUPDATE_BANNER_COPYRIGHT 102
#define IDS_SYMPROTECT_MANIFESTUPDATE_ERROR_EXTRACT 103
#define IDS_SYMPROTECT_MANIFESTUPDATE_ERROR_COPY 104
#define IDS_SYMPROTECT_MANIFESTUPDATE_ERROR_NOPRODUCT 105
#define IDS_SYMPROTECT_MANIFESTUPDATE_PROGRESS_FOUND_SAV 106
#define IDS_SYMPROTECT_MANIFESTUPDATE_UPDATED_SAV 106
#define IDS_SYMPROTECT_MANIFESTUPDATE_SEARCHINGFOR_SCS 107
#define IDS_SYMPROTECT_MANIFESTUPDATE_PROGRESS_FOUND_SCS 107
#define IDS_SYMPROTECT_MANIFESTUPDATE_UPDATED_SCS 107
#define IDS_SYMPROTECT_MANIFESTUPDATE_SWITCH_FORCESCS 108
#define IDS_SYMPROTECT_MANIFESTUPDATE_SWITCH_FORCESAV 109
#define IDS_SYMPROTECT_MANIFESTUPDATE_ERROR_DELETE 110
#define IDS_SYMPROTECT_MANIFESTUPDATE_ERROR_DELETETEMP 110

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
