//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DWHWizrdRes.rc
//
#define MANIFEST_RESOURCE_ID              1
#define IDS_TEST                        2
#define IDB_CHECKMARK                   100
#define IDB_CHECKMARK_MASK              101
#define IDD_DWHWIZRD_DIALOG             102
#define IDB_NOWAYJOSE                   110
#define IDB_NOWAYJOSE_MASK              111
#define IDB_NETSCAPELOGO                120
#define IDB_NETSCAPELOGO_MASK           121
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       129
#define IDI_ICON2                       130
#define IDI_ICON3                       131
#define IDI_ICON4                       132
#define IDI_ICON5                       133
#define IDI_ICON6                       134
#define IDI_ICON7                       135
#define IDI_ICON8                       136
#define IDI_ICON9                       137
#define IDI_ICON10                      138
#define IDI_ICON11                      139
#define IDI_ICON12                      140
#define IDI_ICON13                      141
#define IDI_ICON14                      142
#define IDI_ICON15                      143
#define IDB_WZ256_0                     160
#define IDB_WZ256_1                     161
#define IDB_WZ256_2                     162
#define IDB_WZ256_3                     163
#define IDB_WZ256_4                     164
#define IDB_WZ256_5                     165
#define IDB_WZ256_6                     166
#define IDB_WZ256_7                     167
#define IDB_WZ_16_0                     180
#define IDB_WZ_16_1                     181
#define IDB_WZ_16_2                     182
#define IDB_WZ_16_3                     183
#define IDB_WZ_16_4                     184
#define IDB_WZ_16_5                     185
#define IDB_WZ_16_6                     186
#define IDB_WZ_16_7                     187
#define IDB_SIRENS                      200
#define IDB_BITMAP1                     210
#define IDB_BITMAP2                     211
#define IDB_BITMAP3                     212
#define IDB_BITMAP4                     213
#define IDB_BITMAP5                     214
#define IDB_BITMAP6                     215
#define IDB_BITMAP7                     216
#define IDB_BITMAP8                     217
#define IDB_BITMAP9                     218
#define IDB_BITMAP10                    219
#define IDB_BITMAP11                    220
#define IDB_BITMAP12                    221
#define IDB_BITMAP13                    222
#define IDB_BITMAP14                    223
#define IDB_BITMAP15                    224
#define IDB_BITMAP16                    225
#define IDB_BITMAP17                    226
#define IDB_BITMAP18                    227
#define IDB_BITMAP19                    228
#define IDB_BITMAP20                    229
#define IDC_ANIMATE                     1000
#define IDC_PICTURE                     1001
#define IDC_DOIT                        1002
#define IDC_LIST1                       1003
#define IDC_LIST_VIRUSES                1003
#define IDC_VIRUS_INFO_BUTTON           1004
#define IDC_BUTTON_VIRUS_INFO           1004
#define IDC_RADIO1                      1005
#define IDC_RADIO2                      1006
#define IDC_LISTVIEW                    1007
#define IDC_ADVICE_BUTTON               1010
#define IDC_MORE_INFO_BUTTON            1012
#define IDC_ITEMS_SCANNED_STATIC        1013
#define IDC_ITEMS_INFECTED_STATIC       1014
#define IDC_ITEMS_REPIRED_STATIC        1015
#define IDC_RADIO_AUTOMATIC             1017
#define IDC_RADIO_MANUAL                1018
#define IDC_ITEMS_REPAIRED_STATIC       1019
#define IDC_ITEMS_QUARANTINED_STATIC    1020
#define IDC_ITEMS_DELETED_STATIC        1021
#define IDC_FINISH_TEXT                 1022
#define IDS_PROPSHT_CAPTION             2000
#define IDS_RW_NAME                     2001
#define IDS_RW_VIRUS_NAME               2002
#define IDS_RW_CLOSE                    2003
#define IDS_CANCELREPWIZ_CAPTION        2013
#define IDS_CANCELREPWIZ_BODY           2014
#define IDS_SUMM_SCANNED                2020
#define IDS_SUMM_INFECTED               2021
#define IDS_SUMM_CLEANED                2022
#define IDS_SUMM_QUARANTINED            2023
#define IDS_REPWIZ_BYPASSREGKEY         2024
#define IDS_WIZWHYNOT_ZIPSENTENCE       2025
#define IDS_WIZWHYNOT_ZIPLINE1          2026
#define IDS_WIZWHYNOT_ZIPLINE2          2027
#define IDS_WIZWHYNOT_MBRSENTENCE       2028
#define IDS_WIZWHYNOT_MBRLINE1          2029
#define IDS_WIZWHYNOT_MBRLINE2          2030
#define IDS_WIZWHYNOT_BOOTSENTENCE      2031
#define IDS_WIZWHYNOT_BOOTLINE1         2032
#define IDS_WIZWHYNOT_BOOTLINE2         2033
#define IDS_WIZWHYNOT_FILESENTENCE      2034
#define IDS_WIZWHYNOT_FILELINE1         2035
#define IDS_WIZWHYNOT_FILELINE2         2036
#define IDS_WIZWHYNOT_FILELINE3_95      2037
#define IDS_WIZWHYNOT_CONSULT           2038
#define IDS_WIZWHYNOT_CAPTION           2039
#define IDS_WIZWHYNOT_FILELINE4         2041
#define IDS_WIZWHYNOT_FILELINE3_NT      2042
#define IDS_CLOSEREPWIZ_BODY            2044
#define IDS_NOVIRUSESDETECTED           2045
#define IDS_REPWIZ_DEFAULTREGKEY        2048
#define IDS_MEMORY                      2050
#define IDS_DOWNLOADMOVED               2055
#define IDS_FILEMOVED                   2056
#define IDS_DOWNLOADNOTMOVED            2057
#define IDS_FILENOTMOVED                2058
#define IDS_SUMM_DELETED                2070
#define IDS_FINISH_TEXT_CONGRATS        2074
#define IDS_FINISH_TEXT_ATTENTION       2075
#define IDS_RESTORE_OVERWRITE_TITLE     2076
#define IDS_RESTORE_OVERWRITE_FORMAT    2077
#define IDS_FINISH_TEXT_NO_RESTORE      2078
#define IDD_WIZPAGE1                    2400
#define IDD_WIZPAGE2                    2401
#define IDD_WIZPAGE3                    2402
#define IDD_WIZPAGE4                    2403
#define IDD_WIZPAGE5                    2404
#define IDD_WIZPAGE6                    2405
#define IDD_WIZPAGE7                    2406

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        255
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
