START DATABASE MANAGER
CONNECT TO AVISDATA

DROP TRIGGER AnalysisRequestTR1
DROP TRIGGER AnalysisRequestTR2
DROP TRIGGER AnalysisRequestTR4
DROP TRIGGER AnalysisRequestTR5
DROP TRIGGER AnalysisRequestTR6
DROP TRIGGER AnalysisRequestTR7
DROP TRIGGER AnalysisRequestTR8
DROP TRIGGER AnalysisRequestTR9
DROP TRIGGER AnalysisRequestTRA
DROP TRIGGER SignaturesTR1a
DROP TRIGGER SignaturesTR1b
DROP TRIGGER SignaturesTR2
DROP TRIGGER SubmittorsTR1
DROP TRIGGER GlobalsTR1
DROP TRIGGER AttributeKeysTR1
DROP TRIGGER AnalysisStInfTR1
DROP TRIGGER GlobalsTR2
DROP TRIGGER ServersTR1
DROP TRIGGER AnalysisRequestTR3
--DROP TRIGGER AttributesTR1
DROP TRIGGER AttributeKeysTR2
DROP TRIGGER AnalysisStInfTR2
DROP TRIGGER ServersTR2
DROP TRIGGER SubmittorsTR3
DROP TRIGGER AnalysisResultsTR3


DELETE FROM RemoteMustBeUnique
--DELETE FROM Attributes
DELETE FROM AnalysisRequest
DELETE FROM Globals
DELETE FROM AnalysisResults
DELETE FROM DefinitionNameMap
DELETE FROM SigsToBeExported
DELETE FROM Signatures
DELETE FROM Submittors
DELETE FROM Servers
DELETE FROM AnalysisStateInfo
DELETE FROM AttributeKeys

DISCONNECT ALL
