# Copyright 2004-2005 Symantec Corporation. All rights reserved.
# Author: Bertil Askelid <Bertil_Askelid@Symantec.com>
# Intent: VPRegEdt Makefile

Root = ../

Macros = SERVER

Includes = $(PScan)\
			  $(LDVP)/include\
			  $(LDVPmisc)\
			  $(QuarantineServer)/Shared/Include\
			  $(MD5)/include\
			  $(AMS)/include

Sources = regedit.cpp ../VPReg/regmem.cpp
Binary  = VPRegEdt.bin

include $(Root)Rules.mk
