//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NAVTaskWizard.rc
//
#define IDR_COSYMSWPLUGIN_SW            102
#define IDS_PRODUCTOPTIONS_DESC         103
#define IDD_USERTASK_PROPERTIES         103
#define IDR_NSWPLUGINVIEW               104
#define IDS_OPTIONPG1TITLE              105
#define IDI_APOFF                       105
#define IDB_SCAN_FOLDER_CHECKBOXES      105
#define IDR_NSWPLUGINOPTIONS            106
#define IDS_CHECKBOX                    107
#define IDD_TW_INTRO                    107
#define IDR_NSWCATEGORY                 108
#define IDS_CATEGORYTITLE               109
#define IDR_NSWFRAME                    110
#define IDS_HELPFILENAME                110
#define IDD_TW_SELECTITEMS              110
#define IDD_TW_SAVETASK                 111
#define IDC_TB_LADVISE                  112
#define IDS_CLOSE_BTN_TEXT              114
#define IDS_CONFIRM_DELETE_TASK         116
#define IDS_TB_LADVISE                  117
#define IDI_APON                        130
#define IDI_VIRUSLIST                   132
#define IDI_ACTIVITYLOG                 134
#define IDI_QUARANTINE                  136
#define IDB_TASK_IMGLIST                137
#define IDB_WIZ256_0                    138
#define IDB_WIZ256_2                    141
#define IDB_WIZ256_3                    142
#define IDB_WIZ16_0                     143
#define IDR_RCLK_BUILTIN_SCAN           144
#define IDB_WIZ16_2                     144
#define IDR_RCLK_USER_SCAN              145
#define IDB_WIZ16_3                     145
#define IDR_RCLK_NO_SCAN_TASK           146
#define IDD_BUILTIN_PROPERTIES          147
#define IDB_SCANITEM_IMGLIST            148
#define IDI_NAV_BAG_BIG                 154
#define IDB_SYSSTATUS_IMGLIST           156
#define IDR_RCLK_SYSTEM_STATUS          157
#define IDR_RCLK_SYSSTATUS_NO_ITEM      158
#define IDR_RCLK_REPORTS                159
#define IDR_RCLK_REPORTS_NO_ITEM        160
#define IDD_INTEG_SYSTEM_STATUS         161
#define IDR_TASK_BTN_DROPDOWN           161
#define IDD_INTEG_VIRUS_SCAN            162
#define IDD_INTEG_REPORTS               163
#define IDD_TW_SAVEEDITEDTASK           191
#define IDB_PRODBM_UP                   201
#define IDB_PRODBM_DOWN                 202
#define IDB_PRODBM_OVER                 203
#define IDB_PRODBM_DISABLED             204
#define IDB_CATEGORYBACKGND             205
#define IDC_CLIENTWND                   206
#define IDC_STATIC1                     207
#define IDC_STATIC2                     208
#define IDC_DRIVE_LIST                  209
#define ID_SCAN                         210
#define IDC_STATIC_TW_INTRO             211
#define IDC_STATIC_SELECTITEMS_INTO     212
#define IDD_SELECT_SCAN_FOLDERS         300
#define IDC_FOLDER_TREE                 301
#define IDC_TREE_HEADER                 302
#define IDD_SELECT_SCAN_DRIVES          3000
#define IDS_NO_ITEMS_IN_TASK            5000
#define IDB_DRIVE_LIST_CHECKBOXES       5000
#define IDS_DRIVE_ITEM_DESCRIPTION      5001
#define IDS_FOLDER_AND_SUBS_ITEM_DESCRIPTION 5002
#define IDB_LU_UP                       6002
#define IDB_SCHED_UP                    6003
#define IDC_ITEMLIST                    6009
#define IDC_SCAN_FOLDER                 6011
#define IDC_SCAN_FILE                   6012
#define IDC_STATUS_LIST                 6016
#define IDC_TASK_ITEMLIST               6016
#define IDC_AP_CONTROL_BTN              6025
#define IDC_APSTATUS_ICON               6026
#define IDC_DETAILS                     6027
#define IDC_TASK_LIST                   6029
#define IDC_RUN_SCAN                    6030
#define IDC_CREATE_TASK                 6031
#define IDC_TASK_PROPERTIES             6032
#define IDC_DELETE_TASK                 6035
#define IDC_PICTURE                     6036
#define IDS_SCAN_COMPUTER_DESCRIPTION   6036
#define IDC_REMOVE                      6037
#define IDS_SCAN_HD_DESCRIPTION         6037
#define IDC_TASK_NAME                   6038
#define IDS_SCAN_REMOVABLE_DESCRIPTION  6038
#define IDS_SCAN_FLOPPY_DESCRIPTION     6039
#define IDS_SCAN_FOLDERS_DESCRIPTION    6040
#define IDS_SCAN_FILES_DESCRIPTION      6041
#define IDC_TASKS_DROPDOWN              6042
#define IDS_TASK_WIZARD_DESCRIPTION     6042
#define IDS_SHOW_INFO_STATUS            6043
#define IDS_HIDE_INFO_STATUS            6044
#define IDP_LAUNCH_TASK_ERROR           6046
#define IDP_TASKWIZ_ERROR_SAVING_TASK   6048
#define IDP_NO_REMOVABLE_DRIVES         6049
#define IDP_NO_FLOPPY_DRIVES            6050
#define IDS_ONE_FILE_IN_QUAR            6051
#define IDS_MULTIPLE_FILES_IN_QUAR      6052
#define IDS_ERROR_READING_QUAR_CONTENTS 6053
#define IDS_QUAR_EMPTY                  6054
#define IDS_QUAR_ERROR_DETAILS          6055
#define IDC_AP_STATUS_TEXT              6056
#define IDS_QUAR_EXPLANATION            6056
#define IDS_STATUS_DETAILS              6057
#define IDS_QUAR_EMPTY_EXPLANATION      6058
#define IDS_DEFS_UP_TO_DATE             6059
#define IDS_DEFS_OLD_WARNING            6060
#define IDC_CREATED_TIME                6060
#define IDS_DEFS_OLD_URGENT             6061
#define IDC_MODIFIED_TIME               6061
#define IDS_ERROR_READING_DEFS_DATE     6062
#define IDC_LAST_RUN_TIME               6062
#define IDC_AP_STATUS_SEP               6063
#define IDS_DEFS_DESCRIPTION            6063
#define IDS_DEFS_OK_DETAILS             6064
#define IDS_DEFS_OLD_DETAILS            6065
#define IDS_LAUNCH_NAVLU_ERROR          6066
#define IDS_DEFS_OK_DETAILS2            6067
#define IDS_NO_DETAILS_AVAILABLE        6068
#define IDS_RESCUE_DISK_OK              6069
#define IDS_RESCUE_DISK_OUT_OF_DATE     6070
#define IDS_RESCUE_DISK_STATUS_UNKNOWN  6071
#define IDS_RESCUE_DISK_EXPLANATION     6072
#define IDS_RESCUE_DISK_OUT_OF_DATE_DETAILS 6073
#define IDS_RESCUE_DISK_UP_TO_DATE      6074
#define IDS_LAUNCH_RESCUE_ERROR         6075
#define IDC_DESCRIPTION                 6075
#define IDS_SELECT_ADD_FOLDERS          6076
#define IDS_SCAN_DRIVES_DESCRIPTION     6076
#define IDS_ADD_FOLDERS_BTN_TEXT        6077
#define IDS_NAV                         6091
#define IDS_SCAN_TASK_PROPERTIES        6093
#define IDS_ENTER_TASK_NAME             6094
#define IDS_ILLEGAL_CHAR_IN_NAME        6095
#define IDS_DEFS_STATUS_UNKNOWN_DETAILS 6096
#define IDS_AP_AGENT_FILENAME           6097
#define IDS_NAVAP_SERVICE_NAME          6098
#define IDS_NO_FOLDERS_SELECTED         6101
#define IDS_RUN_NEW_SCAN_NOW            6102
#define IDS_ALL_FILES_FILTER            6103
#define IDS_SCAN_FILES                  6104
#define IDS_DISABLE_BTN_TEXT            6106
#define IDS_ENABLE_BTN_TEXT             6107
#define IDS_AP_ENABLED                  6108
#define IDS_AP_DISABLED                 6109
#define IDS_NO_ITEMS_IN_LIST            6111
#define IDS_QUAR_REPORT_TEXT            6112
#define IDS_LOG_REPORT_TEXT             6113
#define IDS_VIRUS_LIST_REPORT_TEXT      6114
#define IDP_SCAN_TASK_EXISTS            6115
#define IDC_PANEL_HEADER                6150
#define IDC_REPORT_LIST                 6154
#define IDC_OPEN_REPORT                 6155
#define IDC_SCAN                        6156
#define IDC_TB_SCHED                    6314
#define IDC_TB_LU                       6315
#define IDS_TB_SCHED                    6316
#define IDS_TB_LU                       6317
#define IDS_SYSTEM_SCAN_NOT_DONE        6319
#define IDB_LADVISE_UP                  6320
#define IDS_SYSTEM_SCAN_TODAY           6320
#define IDS_SYSTEM_SCAN_YESTERDAY       6321
#define IDS_SYSTEM_SCAN_NUM_DAYS        6322
#define IDS_LAST_VIRUS_FOUND_NUM_DAYS   6323
#define IDS_NUM_VIRUSES                 6324
#define IDS_TITLE                       6325
#define ID_SCHEDULE_SCAN                32769
#define ID_WHATS_THIS                   40002
#define ID_EDIT_TASK                    40006
#define ID_VIEW_ALL_TASKS               40008
#define ID_VIEW_BUILTINS                40009
#define ID_VIEW_USERTASKS               40010
#define ID_DETAILS                      40016
#define ID_SHOW_HIDE_INFO               40019
#define ID_RENAME_TASK                  40020

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        6325
#define _APS_NEXT_COMMAND_VALUE         32770
#define _APS_NEXT_CONTROL_VALUE         213
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
