// PROPRIETARY/CONFIDENTIAL. Use of this product is subject to license terms.
// Copyright 1998 - 2003, 2005 Symantec Corporation. All rights reserved. 
//*************************************************************************
// defwatch.h - created 11/6/98 1:57:15 PM
//
// $Header$
//
// Description:
//
// Contains:
//
//*************************************************************************
// $Log$
//*************************************************************************

#ifndef _DEFWATCH_H_
#define _DEFWATCH_H_

// 
// This file is generated by the MC message compiler.
// 
#ifdef BUILDING_DEFWATCH
#include "dwmsg.h"
#endif

// 
// Macros
// 
#define DEFWATCH_SERVICE_NAME           TEXT( "DefWatch" )
#define SYMANTEC_INSTALLED_APPS_KEY     _T( "SOFTWARE\\Symantec\\InstalledApps" )
#define DEFINFO_DAT                     _T( "DEFINFO.DAT" )
#define DEFWATCH_REG_KEY                _T( "SOFTWARE\\Symantec\\SharedDefs\\DefWatch" )
#define DEFWATCH_HANDLERS_REG_KEY       _T( "SOFTWARE\\Symantec\\SharedDefs\\DefWatch\\Handlers" )
#define DEFWATCH_DEFVER_VAL             _T( "DefVersion" )
#define HAWKING_APP_ID                  "DEFWATCH_10"


// 
// Prototypes
// 
#ifdef _DEBUG
void DefWatchDebugOut(LPSTR String, DWORD Status = 0);
#else
#define DefWatchDebugOut
#endif


void DefWatchLogEvent( DWORD dwMsgID,
					   WORD wType = EVENTLOG_ERROR_TYPE,
					   LPSTR lpszParam1 = NULL ,
					   LPSTR lpszParam2 = NULL ,
					   LPSTR lpszParam3 = NULL ,
					   LPSTR lpszParam4 = NULL  );
#endif
