////////////////////////
//
// PROPRIETARY / CONFIDENTIAL.
// Use of this product is subject to license terms.
// Copyright © 2006 Symantec Corporation.
// All rights reserved.
//
/////////////////////////////////////////////////////////////////////////////////////////////////

//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NAVCOMUIRes.rc
//
#define IDC_OPEN_QUARANTINE             3
#define IDR_SCRIPTINFECTION             101
#define IDS_FONTNAME                    101
#define IDS_PROCESS_NAME                101
#define IDR_SCRIPTSCANRESULTS           102
#define IDS_FILENAME_COL                102
#define IDR_SCRIPTREPAIRSINK            103
#define IDS_VIRUSNAME_COL               103
#define IDR_SCRIPTCOMMONUI              104
#define IDS_STATUS_COL                  104
#define IDB_AXLISTVIEWCTRL              105
#define IDS_SCAN_MEMDETECT_TIMEOUT      105
#define IDR_AXSYSLISTVIEW32             106
#define IDS_REPAIR_FAILED               106
#define IDR_SURROGATECOMMONUI           107
#define IDS_QUARANTINE_FAILED           107
#define IDS_REMOVE_FAILED               108
#define IDS_REPAIRED                    109
#define IDS_QUARANTINED                 110
#define IDS_UNKNOWN_REMEDIATION_ACTION_TEXT 111
#define IDS_INFECTED                    112
#define IDS_WITHIN                      113
#define IDS_OEH_DESCRIPTION             113
#define IDR_SCRIPTMEMSCANUI             114
#define IDS_MASTER_BOOT_RECORD          114
#define IDS_QUARANTINE_THIS             114
#define IDS_BOOT_RECORD                 115
#define IDS_ALLOW_THIS                  115
#define IDS_BLOCK_THIS                  116
#define IDS_AUTHORIZE_THIS              117
#define IDR_AXLISTVIEWCTRLEVENTBRIDGE   118
#define IDS_WHATTODO                    118
#define IDS_SENDER                      118
#define IDS_ALERT_TITLE_FONTSIZE        119
#define IDS_ALERT_FONT                  120
#define IDS_ALERT_FONTSIZE              121
#define IDS_WORM_DETECTED               123
#define IDS_OEH_ALERT_WORM_DETECTED     123
#define IDS_OEH_QUARANTINE_FAILED       124
#define IDS_OEH_ALERT_QUAR_FAILED       125
#define IDS_QUARANTINED_SUCCESSFUL      126
#define IDS_QUAR_DESCRIPTION            127
#define IDS_OK_DESCRIPTION              128
#define IDS_QUARANTINED_DESC            129
#define IDS_QUARANTINED_DESC_ADDITIONAL 130
#define IDS_RECIPIENT                   131
#define IDS_DEFAULT_REGISTRY_KEY_TEXT   132
#define IDS_OTHERAREAS_ONE_UNKNOWN      133
#define IDS_CATEGORY_COL                134
#define IDS_TYPE_COL                    134
#define IDS_TYPE_VIRUS                  135
#define IDS_EXCLUDED                    136
#define IDS_EXCLUDE_FAILED              137
#define IDS_THREAT_INFECTED_STATUS      138
#define IDS_SUBJECT                     139
#define IDS_HELP                        140
#define IDS_FOUND                       141
#define IDS_BLOCK_THIS_RECOMMENDED      142
#define IDS_EXPANDED_THREAT_URL_PREFIX  143
#define IDS_EXPANDED_THREAT_URL_GENERIC 144
#define IDS_EXPANDED_THREAT_URL_VIRUS   145
#define IDS_EXPANDED_THREAT_URL_SECURITY_RISK 146
#define IDS_EXPANDED_THREAT_URL_ADWARE  147
#define IDS_EXPANDED_THREAT_URL_DIALERS 148
#define IDS_EXPANDED_THREAT_URL_HACK_TOOLS 149
#define IDS_EXPANDED_THREAT_URL_JOKE_PROGRAMS 150
#define IDS_EXPANDED_THREAT_URL_REMOTE_ACCESS 151
#define IDS_EXPANDED_THREAT_URL_SPYWARE 152
#define IDS_PLACEHOLDER                 153
#define IDS_ACTION_REMOVE               153
#define IDS_THREAT_EXCLUDE_STATUS       154
#define IDS_DOWNLOAD_TOOL_TEXT          155
#define IDS_ACTION_REPAIR               156
#define IDS_ACTION_QUARANTINE           157
#define IDS_ACTION_REPTHENQUAR          158
#define IDS_ACTION_DELETE               159
#define IDS_OTHERAREAS_PLURAL_UNKOWN    159
#define IDS_ACTION_REPTHENDELETE        160
#define IDS_ACTION_EXCLUDE              161
#define IDS_ACTION_IGNORE               162
#define IDB_AXSYSLISTVIEW32OAA          163
#define IDS_OTHERAREA_FILES             163
#define IDR_AXSYSLISTVIEW32OAA          164
#define IDS_OTHERAREAS_PROCS            164
#define IDS_OTHERAREAS_REGKEYS          165
#define IDS_OTHERAREAS_BRS              166
#define IDS_OTHERAREAS_MBRS             167
#define IDS_OTHERAREAS_BATCH            168
#define IDS_OTHERAREAS_INI              169
#define IDS_OTHERAREAS_SERVICES         170
#define IDS_OTHERAREAS_COM              171
#define IDS_OTHERAFFECTEDAREAS_UNHANDLED_DESCRIPTION 172
#define IDS_OTHERAFFECTEDAREAS_HANDLED_DESCRIPTION 173
#define IDS_REBOOT_WARNING              174
#define IDS_DAMAGE_VALUE                175
#define IDS_RECOMMENDED                 176
#define IDS_DEPENDENCY_WARNING_IMAGE    177
#define IDS_DEPENDENCY_WARNING_TEXT     178
#define IDS_USE_QUARANTINE_NOTE_IMAGE   179
#define IDS_DEPENDENCY_WARNING_DLG_TEXT 180
#define IDS_BLUE_TEXT                   180
#define IDS_OTHERAREAS_LSP              180
#define IDS_FMT_THREATS_REMAINING_DESC  181
#define IDS_OTHERAREA_FILE              182
#define IDS_OTHERAREAS_PROC             183
#define IDS_OTHERAREAS_REGKEY           184
#define IDS_OTHERAREAS_BR               185
#define IDS_OTHERAREAS_MBR              186
#define IDS_OTHERAREAS_ONE_BATCH        187
#define IDS_OTHERAREAS_ONE_INI          188
#define IDS_OTHERAREAS_SERVICE          189
#define IDS_OTHERAREAS_ONE_COM          190
#define IDS_OTHERAREA_DETAIL_COLUMN_HEADER 191
#define IDS_OTHERAREA_STATUS_COLUMN_HEADER 192
#define IDS_OTHERAREA_AREA_COLUMN_HEADER 193
#define IDS_PERFORMANCE                 194
#define IDS_STEALTH                     195
#define IDS_REMOVAL                     196
#define IDS_PRIVACY                     197
#define IDS_OVERALL                     198
#define IDS_CANTPROCESS_WARNING_TEXT    199
#define IDS_PROCESSED_ALL_SUCCESSFULLY  200
#define IDR_COMMON_UI_PROGRESS          201
#define IDC_ALERT_TEXT                  201
#define IDS_RESULTS_NOTE_ITEMS_REMAINING 201
#define IDC_STATUS_ICON                 202
#define IDS_DEFS_OLD                    202
#define IDC_DESCRIPTION                 203
#define IDS_ACTION_REVIEW               203
#define IDC_PROCESS_TEXT                204
#define IDC_ADDITIONAL_DESCRIPTION      204
#define IDS_ACTION_IGNORED              204
#define IDC_PROCESS_NAME                205
#define IDS_REBOOT_TITLE                205
#define IDC_WHATTODO_TEXT               206
#define IDS_REMOVED                     206
#define IDC_HELP_ARROW                  207
#define IDS_REMAINING_RISK_DESCRIPTION_EMAIL 207
#define IDC_HELP_LINK                   208
#define IDS_REPAIRED_RISK_DESCRIPTION_EMAIL 208
#define IDC_ACTION_TEXT                 209
#define IDS_OTHERAREAS_LSPS             209
#define IDC_ACTION                      210
#define IDS_OTHERAREA_HOST              210
#define IDC_BOTTOM                      211
#define IDS_OTHERAREA_HOSTS             211
#define IDC_MOREINFO_LINK               212
#define IDR_COMMON_UI_REPAIR            213
#define IDC_DOTTED                      213
#define IDC_HELP_ARROW2                 213
#define IDR_COMMON_UI_SUMMARY           214
#define IDC_DOTTED2                     214
#define IDI_NAV                         215
#define IDC_QUAR_DESCRIPTION            216
#define IDC_OK_DESCRIPTION              217
#define IDC_SENDER_TEXT                 218
#define IDC_RECIPIENT_TEXT              219
#define IDC_SUBJECT_TEXT                220
#define IDI_GENERICICON                 221
#define IDC_SENDER                      221
#define IDI_WINDOWSLOGO                 222
#define IDC_RECIPIENT                   222
#define IDC_SUBJECT                     223
#define IDC_EMAILINFO_TEXT              225
#define IDI_CHECKED                     226
#define IDC_INFORMATION                 226
#define IDI_UNCHECKED                   227
#define IDC_HAND_CURSOR                 251
#define IDR_MAINFRAME                   252
#define IDB_OEH_ALERT                   302
#define IDB_OEH_QUAR_SUCCESS            303
#define IDD_DIALOG1                     308
#define IDD_SCAN_CONDITIONAL            308
#define IDD_SCAN_MEMINFECTION           309
#define IDS_THREATNAME_COL              310
#define IDS_THREATWARNING_COL           312
#define IDS_REPAIRACTION_COL            313
#define IDI_BUG_RED                     314
#define IDI_BUG_YELLOW                  315
#define IDI_BUG_GREEN                   316
#define IDI_GREEN_CHECK                 317
#define IDS_TAB1_TITLE1                 322
#define IDS_TAB1_TITLE2                 323
#define IDS_TAB2_TITLE1                 324
#define IDS_TAB2_TITLE2                 325
#define IDR_ACCELERATOR1                326
#define IDS_HTML_INNER_SELECT           327
#define IDD_CONFIRM                     328
#define IDS_HTML_COMFIRM_STOP_SCAN      329
#define IDS_CONDITIONAL_SPYWARE         330
#define IDD_OTHER_AFFECTED_AREAS        331
#define IDS_REMAINING_RISK_DESCRIPTION  332
#define IDS_REPAIRED_RISK_DESCRIPTION   333
#define IDS_USE_QUARANTINE_NOTE         334
#define IDS_RENEW_SUBCRIPTION_ADMIN     335
#define IDS_RENEW_SUBCRIPTION_NONADMIN  336
#define IDS_GREENTEXTNOITEMS            337
#define IDS_GREENTEXT                   338
#define IDS_REDTEXT                     339
#define IDS_RED_TEXT                    339
#define IDS_THREAT_TYPE                 340
#define IDI_RED_SQUARE                  341
#define IDI_YELLOW_SQUARE               342
#define IDS_THREAT_MATRIX_LOW           343
#define IDS_THREAT_MATRIX_MED           344
#define IDS_THREAT_MATRIX_HIGH          345
#define IDD_THREAT_MATRIX               346
#define IDS_THREAT_MATRIX_DESC_01       347
#define IDD_KNOWN_DEPENDENCIES_WARNING  347
#define IDS_THREAT_MATRIX_DESC_OVERALL_HIGH 347
#define IDD_THREATS_REMAINING           348
#define IDD_SCAN_CONDITIONAL1           348
#define IDS_THREAT_MATRIX_DESC_OVERALL_MED 348
#define IDS_THREAT_MATRIX_DESC_OVERALL_LOW 349
#define IDD_HANDLE_LOW_THREATS          349
#define IDS_THREAT_MATRIX_DESC_PERF_HIGH 350
#define IDS_THREAT_MATRIX_DESC_PERF_MED 351
#define IDS_THREAT_MATRIX_DESC_PERF_LOW 352
#define IDS_THREAT_MATRIX_DESC_PRIV_HIGH 353
#define IDS_THREAT_MATRIX_DESC_PRIV_MED 354
#define IDS_THREAT_MATRIX_DESC_PRIV_LOW 355
#define IDS_THREAT_MATRIX_DESC_REMOVE_HIGH 356
#define IDS_THREAT_MATRIX_DESC_REMOVE_MED 357
#define IDS_THREAT_MATRIX_DESC_REMOVE_LOW 358
#define IDS_THREAT_MATRIX_DESC_STEALTH_HIGH 359
#define IDS_THREAT_MATRIX_DESC_STEALTH_MED 360
#define IDS_THREAT_MATRIX_DESC_STEALTH_LOW 361
#define IDS_THREAT_MATRIX_IMAGE         362
#define IDS_SCAN_RESULT_EMAIL_TITLE     363
#define IDS_SCAN_RESULTS_NORMAL_TITLE   364
#define IDS_QUICKSCANGREENTEXTNOITEMS   365
#define IDS_QUICKSCAN_TITLE             366
#define IDS_RESULTS_NOTE_QUICKSCAN      367
#define IDS_PROCESSED_ALL_SUCCESSFULLY_QUICKSCAN 368
#define IDS_RECOMMENDED_ABBREV          369
#define IDS_MANUAL_REMOVAL_WARNING      370
#define IDS_DEPENDENCY_WARNING          371
#define IDS_THREATIMPACT_COL            372
#define IDS_RESULTS_NOTE_FIX_NOW        373
#define IDS_DEPENDENCY_WARNING_PAST_TENSE 374
#define IDS_VIEW_REMOVAL_INSTRUCTIONS   375
#define IDS_QUARANTINE_NAME             376
#define IDS_FONTEZ_LISTBOXHEADER        380
#define IDS_FONTEZ_LISTBOXDETAIL        381
#define IDS_FONTEZ_HYPERLINK            382
#define IDS_FONTEZ_LISTBOXDETAIL_FAKE   383
#define IDS_MEM_INFECTION               384
#define IDS_REPAIR_PROGRESS             385
#define IDS_HAS_DEPENDENCIES            386
#define IDS_HAS_NO_DEPENDENCIES         387
#define IDD_RISK_DETAILS                388
#define IDS_RISK_ASSESSMENT_TAB_TEXT    389
#define IDS_DETAILS_TAB_TEXT            390
#define IDS_DEFS_OLD_NOSPYWARE          391
#define IDS_GREENTEXTNOITEMS_NOSPYWARE  392
#define IDS_QUICKSCANGREENTEXTNOITEMS_NOSPYWARE  393
#define IDS_SCAN_RESULTS_RISKS_LABEL    394
#define IDS_SCAN_RESULTS_RISKS_LABEL_NOSPYWARE  395
#define IDS_SCAN_PROGRESS_RISKS_LABEL   396
#define IDS_SCAN_PROGRESS_TITLE_LABEL   397
#define IDS_SCAN_PROGRESS_TITLE_LABEL_NOSPYWARE  398
#define IDS_RESULTS_NOTE_ITEMS_REMAINING_SINGULAR 399
#define IDS_REMAINING_RISK_DESCRIPTION_HC 400
#define IDS_ADDITIONAL_SCAN             401
#define IDS_ADDITIONAL_SCAN_IMAGE       402
#define IDS_MEM_INFECTION_RECOMMEND     403
#define IDS_CANT_RESTORE_WARNING        404
#define ID_F1_HELP                      32771
#define ID_ALT_KEY                      32772
#define ID_LEFT                         32774
#define ID_RIGHT                        32775
#define ID_ACCELERATOR32777             32777
#define ID_CTRLTAB                      32777
#define ID_CTRLSHIFTTAB                 32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        386
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         227
#define _APS_NEXT_SYMED_VALUE           165
#endif
#endif
