//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AvProdAppRes.rc
//
#define IDS_TRAYICON_TEXT_NORMAL        101
#define IDS_TRAYICON_TEXT_ABNORMAL      102
#define IDB_OEHALERT_TITLE_RED          102
#define IDS_TRAYICON_TEXT_UNKNOWN       103
#define IDB_OEHALERT_TITLE_YELLOW       103
#define IDS_TRAYICON_TEXT_WORKING       104
#define IDS_TRAYICON_TEXT_INFORMATION   105
#define IDS_TRAYICON_TEXT_WARNING       106
#define IDS_OEHALERT_SUBJECT            107
#define IDS_OEHALERT_SENDER             108
#define IDS_OEHALERT_WORMPATH           109
#define IDS_OEHALERT_RECIPIENT          110
#define IDS_OEHALERT_TITLE              111
#define IDS_OEHALERT_ACTION_TITLE       112
#define IDS_OEHALERT_ACTION_QUARANTINE  113
#define IDS_OEHALERT_ACTION_AUTHORIZE   114
#define IDS_OEHALERT_ACTION_ABORT       115
#define IDS_OEHALERT_ACTION_IGNORE      116
#define IDS_OEHALERT_BRIEF_DESC         117
#define IDS_OEHALERT_PROMPT_TEXT        118
#define IDR_MENU_TRAY                   119
#define IDS_REBOOTREQUEST_TITLE         119
#define IDS_REBOOTREQUEST_BRIEF_DESC    120
#define IDS_REBOOTREQUEST_PROMPT_TEXT   121
#define IDS_REBOOTREQUEST_REBOOT_NOW    122
#define IDS_REBOOTREQUEST_REBOOT_LATER  123
#define IDS_PROCTERM_PROMPT_TEXT        124
#define IDS_PROCTERM_CANCEL_BUTTON_TEXT 125
#define IDS_PROCTERM_OK_BUTTON_TEXT     126
#define IDS_PROCTERM_MOREINFO_BUTTON_TEXT 127
#define IDS_PROCTERM_DONTASKAGAIN_TEXT  128
#define IDS_RISKALERT_TITLE             129
#define IDS_RISKALERT_BRIEF_DESC        130
#define IDS_RISKALERT_RISK_NAME         131
#define IDS_RISKALERT_RISK_CATEGORY     132
#define IDS_RISKALERT_PROMPT_TEXT       133
#define IDS_RISKALERT_ACTION_REMOVE     134
#define IDS_RISKALERT_ACTION_IGNORE_ONCE 135
#define IDS_RISKALERT_ACTION_IGNORE_ALWAYS 136
#define IDS_REBOOTREQUEST_HEIGHT        137
#define IDS_REBOOTREQUEST_WIDTH         138
#define IDI_TRAYICON_NORMAL             139
#define IDS_OEH_FEATURE_NAME            139
#define IDI_TRAYICON_ABNORMAL           140
#define IDS_PROCTERM_TITLE              140
#define IDI_TRAYICON_WORKING            141
#define IDI_TRAYICON_INFORMATION        142
#define IDI_TRAYICON_WARNING            143
#define IDI_TRAYICON_UNKNOWN            144
#define ID_TRAYMENU_OPENAVPRODUCT       50003
#define ID_TRAYMENU_OPENAVPRODUCTOPTIONS 50005
#define ID_ADDITIONALOPTIONS_CLOSE      50007
#define ID_TRAYMENU_ENABLEAUTOPROTECT   50008
#define ID_TRAYMENU_DISABLEAUTOPROTECT  50009
#define ID_ADDITIONALOPTIONS_SHOWBALLOONTEXT 50010
#define ID_TRAYMENU_VIEWRECENTHISTORY   50011
#define ID_ADDITIONALOPTIONS_SETNORMALSTATE 50012
#define ID_ADDITIONALOPTIONS_SETABNORMALSTATE 50013
#define ID_ADDITIONALOPTIONS_SETUNKNOWNSTATE 50014
#define ID_ADDITIONALOPTIONS_SETWORKINGSTATE 50015
#define ID_ADDITIONALOPTIONS_SETINFORMATIONSTATE 50016
#define ID_ADDITIONALOPTIONS_SETWARNINGSTATE 50017
#define ID_ADDITIONALOPTIONS_SENDTESTNOTIFICATION 50018
#define ID_ADDITIONALOPTIONS_SENDTESTALERT 50019

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         50020
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
