//      Copyright 1996 Symantec Corporation
/////////////////////////////////////////////////////////////////////
// $Header:   S:/NAVAPSVC/VCS/navaplog.cpv   1.2   13 May 1998 16:26:08   DALLEE  $
//
// Description:
//
//    Here is where we are going to put the activity log code into
//    the NAVAP Service.  It is much nicer here because it will be
//    easier to pull out when we go to a centralized Logging Service
//
//*** Hey, guess what? We did move to a centralized (sort of) alerting / logging
//    service. So now I nuked the contents of this file.
//    No longer being compiled/used in NAVAPSVC.
//
/////////////////////////////////////////////////////////////////////
//      $Log:   S:/NAVAPSVC/VCS/navaplog.cpv  $
// 
//    Rev 1.2   13 May 1998 16:26:08   DALLEE
// Removed all the guts. We're no longer using this file.
//
/////////////////////////////////////////////////////////////////////

