//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NAV_Roam.rc
//
#define MANIFEST_RESOURCE_ID              1

#define IDS_NO_ERROR                    1
#define IDS_ERROR                       2
#define IDS_NO_ERROR_STRING             3
#define IDS_NO_ERROR2                   4
#define IDS_FOUND_VIRUS                 5
#define IDS_MACHINE_ERROR               6
#define IDS_LAST_CHECK_IN               7
#define IDS_SERVER_CLIENT_IPADDRESS     8
#define IDS_SERVER_CLIENT_IPXADDRESS    9
#define IDS_SERVER_OFFLINE              10
#define IDS_REGKEY_CONFLICT             11
#define IDS_CONJURE_WORKED              12
#define IDS_CONJURE_FAILED              13
#define IDS_UNABLE_TO_GET_SERVER_INFO   14
#define IDS_CHILDREN_CALLBACK           15
#define IDS_CHILDREN_VALUE_CALLBACK     16
#define IDS_ADDING_CHILD_SERVER         17
#define IDS_ERROR_REASON                18
#define IDS_ERROR_CORRECTION_PASS       19
#define IDS_DOMAIN                      20
#define IDS_MASTER_SERVER               21
#define IDS_SERVER_AND_PARENT           22
#define IDS_NUM_CLIENTS                 23
#define IDS_CLIENTS_0_DAYS              24
#define IDS_CLIENTS_1_DAY               25
#define IDS_CLIENTS_2_DAYS              26
#define IDS_CLIENTS_3_DAYS              27
#define IDS_CLIENTS_4_DAYS              28
#define IDS_CLIENTS_5_TO_7_DAYS         29
#define IDS_CLIENTS_1_TO_2_WEEKS        30
#define IDS_OLD_CLIENTS                 31
#define IDS_CLIENTS_NO_ADDRESS          32
#define IDS_CLIENTS_WITH_IP             33
#define IDS_CLIENTS_WITH_IPX            34
#define IDS_NO_MASTER_FOUND             35
#define IDS_NUM_CHILD_SERVERS           36
#define IDS_CLIENTS_IN_DOMAIN           37
#define IDS_SERVERS_WITH_IP             38
#define IDS_SERVERS_WITH_IPX            39
#define IDS_DOMAINS_FOUND               40
#define IDS_LIVE_SERVERS_FOUND          41
#define IDS_OFFLINE_SERVERS_FOUND       42
#define IDS_DOMAINS_NO_MASTER           43
#define IDS_CLIENTS_FOUND               44
#define IDS_CHILDREN_ADDED              45
#define IDS_CONJURES_SUCCEEDED          46
#define IDS_CONJURES_FAILED             47
#define IDS_TOTAL_CLIENTS_0_DAYS        48
#define IDS_TOTAL_CLIENTS_1_DAY         49
#define IDS_TOTAL_CLIENTS_2_DAYS        50
#define IDS_TOTAL_CLIENTS_3_DAYS        51
#define IDS_TOTAL_CLIENTS_4_DAYS        52
#define IDS_TOTAL_CLIENTS_5_TO_7_DAYS   53
#define IDS_TOTAL_CLIENTS_1_TO_2_WEEKS  54
#define IDS_TOTAL_OLD_CLIENTS           55
#define IDS_TOTAL_CLIENTS_NO_ADDRESS    56
#define IDS_TOTAL_CLIENTS_WITH_IP       57
#define IDS_TOTAL_CLIENTS_WITH_IPX      58
#define IDS_TOTAL_SERVERS_WITH_IP       59
#define IDS_TOTAL_SERVERS_WITH_IPX      60
#define IDS_TOTAL_MANAGEABLE            61
#define IDS_ERROR_OPENING_KEY           62
#define IDS_SETTING_REGKEY              63
#define IDS_SET_LOCAL_KEY_VALUE         64
#define IDS_DELETING_LOCAL_KEY          65
#define IDS_ERROR_SETTING_ROAMING_KEYS  66
#define IDS_SET_SERVER_KEY_VALUE        67
#define IDS_DELETE_VALUE_OK             68
#define IDS_ERROR_DELETING_ROAMING_KEY  69
#define IDS_DELETE_VALUE_ON_SERVER_KEY  70
#define IDS_ERROR_OPENING_IMPORT_FILE   71
#define IDS_ERROR_OPENING_EXPORT_FILE   72
#define IDS_FUNCTION_FAILED             73
#define IDS_FUNCTION_FAILED_WITH_HRESULT 74
#define IDS_STARTDRIVER_ERROR           75
#define IDS_SAV_NOT_MANAGED             76
#define IDS_ERROR_RETRIEVING_LU_FILE    77
#define IDS_ERROR_CREATING_GRC          78
#define IDS_ERROR_RETRIEVING_GRC        79
#define IDS_ERROR_RETRIEVING_GRC_PATH   80
#define IDS_SAV_NOT_RUNNING             81
#define IDS_ERROR_CREATING_TO_SET_PARENT 82
#define IDS_SAV_NOT_USING_AMS           83
#define IDS_SAV_NOT_RUNNING_WITH_AMS    84
#define IDS_LOCAL_MACHINE_STARTS_WITH_SERVER 85
#define IDS_NO_REGIONAL_SERVERS_FOR_TYPE 86
#define IDS_TIME_SERVER_LEVEL_DELAY     87
#define IDS_FAILED_TIME_SERVER_LEVEL_DELAY 88
#define IDS_SERVER_AVG_TIME             89
#define IDS_SERVER_QUICKER_AVG_TIME     90
#define IDS_RANDOM_RESULTS              91
#define IDS_DIDNT_FIND_PARENT           92
#define IDS_SERVER_AVG_TIME_ALL         94
#define IDS_NEAREST_PARENT              95
#define IDS_PARENT_OWNS_CLIENT          96
#define IDS_PARENT_HAS_NOT_TAKEN_OVER   97
#define IDS_PARENT_OWNS_QUARANTINE_CLIENT 98
#define IDS_PARENT_OWNS_GRC_CLIENT      99
// Do not use IDS 100 -- special value for RTVScan which also includes these resources.
#define IDS_NEAREST_PRIMARY             101
#define IDS_PRIMARY_OWNS_MACHINE        102
#define IDS_PRIMARY_HAS_NOT_TAKEN_OVER  103
#define IDS_PARENT_OWNS_ALERTS_CLIENT   104
#define IDS_PARENT_HAS_NOT_TAKEN_OVER_ALERTS_CLIENT 105
#define IDS_PARENT_IS_FINE              106
#define IDS_PROBLEM_WITH_PARENT         107
#define IDS_ERROR_INSTALLING            108
#define IDS_INSTALLED                   109
#define IDS_FUNCTION_FAILED_TEXT        110
#define IDS_STOPPING_SERVICE            111
#define IDS_ERROR_STOPPING_SERVICE      112
#define IDS_SERVICE_STOPPED             113
#define IDS_SERVICE_REMOVED             114
#define IDS_DEBUGGING_SERVICE           115
#define IDS_INSTALLING_TO_PATH          116
#define IDS_INSTALLING_AS_SERVICE       117
#define IDS_INSTALLING_AS_EXE           118
#define IDS_REMOVING_AS_SERVICE         119
#define IDS_UNABLE_TO_START             120
#define IDS_PARENT_OWNS_ITA_CLIENT      121
#define IDS_PARENT_HAS_NOT_TAKEN_OVER_ITA_CLIENT 122
#define IDS_PARENT_OWNS_ESM_CLIENT      123
#define IDS_PARENT_HAS_NOT_TAKEN_OVER_ESM_CLIENT 124
#define IDS_ERROR_RETRIEVING_ITA        125
#define IDS_ERROR_RETRIEVING_ITA_PATH   126
#define IDS_ERROR_STARTING_ITA          127
#define IDS_ERROR_RETRIEVING_ESM_PROXY  128
#define IDS_ERROR_RETRIEVING_ESM_REG    129
#define IDS_SAVROAM_HELP                130
#define IDS_ERROR_WINDOWS_VERSION       131
#define IDS_ERROR_LIBRARY_FUNCTIONS     132
#define IDS_ERROR_LOADING_LIBRARY       133
#define IDS_ERROR_REG_WNDCLASS          134
#define IDS_ERROR_RETRIEVING_ESM_PATH   134
#define IDS_SERVICE_ALREADY_RUNNING     135
#define IDS_ERROR_STARTING_SERVICE      136
#define IDS_ERROR_LAUNCHING_ESM_REG     137
#define IDS_ERROR_STARTING_SAV          138
#define IDS_ERROR_STARTING_SAV_FOR_GRC  139
#define IDS_ROAMADMN_HELP               140
#define IDS_SERVICE_STARTED             141
#define IDS_ERROR_STARTING              142
#define IDS_ERROR_NO_SERVER_LIST        143
#define IDS_ERROR_PARSING_LINE          144
#define IDS_NO_SERVER_LIST              145
#define IDS_EXPORT_SERVERLIST           145
#define IDS_INVALID_EXTENSION           146
#define IDS_ERROR_FIND_PARENT           147
#define IDS_COMM_ERROR_SETTING_ROAMING_KEYS 148
#define IDS_DELAYTIMEONSUCESS           149
#define IDS_DELAYTIMEONFAILURE          150
#define IDS_ERROR_RETRIEVING_ITA_TOKENTXT 151
#define IDS_ERROR_RETRIEVING_ITA_TOKGENEXE 152
#define IDS_ERROR_LAUNCHING_ITA_REG     153
#define IDS_ERROR_LAUNCHING_ITA_TOKGENEXE 154
#define IDS_ERROR_LAUNCHING_ITA_AGTCFGEXE 155
#define IDS_ERROR_RETRIEVING_ITA_AGTCFGEXE 156
#define IDS_CREATE_PROCESS_RESULT       157
#define IDS_REMOTE_COPY_FILE_RESULT     158
#define IDS_ERROR_STOPPING_ITA_ROAM     159
#define IDS_ERROR_REQUIRED_NETWORK_NOT_PRESENT 160
#define IDS_SCM_DESCRIPTION             161
#define IDS_FORCING_NEW_PARENT          162
#define IDS_PARENT_HAS_NOT_TAKEN_OVER_GRC_CLIENT 163

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
