//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ScanMgr.rc
//
#define IDS_REMOVE_MIME                 2
#define IDS_LOG_SCAN_START              3
#define IDS_LOG_SCAN_ABORT              4
#define IDS_LOG_SCAN_ERROR              5
#define IDS_LOG_SCAN_COMPLETE           6
#define IDS_LOG_FILE_REPAIRED           7
#define IDS_LOG_FILE_QUAR               8
#define IDS_LOG_FILE_DELETED            9
#define IDS_LOG_FILE_REPAIR_FAILED      10
#define IDS_LOG_FILE_QUAR_FAILED        11
#define IDS_LOG_FILE_DELETE_FAILED      12
#define IDS_LOG_BOOTREC_REPAIRED        13
#define IDS_LOG_BOOTREC_REPAIR_FAILED   14
#define IDS_LOG_MBR_REPAIRED            15
#define IDS_LOG_MBR_REPAIR_FAILED       16
#define IDS_GSE_SCAN_TEXT               17
#define IDS_DISPLAY_MBR                 18
#define IDS_DISPLAY_MBR_FULL            19
#define IDS_DISPLAY_BOOTREC             20
#define IDS_DISPLAY_BOOTREC_FULL        21
#define IDS_DISPLAY_FILE_FULL           22
#define IDS_DISPLAY_EMAIL_PREFIX        23
#define IDS_DISPLAY_COMPRESSED_PREFIX   24
#define IDS_DISPLAY_COMPRESSED_POSTFIX  25
#define IDS_WITHIN                      26
#define IDS_ERROR_DISK_FULL             27
#define IDS_REVERSE_COMPRESS_STRING_FLAG 28
#define IDS_LOG_OEH_VIRUSNAME           29
#define IDS_INSUFFICIENT_DISK_SPACE     30
#define IDS_DISPLAY_NONVIRAL_FILE_FULL  31
#define IDS_DISPLAY_NONVIRAL_COMPRESSED_POSTFIX 32
#define IDS_DEF_AUTHENTICATION_FAILURE  33
#define IDS_DISPLAY_REGKEY_PREFIX       33
#define IDS_DISPLAY_STARTUPFOLDER_PREFIX 34
#define IDS_DISPLAY_BATCH_PREFIX        35
#define IDS_DISPLAY_INIFILE_PREFIX      36
#define IDS_ERROR_DEFINITIONS           37
#define IDS_ERROR_DEFINITIONS_NO_FILE   38
#define IDS_DISPLAY_SE_LEFT_INTACT      39
#define IDS_DISPLAY_SE_UNHANDLED        40
#define IDS_DISPLAY_SE_MEMORY_REMAINING 41
#define IDS_POSTREBOOTREMEDIATION_ERROR_REBOOT_REQUIRED 42
#define IDS_STRING43                    43
#define IDS_POSTREBOOTREMEDIATION_ERROR_FILE_STILL_PRESENT 43
#define IDS_LOG_PROCESS_TERMINATE_ATTEMPT 44
#define IDS_LOG_PROCESS_TERMINATE_ATTEMPT_TITLE 45
#define IDS_LOG_PROCESS_TERMINATE_RESULT_TITLE 46
#define IDS_LOG_PROCESS_TERMINATE_SUCCEEDED 47
#define IDS_LOG_PROCESS_TERMINATE_FAILED 48
#define IDS_ERR_DEFS_REVERTED           49
#define IDS_ERR_DEFS_NOT_AUTHENTIC      50
#define IDS_MIME_REPLACEMENT_TEXT       51
#define IDS_GSE_DOT_ANIMATION_TO_DISPLAY_IN_COMMON_UI 55
#define IDS_DISPLAY_MEMORY_INFECTION    56
#define IDS_DISPLAY_MEMORY_INFECTION_FULL 57
#define IDS_DISPLAY_MEMORY_INFECTION_DESCRIPTION 57
#define IDS_PROCESSES                   58
#define IDS_REPAIRED                    58
#define IDS_FILES                       59
#define IDS_REPAIR_FAILED               59
#define IDS_REGKEYS                     60
#define IDS_TERMINATED                  60
#define IDS_SERVICES                    61
#define IDS_LOW                         61
#define IDS_COMOBJECTS                  62
#define IDS_MEDIUM                      62
#define IDS_INIFILES                    63
#define IDS_HIGH                        63
#define IDS_UNKOWN_TEXT                 64
#define IDS_MBRS                        65
#define IDS_DEFAULT_REGISTRY_KEY_TEXT   65
#define IDS_BOOTRECORDS                 66
#define IDS_LOG_AFFECTED_UNKNOWN        66
#define IDS_GSE_DELAYED_TEXT            67
#define IDS_LOG_AFFECTED_FILES          68
#define IDS_LOG_AFFECTED_PROCS          69
#define IDS_LOG_AFFECTED_BRS            70
#define IDS_LOG_AFFECTED_MBRS           71
#define IDS_LOG_AFFECTED_REGKEYS        72
#define IDS_LOG_AFFECTED_BATCH          73
#define IDS_LOG_AFFECTED_INI            74
#define IDS_LOG_AFFECTED_SERVICES       75
#define IDS_LOG_AFFECTED_COM            76
#define IDS_LOG_STATUS_SUCCESS          77
#define IDS_LOG_STATUS_FAIL             78
#define IDS_LOG_STATUS_NOTFOUND         79
#define IDS_LOG_STATUS_REPAIRED         80
#define IDS_LOG_STATUS_DELETED          81
#define IDS_LOG_STATUS_DEFAULT          82
#define IDS_LOG_SOURCE_MANUAL           83
#define IDS_LOG_SOURCE_EMAIL            84
#define IDS_LOG_SOURCE_IM               85
#define IDS_LOG_SOURCE_OFFICE           86
#define IDS_LOG_DESCRIPTION_HEADER_NOT_HANDLED 87
#define IDS_LOG_DESCRIPTION_HEADER_HANDLED 88
#define IDS_REBOOT_REQUIRED             89
#define IDS_DELETED                     90
#define IDS_OPERATION_FAILED            91
#define IDS_QUARANTINE_FAILED           92
#define IDS_DELETE_FAILED               93
#define IDS_EXCLUDE_FAILED              94
#define IDS_QUARANTINED                 95
#define IDS_EXCLUDED                    96
#define IDS_DETECTED                    97
#define IDS_NOACTION_TAKEN              98
#define IDS_ACCESS_DENIED               99
#define IDS_NOT_DETECTED                100
#define IDS_NOACTION_REQUIRED           101

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
