//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WProtect32.rc
//
#define MANIFEST_RESOURCE_ID            1
#define IDC_HELP_BUTTON                 9
#define IDS_ERROR_REG_FAIL              46
#define IDS_ERROR_SERVICE_HUNG          47
#define IDS_ERROR_UNKNOWN               48
#define IDS_DELETE_TASK                 49
#define IDS_WRONG_PASSWORD              50
#define IDS_SCAN_DIALOGS_ERROR          51
#define IDS_ERROR_NO_OPEN               52
#define IDS_ERROR_STARTUP_SCANS         53
#define IDS_TRANSLATION_NOTE1           98
#define IDS_TRANSLATION_NOTE2           99
#define IDD_SCHEDULE_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDR_WPROTETYPE                  129
#define IDS_STAT_BAR_SCANNING           129
#define IDB_OBJECTS                     130
#define IDS_WARNING_DIR_NOT_ADDED       130
#define IDD_DEFAULT                     131
#define IDS_SCAN_COMPLETE               131
#define IDB_INTEL                       132
#define IDS_INVALID_SETTINGS            132
#define IDB_SPLASH                      133
#define IDS_ERROR_TASK_EXISTS           133
#define IDD_TASK_OCX_HELPER             134
#define IDS_CUSTOM_TASK_SAVE_ERROR      134
#define IDS_LOADING_TASK                135
#define IDD_SCRIPTED_TASK               136
#define IDS_VIRUS_ENCYCLOPEDIA          136
#define IDS_GROUP_SCHEDULED_TASKS       137
#define IDD_RECORD_VIEW                 137
#define IDS_STOP_CURRENT_SCAN           138
#define IDM_POPUP                       138
#define IDS_NEW_TASK                    139
#define IDS_LOCKED_OPTION               139
#define IDS_SERVICE_CANT_START          140
#define IDS_PATTERN_PROMPT_RUNSILENT_LICENSED 141
#define IDS_COUNTING_NUM_QUARANTINE_ITEMS 142
#define IDB_MAINSCRN                    157
#define IDB_NEWSCAN                     158
#define IDB_ABOUT                       159
#define IDD_UNLOAD                      161
#define IDB_LOCKS                       162
#define IDD_CONFIGURE_SNAPIN            162
#define IDD_PASSWORD                    168
#define IDI_LDVPWARNING                 171
#define IDS_NEW_SCRIPTED                172
#define IDS_NEW_SCHEDULED               173
#define IDS_SCHEDULE_TAB_HOURLY         174
#define IDI_SCHEDULE_ICON               174
#define IDS_SCHEDULE_TAB_DAILY          175
#define IDD_SCHEDULE_ENABLE_DIALOG      175
#define IDS_SCHEDULE_TAB_WEEKLY         176
#define IDB_NONE                        176
#define IDS_SCHEDULE_TAB_MONTHLY        177
#define IDB_ASCENDING                   177
#define IDS_LDVP_TITLE                  178
#define IDB_DESCENDING                  178
#define IDS_ACTION_CLEANED              179
#define IDS_HELP_CONTENTS               180
#define IDS_HELP_CONTENTS_DESCRIPTION   181
#define IDS_HELP_INDEX                  182
#define IDS_HELP_INDEX_DESCRIPTION      183
#define IDS_NEW_STARTUP                 184
#define IDS_NEW_STARTUP_TITLE           185
#define IDS_TIME_STRING                 186
#define IDS_CANCEL_RECORD               187
#define IDS_NO_WHATS_THIS_HELP          188
#define IDS_ERROR_EMPTY_TASKNAME        189
#define IDS_NO_LOAD_OCX                 190
#define IDS_NO_LDVPTASK                 191
#define IDS_NOT_READY                   192
#define IDS_ERROR_DOWNLOAD_PATTERN      193
#define IDS_ENGINE_MEMORY_ERROR         194
#define IDS_ENGINE_NO_PATTERN_FILE      195
#define IDS_ENGINE_NO_ENGINE            196
#define IDS_ENABLED                     211
#define IDS_DISABLED                    212
#define IDS_GROUP_VIEW                  213
#define IDS_NEW_STARTUP_TASK            214
#define IDS_NEW_SCRIPTED_TASK           215
#define IDS_NEW_SCHEDULED_TASK          216
#define IDS_CONFIG_TASK_DESCRIPTION     217
#define IDS_REALTIME_PROTECTION         218
#define IDS_IDLE_PROTECTION             219
#define IDS_GROUP_SCAN                  220
#define IDS_ENGINE_FAILER               250
#define IDS_ERR_CREATE_TASKPAD          251
#define IDS_DEFTASK_FAVORITES           252
#define IDS_DEFTASK_STARTUP             253
#define IDS_DEFTASK_HELP                254
#define IDS_DEFTASK_SCRIPTED            255
#define IDS_GROUP_CONFIGURE             256
#define IDS_SCAN_FAILED                 257
#define IDS_SCANNING_MEMORY             258
#define IDS_SCANNING_BOOT               259
#define IDS_INIT_SCANNING               260
#define IDS_AC_MOVE                     261
#define IDS_AC_RENAME                   262
#define IDS_AC_DELETE                   263
#define IDS_AC_NOTHING                  264
#define IDS_AC_BAD                      265
#define IDS_AC_CLEAN                    266
#define IDS_ENGINE_WRONG_VERSION        267
#define IDC_SCHEDULE                    633
#define IDC_STORAGE_VIEW                652
#define IDC_TASK_FS                     1006
#define IDC_TITLE                       1007
#define IDC_NAME                        1007
#define IDC_SCAN_ENGINE_VERSION         1008
#define IDC_TASK_DESCRIPTION            1008
#define IDC_PATTERN_FILE_VERSION        1009
#define IDC_SCAN_LIST                   1009
#define IDC_NEXT                        1010
#define IDC_PLACE_HOLDER                1011
#define IDC_TEXT                        1017
#define IDC_LICENSE_NUMBER              1017
#define IDC_CLIENT_GROUP                1018
#define IDC_PARENT_SERVER               1019
#define IDC_REALTIME_STATUS             1020
#define IDC_LOAD_SERVICES               1021
#define IDC_WELCOME                     1022
#define IDC_EXIT                        1024
#define IDC_CLOSE                       1025
#define IDC_PRODUCT_VERSION             1029
#define IDC_REGISTER                    1031
#define IDC_CLIGROUP_TEXT               1032
#define IDC_DOMAIN_TEXT                 1033
#define IDC_DOMAIN                      1034
#define IDC_PASSWORD                    1035
#define IDC_PARENT_TEXT                 1035
#define IDC_COUNT_TEXT                  2006
#define IDC_DISCLAIMER                  2007
#define IDC_LINE1                       2008
#define IDC_LINE2                       2009
#define IDC_LINE3                       2010
#define IDC_DISCLAIMER2                 2011
#define IDC_IMAGE                       2017
#define ID_STATIC                       2019
#define IDC_ENABLE_SCHEDULING           2020
#define IDC_SCHEDULE_DESCRIPTION        2023
#define IDC_QUARANTINE_ITEMS            2024
#define IDC_USERNAME                    2032
#define IDS_VIRUSES_SEARCH              5000
#define IDS_VIRUSES_SEARCH_DESCRIPT     5001
#define IDS_VIRUSES_0                   5002
#define IDS_VIRUSES_0_DESCRIPT          5003
#define IDS_VIRUSES_A                   5004
#define IDS_VIRUSES_A_DESCRIPT          5005
#define IDS_VIRUSES_B                   5006
#define IDS_VIRUSES_B_DESCRIPT          5007
#define IDS_VIRUSES_C                   5008
#define IDS_VIRUSES_C_DESCRIPT          5009
#define IDS_VIRUSES_C_DESCRIPTION       5009
#define IDS_VIRUSES_D                   5010
#define IDS_VIRUSES_D_DESCRIPT          5011
#define IDS_VIRUSES_E                   5012
#define IDS_VIRUSES_E_DESCRIPT          5013
#define IDS_VIRUSES_E_DESCRIPTION       5013
#define IDS_VIRUSES_F                   5014
#define IDS_VIRUSES_F_DESCRIPT          5015
#define IDS_VIRUSES_G                   5016
#define IDS_VIRUSES_G_DESCRIPT          5017
#define IDS_VIRUSES_G_DESCRIPTION       5017
#define IDS_VIRUSES_H                   5018
#define IDS_VIRUSES_H_DESCRIPT          5019
#define IDS_VIRUSES_I                   5020
#define IDS_VIRUSES_I_DESCRIPT          5021
#define IDS_VIRUSES_I_DESCRIPTION       5021
#define IDS_VIRUSES_J                   5022
#define IDS_VIRUSES_J_DESCRIPT          5023
#define IDS_VIRUSES_K                   5024
#define IDS_VIRUSES_K_DESCRIPT          5025
#define IDS_VIRUSES_K_DESCRIPTION       5025
#define IDS_VIRUSES_L                   5026
#define IDS_VIRUSES_L_DESCRIPT          5027
#define IDS_VIRUSES_M                   5028
#define IDS_VIRUSES_M_DESCRIPT          5029
#define IDS_VIRUSES_N                   5030
#define IDS_VIRUSES_N_DESCRIPT          5031
#define IDS_VIRUSES_O                   5032
#define IDS_VIRUSES_O_DESCRIPT          5033
#define IDS_VIRUSES_P                   5034
#define IDS_VIRUSES_P_DESCRIPT          5035
#define IDS_VIRUSES_P_DESCRIPTION       5035
#define IDS_VIRUSES_Q                   5036
#define IDS_VIRUSES_Q_DESCRIPT          5037
#define IDS_VIRUSES_R                   5038
#define IDS_VIRUSES_R_DESCRIPT          5039
#define IDS_VIRUSES_R_DESCRIPTION       5039
#define IDS_VIRUSES_S                   5040
#define IDS_VIRUSES_S_DESCRIPT          5041
#define IDS_VIRUSES_S_DESCRIPTION       5041
#define IDS_VIRUSES_T                   5042
#define IDS_VIRUSES_T_DESCRIPT          5043
#define IDS_VIRUSES_U                   5044
#define IDS_VIRUSES_U_DESCRIPT          5045
#define IDS_VIRUSES_U_DESCRIPTION       5045
#define IDS_VIRUSES_V                   5046
#define IDS_VIRUSES_V_DESCRIPT          5047
#define IDS_VIRUSES_W                   5048
#define IDS_VIRUSES_W_DESCRIPT          5049
#define IDS_VIRUSES_W_DESCRIPTION       5049
#define IDS_VIRUSES_X                   5050
#define IDS_VIRUSES_X_DESCRIPT          5051
#define IDS_VIRUSES_Y                   5052
#define IDS_VIRUSES_Y_DESCRIPT          5053
#define IDS_VIRUSES_Y_DESCRIPTION       5053
#define IDS_VIRUSES_Z                   5054
#define IDS_VIRUSES_Z_DESCRIPT          5055
#define IDS_VIRUSES_Z_DESCRIPTION       5055
#define ID_SCAN                         32771
#define ID_VIRUS_ENCYCLOPEDIA           32772
#define ID_UPDATE                       32773
#define ID_REPORT                       32774
#define ID_RECORD_NEW                   32779
#define ID_FILE_SCANNING                32780
#define ID_REALTIME_SCANNING            32781
#define ID_STARTUP_SCANNING             32782
#define ID_SCHEDULED_SCANNING           32783
#define ID_DEFAULT_ACTIONS              32784
#define ID_ALERTS                       32785
#define ID_OPTIONS                      32786
#define IDM_TASK_DELETE                 32787
#define ID_NEW_SCHEDULED                32788
#define IDM_CONTENTS                    32789
#define IDM_SEARCH                      32790
#define IDM_VIRUS_ENCYCLOPEDIA          32791
#define ID_RECORD_STARTUP               32792
#define ID_NEW_STARTUP                  32793
#define ID_CUT                          32794
#define ID_PASTE                        32795
#define IDC_UPDATE_PATTERNFILE          32796
#define IDM_EDIT                        32797
#define IDM_CONFIG_HISTORY              32798
#define IDC_SCHEDULE_UPDATES            32799
#define IDM_VIRUSLIST                   32800
#define IDS_ERROR_NO_OPEN_SCHEDULE      61447
#define IDS_UPDATE_DAILY                61448
#define IDS_UPDATE_WEEKLY               61449
#define IDS_UPDATE_MONTHLY              61450
#define IDS_NUM_QUARANTINE_ITEMS        61451
#define IDS_ONE_QUARANTINE_ITEM         61452
#define IDS_QUARANTINE_REPAIR           61453
#define IDS_QUARANTINE_RESTORE          61454
#define IDS_UPDATE_DAILY_RANDOM         61455
#define IDS_UPDATE_WEEKLY_RANDOM        61456
#define IDS_UPDATE_MONTHLY_RANDOM       61457
#define IDS_INVALID_DEFINITION_SET      61458
#define IDS_INVALID_APP_PATH            61459
#define IDS_TUESDAY                     61460
#define IDS_WEDNESDAY                   61461
#define IDS_THURSDAY                    61462
#define IDS_FRIDAY                      61463
#define IDS_SATURDAY                    61464
#define IDS_SUNDAY                      61465
#define IDS_PATTERN_PROMPT_WEEK_AND_DAY_RANDOM 61466
#define IDS_PATTERN_PROMPT_MONTH_AND_DAY_RANDOM 61467
#define IDS_PATTERN_PROMPT_RANDOM_WEEKDAY 61468
#define IDS_PATTERN_PROMPT_RANDOM_MONTHDAY 61469
#define IDS_MONDAY                      61470
#define IDS_ERROR_CANT_START_LIVEUPDATE 61471
#define IDS_UNLOAD_SERVICE              61472
#define IDS_LOAD_SERVICE                61473
#define IDS_INSTALL_REBOOT_REQUIRED     61474
#define IDS_SAVRT32_DLL                 61475
#define IDS_NO_ADMIN_PRIVS              61476
#define IDS_PATTERN_PROMPT_RUNSILENT    61477
#define IDS_LIVEUPDATE                  61478

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        181
#define _APS_NEXT_COMMAND_VALUE         32801
#define _APS_NEXT_CONTROL_VALUE         2033
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
