#!/bin/sh

for dir in symkunix heur avenge emulator engine15 crc32 df macroheu olessapi navex15 cmdline navapi
do
    echo Making $dir
    cd $dir
    make -f unix.mak $1 >make.err 2>&1
    echo "    errors:   `grep error make.err | wc -l`"
    echo "    warnings: `grep warning make.err | wc -l`"
    cd ..
done
