del "c:\program files\common files\symantec shared\ccApp-DefAlert.exe"
del "c:\program files\common files\symantec shared\ccApp-avpapp32.exe"
del "c:\program files\common files\symantec shared\ccApp-AppCrPlg.exe"
del "c:\program files\common files\symantec shared\ccApp-ISLAlert.exe"
del "c:\program files\common files\symantec shared\ccApp-NisTray.exe"
del "c:\program files\common files\symantec shared\ccApp-NPCTray.exe"
del "c:\program files\common files\symantec shared\ccApp-ccEmlPxy.exe"
del "c:\program files\common files\symantec shared\ccApp-ccAlert.exe"
del "c:\program files\common files\symantec shared\ccApp-fwAlert.exe"

copy "c:\program files\common files\symantec shared\ccApp.exe" "c:\program files\common files\symantec shared\ccApp-DefAlert.exe"
copy "c:\program files\common files\symantec shared\ccApp.exe" "c:\program files\common files\symantec shared\ccApp-avpapp32.exe"
copy "c:\program files\common files\symantec shared\ccApp.exe" "c:\program files\common files\symantec shared\ccApp-AppCrPlg.exe"
copy "c:\program files\common files\symantec shared\ccApp.exe" "c:\program files\common files\symantec shared\ccApp-ISLAlert.exe"
copy "c:\program files\common files\symantec shared\ccApp.exe" "c:\program files\common files\symantec shared\ccApp-NisTray.exe"
copy "c:\program files\common files\symantec shared\ccApp.exe" "c:\program files\common files\symantec shared\ccApp-NPCTray.exe"
copy "c:\program files\common files\symantec shared\ccApp.exe" "c:\program files\common files\symantec shared\ccApp-ccEmlPxy.exe"
copy "c:\program files\common files\symantec shared\ccApp.exe" "c:\program files\common files\symantec shared\ccApp-ccAlert.exe"
copy "c:\program files\common files\symantec shared\ccApp.exe" "c:\program files\common files\symantec shared\ccApp-fwAlert.exe"
pause
