//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by navapsvcres.rc
//
#define IDS_SERVICENAME                 100
#define IDS_DISPLAYNAME                 101
#define IDS_UNKNOWN_USER                102
#define IDS_SERVICE_DESC                103
#define IDS_ERROR_SAVRT_NAVEX_INTERFACE 104
#define IDS_ERROR_SAVRT_UNKNOWN         105
#define IDS_NAVAP_VIR_MSG_WAS_INFECTED  2000
#define IDS_NAVAP_VIR_MSG_IS_INFECTED   2001
#define IDS_NAVAP_VIR_MSG_BOOT_WAS_INFECTED 2002
#define IDS_NAVAP_VIR_MSG_BOOT_IS_INFECTED 2003
#define IDS_NAVAP_VIR_MSG_MBR_WAS_INFECTED 2004
#define IDS_NAVAP_VIR_MSG_MBR_IS_INFECTED 2005
#define IDS_NAVAP_VIR_ACT_ACCESS_DENIED 2006
#define IDS_NAVAP_VIR_ACT_NONE          2007
#define IDS_NAVAP_VIR_ACT_MBR_REPAIRED  2008
#define IDS_NAVAP_VIR_ACT_MBR_NOT_REPAIRED 2009
#define IDS_NAVAP_VIR_ACT_BOOTREC_REPAIRED 2010
#define IDS_NAVAP_VIR_ACT_BOOTREC_NOT_REPAIRED 2011
#define IDS_NAVAP_VIR_ACT_REPAIRED      2012
#define IDS_NAVAP_VIR_ACT_NOT_REPAIRED  2013
#define IDS_NAVAP_VIR_ACT_DELETED       2014
#define IDS_NAVAP_VIR_ACT_NOT_DELETED   2015
#define IDS_NAVAP_VIR_ACT_QUARANTINED   2016
#define IDS_NAVAP_VIR_ACT_NOT_QUARANTINED 2017
#define IDS_NAVAP_VIR_UNKNOWN_ACTION    2018

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
