//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NAVLogVRes.rc
//
#define IDS_COLUMN_DATE                 1
#define IDS_COLUMN_USER_NAME            2
#define IDS_COLUMN_COMPUTER_NAME        3
#define IDS_COLUMN_ERROR_CODE           4
#define IDS_COLUMN_ERROR_MESSAGE        5
#define IDS_CATEGORY_DESC_ERRORS        6
#define IDS_CATEGORY_NAME_ERRORS        7
#define IDS_COLUMN_FEATURE              8
#define IDS_CATEGORY_NAME_VIRUS_ALERT   9
#define IDS_COLUMN_VIRUS_NAME           10
#define IDS_COLUMN_ACTION               11
#define IDS_COLUMN_FILE_PATH            12
#define IDS_COLUMN_ITEM_TYPE            13
#define IDS_CATEGORY_DESC_VIRUS_ALERT   14
#define IDS_ACTION_ACCESS_DENIED        15
#define IDS_ACTION_ALLOWED              16
#define IDS_ACTION_INFECTED             17
#define IDS_ACTION_HTML                 17
#define IDS_ACTION_BLOCKED              18
#define IDS_ACTION_AUTHORIZED           19
#define IDS_ACTION_REPAIRED             20
#define IDS_ACTION_REPAIR_FAILED        21
#define IDS_ACTION_QUARANTINED          22
#define IDS_ACTION_QUARANTINE_FAILED    23
#define IDS_ACTION_DELETED              24
#define IDS_ACTION_DELETE_FAILED        25
#define IDS_ACTION_BLOCK_FAILED         26
#define IDS_ACTION_AUTHORIZE_FAILED     27
#define IDS_ACTION_NO_ACTION            28
#define IDS_ACTION_EXCLUDED             29
#define IDS_ACTION_EXCLUDE_FAILED       30
#define IDS_ACTION_SHUTDOWN             31
#define IDS_ACTION_UNKNOWN              32
#define IDS_COLUMN_DEFS_REVISION        33
#define IDS_COLUMN_PRODUCT_VERSION      34
#define IDS_ACTION_RESTORED             35
#define IDS_FEATURE_NAVLNCH             36
#define IDS_FEATURE_STATUS              37
#define IDS_FEATURE_OPTIONS_UI          38
#define IDS_FEATURE_LU_CALLBACK         39
#define IDS_FEATURE_SCAN_AND_DELIVER    40
#define IDS_FEATURE_SCRIPT_BLOCKING_UI  41
#define IDS_FEATURE_INFO_WIZARD         42
#define IDS_FEATURE_DEF_ALERT           43
#define IDS_TEXT_THREAT_CAT             44
#define IDS_HTML_THREAT_CAT             45
#define IDS_SCAN_FILES_EXCLUDED         46
#define IDS_SCAN_ACTION_MEMORY          47
#define IDS_ITEM_TYPE_MEMORY            48
#define IDS_ACTION_TEXT                 49
#define IDS_ITEM_TYPE_FILE              50
#define IDS_ITEM_TYPE_BR                51
#define IDS_ITEM_TYPE_MBR               52
#define IDS_ITEM_TYPE_UNKNOWN           53
#define IDS_FEATURE_UNKNOWN             54
#define IDS_COLUMN_APPLICATION          55
#define IDS_COLUMN_TARGET               55
#define IDS_ACTION_HD_FORMAT            56
#define IDS_ACTION_HD_MBR_WRITE         57
#define IDS_ACTION_HD_BOOT_WRITE        58
#define IDS_ACTION_FD_BOOT_WRITE        59
#define IDS_COLUMN_ACTION_ATTEMPTED     60
#define IDS_ITEM_SCRIPT                 61
#define IDS_FEATURE_AP                  62
#define IDS_FEATURE_SCANNER             63
#define IDS_CATEGORY_APPLICATION        64
#define IDS_COLUMN_DETAILS              65
#define IDS_CATEGORY_DESC_APP           66
#define IDS_SCAN_ACTION_STARTED         67
#define IDS_SCAN_ACTION_ABORTED         68
#define IDS_SCAN_ACTION_COMPLETED       69
#define IDS_SCAN_MBR_INFECTED           70
#define IDS_SCAN_MBR_REPAIRED           71
#define IDS_SCAN_BR_INFECTED            72
#define IDS_SCAN_BR_REPAIRED            73
#define IDS_SCAN_FILES_INFECTED         74
#define IDS_SCAN_FILES_REPAIRED         75
#define IDS_SCAN_FILES_QUARANTINED      76
#define IDS_SCAN_FILES_DELETED          77
#define IDS_SCAN_SEPARATOR              78
#define IDS_HTML_HEADER                 79
#define IDS_HTML_FOOTER                 80
#define IDS_FEATURE_OFFICEAV            81
#define IDS_FEATURE_QUARANTINE          82
#define IDS_SARC_WEBSITE                83
#define IDS_ERROR_LINK                  84
#define IDS_LANGUAGE                    85
#define IDS_BUILDTYPE                   86
#define IDS_SCAN_DETAILS                87
#define IDS_TEXT_SCAN_DETAILS           87
#define IDS_SCAN_FILES_SCANNED          88
#define IDS_SCAN_MBR_SCANNED            89
#define IDS_SCAN_BR_SCANNED             90
#define IDS_HTML_BREAK                  91
#define IDS_TEXT_DELIMITER              92
#define IDS_FEATURE_AP_DRIVER           93
#define IDS_SCAN_TIME                   94
#define IDS_HTML_SCAN_DETAILS           95
#define IDS_HTML_TABLE_START            96
#define IDS_HTML_TABLE_STOP             97
#define IDS_HTML_TABLE_ENTRY_START      98
#define IDS_HTML_TABLE_ENTRY_STOP       99
#define IDS_HTML_SOURCE                 100
#define IDS_TEXT_SOURCE                 101
#define IDS_NOT_APPLICABLE              102
#define IDS_ACTION_ALLOWED_METHOD       103
#define IDR_STYLESHEET                  103
#define IDS_HTML_DESCRIPTION            104
#define IDS_TEXT_DESCRIPTION            105
#define IDS_ACTION_AUTODELETE           106
#define IDS_TECHSUPPORT_URL             107
#define IDS_SB_VIRUS_NAME               108
#define IDS_ACTION_REMOVED              109
#define IDS_COLUMN_ACTION_TAKEN         110
#define IDS_HTML_THREAT_MATRIX_OVERALL  112
#define IDS_HTML_MARGINLEFT_SPAN_BEGIN  113
#define IDS_HTML_SPAN_END               114
#define IDS_TEXT_THREAT_MATRIX_OVERALL  117
#define IDS_TEXT_THREAT_MATRIX_PERFORMANCE 118
#define IDS_TEXT_THREAT_MATRIX_PRIVACY  119
#define IDS_TEXT_THREAT_MATRIX_STEALTH  120
#define IDS_TEXT_THREAT_MATRIX_REMOVAL  121

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
