// Configurable items

#define CONFIG_PROFILE_NAME			"AVISACSampleComm.prf"
#define MAIN_LOGFILE_NAME			"AVISACSignatureComm.log"
#define MAIN_TRACEFILE_NAME			"AVISACSignatureComm.trc"
#define MAIN_AGENT_NAME				"AVISACSignatureComm:"

#define SOCKS_ADDRESS_KEYNAME					"socksAddress"
#define PROXY_ADDRESS_KEYNAME					"proxyAddress"
#define PROXY_USERNAME_KEYNAME					"proxyUsername"
#define PROXY_PASSWORD_KEYNAME					"proxyPassword"
#define CONNECTION_TIMEOUT_KEYNAME				"connectTimeout"
#define CONNECTION_RETRIES_KEYNAME				"connectRetries"
#define SEND_REQUEST_TIMEOUT_KEYNAME			"sendRequestTimeout"
#define SEND_REQUEST_DATA_TIMEOUT_KEYNAME		"sendRequestDataTimeout"
#define RECEIVE_RESPONSE_TIMEOUT_KEYNAME		"receiveResponseTimeout"
#define RECEIVE_RESPONSE_DATA_TIMEOUT_KEYNAME	"receiveResponseDataTimeout"
#define WININET_DEBUGGING_KEYNAME				"enableWinInetLogging"
#define GATEWAY_COUNT_KEYNAME					"gatewayCount"
#define GATEWAY_ADDRESS_BASE_KEYNAME			"gatewayAddress"
#define FIREWALL_TYPE_KEYNAME					"firewallType"
#define SIGNATURE_STORAGE_PATH_KEYNAME			"SignatureStoragePath"
#define ENABLE_TRACING_KEYNAME					"enableTracing"
#define CLIENT_DELAY_AFTER_NETWORK_ERROR_KEYNAME	"ClientDelayAfterNetworkError"
#define SIGNATURE_EXPORTER_POLLING_INTERVAL_KEYNAME	"SignatureExporterPollingInterval"
#define SIGNATURE_EXPORTER_USE_SSL_KEYNAME			"signatureExporterUseSSL"
#define SIGNATURE_EXPORTER_USE_SSL_DEFAULT			FALSE
#define ALLOW_USER_TO_RESPOND_TO_CRITICAL_ERROR_KEYNAME "allowUserToRespondToCriticalError"
#define SOUND_ALARM_ON_CRITICAL_ERROR_KEYNAME "soundAlarmOnCriticalError"

#define CONNECTION_TIMEOUT_DEFAULT				5
#define CONNECTION_RETRIES_DEFAULT				2
#define SEND_REQUEST_TIMEOUT_DEFAULT			3
#define SEND_REQUEST_DATA_TIMEOUT_DEFAULT		3
#define RECEIVE_RESPONSE_TIMEOUT_DEFAULT		3
#define RECEIVE_RESPONSE_DATA_TIMEOUT_DEFAULT	3
#define CLIENT_DELAY_AFTER_NETWORK_ERROR_DEFAULT 5
#define SIGNATURE_EXPORTER_POLLING_INTERVAL_DEFAULT 10

#define FIREWALL_TYPE_SOCKS "socks"
#define FIREWALL_TYPE_PROXY "proxy"
#define FIREWALL_TYPE_DEFINED_IN_REGISTRY "definedInRegistry"

#define ALL_TX_REQUIRED_HEADERS					"Connection: close" "\n" "Pragma: no-cache"
#define EXPORT_SIGNATURE_TX_REQUIRED_HEADERS	ALL_TX_REQUIRED_HEADERS

#define SIGNATURE_EXPORTER_AGENT_NAME	"AVIS Signature Exporter"

#define EXPORT_SIGNATURE_CONTENT_TYPE_HEADER_VALUE_FATALBERT	"application/x-NAV-FatAlbert"
#define EXPORT_SIGNATURE_CONTENT_TYPE_HEADER_VALUE_VDB			"application/x-NAV-VDB"

#define FILENAME_EXTENSION_FATALBERT "exe"
#define FILENAME_EXTENSION_VDB "vdb"

#define IGNORE_INVALID_CERTIFICATE_SERVER_NAME_KEYNAME	"ignoreInvalidCertificateServerName"
#define IGNORE_INVALID_CERTIFICATE_SERVER_NAME_DEFAULT	FALSE

#define TIMEOUT_TRANSACTION_CONNECTED_KEYNAME	"timeoutTransactionConnected"
#define TIMEOUT_TRANSACTION_CONNECTED_DEFAULT	30

#define TIMEOUT_EXPORT_SIGNATURE_TRANSACTION_COMPLETED_KEYNAME	"timeoutExportSignatureTransactionCompleted"
#define TIMEOUT_EXPORT_SIGNATURE_TRANSACTION_COMPLETED_DEFAULT	(30*60)

#define SIGNATURE_DATE_PUBLISHED_HEADER_NAME	"X-Date-Published"
#define SIGNATURE_CHECKSUM_HEADER_NAME			"X-Signatures-Checksum"

#define SIGNATURE_EXPORTER_SHUTDOWN_TIMEOUT 1800

#define EXPORT_SIGNATURE_SERVLET_NAME	"/AVIS/postSignatureSet"

#define SINGLE_INSTANCE_MUTEX_NAME "CAVISACSignatureCommAppSingleInstanceObject"
