// Copyright 1992-1997 Symantec Corporation, Peter Norton Product Group
//**************************************************************************
//
// $Header:   S:/IAL/VCS/ialcons.h_v   1.1   25 Jun 1997 17:18:04   DSACKIN  $
//
// Description:
//    This file contains constant definitons for IAL project.
//
//**************************************************************************
// $Log:   S:/IAL/VCS/ialcons.h_v  $
// 
//    Rev 1.1   25 Jun 1997 17:18:04   DSACKIN
// Ported from Marconi
// 
//    Rev 1.1   30 Jan 1997 13:08:56   pvenkat
// Added constants for seperate error msgs if SETUP or NAV32UP fails to start.
// 
//**************************************************************************
//

#define  IDS_ERR_NNS_FILE_NOT_FOUND             0x1001
#define  IDS_ERR_UNABLE_TO_READ_OPTIONS         0x1002
#define  IDS_ERR_IMPERSONATION_FAILED           0x1003

#define  IDS_STR_INST32                         0x2001
#define  IDS_STR_NAV32UP                        0x2002
#define  IDS_STR_NAV_INSTALLED                  0x2003

#define  IDS_ERR_LAUNCH_FAILED_BASE             0x3000
#define  IDS_ERR_SETUP_LAUNCH_FAILED            0x3001
#define  IDS_ERR_NAV32UP_LAUNCH_FAILED          0x3002

