// Copyright 1997 - 1998 Symantec, Peter Norton Product Group
//***************************************************************************
//
// $Header:   S:/APCOMM/VCS/COMMSTRS.H_v   1.1   17 Feb 1998 14:28:02   RStanev  $
//
// Description:
//      This file declares translatable strings.
//
// Contains:
//      -
//
// See Also:
//      commstrs.cpp
//
// Note:
//      APCOMM module
//
//***************************************************************************
// $Log:   S:/APCOMM/VCS/COMMSTRS.H_v  $
// 
//    Rev 1.1   17 Feb 1998 14:28:02   RStanev
// Updated copyright.
//
//    Rev 1.0   29 May 1997 10:54:34   RStanev
// Initial revision.
//
//***************************************************************************

#ifndef _COMMSTRS_H_
#define _COMMSTRS_H_

extern WCHAR szSpoolFileName[];

#endif // #ifndef _COMMSTRS_H_
