//////////////////////////////////////////////////////////////////////////
// Copyright 1993 Symantec, Peter Norton Computing Group
//
// $Header:   S:/SYMKRNL/VCS/DIALOGS.H_v   1.0   26 Jan 1996 20:22:10   JREARDON  $
//
// $Log:   S:/SYMKRNL/VCS/DIALOGS.H_v  $
// 
//    Rev 1.0   26 Jan 1996 20:22:10   JREARDON
// Initial revision.
// 
//    Rev 1.5   02 Mar 1995 11:44:46   BRIANF
// Made changes that are necessary to build custom Quake DLLs.
//
//    Rev 1.4   15 Mar 1994 12:35:24   BRUCE
// Changed EXPORT to SYM_EXPORT
//
//    Rev 1.3   25 Feb 1994 12:23:42   BRUCE
// Ran scripts to change to SYM_ constants and get ready for Win32
//
//    Rev 1.2   26 Jan 1994 08:05:34   MARKK
// Added version warning dialog.
//
//    Rev 1.1   15 Oct 1993 15:23:22   ED
// VFat dialog
//
//    Rev 1.0   22 Jun 1993 12:24:56   DLEVITON
// Support for runtime DLL version checking.
//
/////////////////////////////////////////////////////////////////////////


#define IDD_VERSION                 2100
#define ID_LISTBOX                  2101

#define IDD_NO_VFAT_ALLOWED         2102

#define IDD_UNSUPPORTED_WINDOWS_VER 2103
