/*********************************************************************
** String IDs for file: symkrnl.rc
*********************************************************************/
#define ABRVSIZ_K                  2000 /* ERR_NUM(  0,   0) */
#define ABRVSIZ_M                  2001 /* ERR_NUM(  0,   1) */
#define ABRVSIZ_G                  2002 /* ERR_NUM(  0,   2) */
#define KILOBYTE_STR               2003 /* ERR_NUM(  0,   3) */
#define MEGABYTE_STR               2004 /* ERR_NUM(  0,   4) */
#define GIGABYTE_STR               2005 /* ERR_NUM(  0,   5) */
#define SHORT_KILOBYTE_STR         2006 /* ERR_NUM(  0,   6) */
#define SHORT_MEGABYTE_STR         2007 /* ERR_NUM(  0,   7) */
#define SHORT_GIGABYTE_STR         2008 /* ERR_NUM(  0,   8) */
#define IDS_NOTFOUND               2009 /* ERR_NUM(  0,   9) */
#define IDS_UNKNOWN                2010 /* ERR_NUM(  0,  10) */

#define MN_JANUARY                 2291 /* ERR_NUM(  1,  35) */
#define MN_FEBRUARY                2292 /* ERR_NUM(  1,  36) */
#define MN_MARCH                   2293 /* ERR_NUM(  1,  37) */
#define MN_APRIL                   2294 /* ERR_NUM(  1,  38) */
#define MN_MAY                     2295 /* ERR_NUM(  1,  39) */
#define MN_JUNE                    2296 /* ERR_NUM(  1,  40) */
#define MN_JULY                    2297 /* ERR_NUM(  1,  41) */
#define MN_AUGUST                  2298 /* ERR_NUM(  1,  42) */
#define MN_SEPTEMBER               2299 /* ERR_NUM(  1,  43) */
#define MN_OCTOBER                 2300 /* ERR_NUM(  1,  44) */
#define MN_NOVEMBER                2301 /* ERR_NUM(  1,  45) */
#define MN_DECEMBER                2302 /* ERR_NUM(  1,  46) */
#define WDN_SUNDAY                 2303 /* ERR_NUM(  1,  47) */
#define WDN_MONDAY                 2304 /* ERR_NUM(  1,  48) */
#define WDN_TUESDAY                2305 /* ERR_NUM(  1,  49) */
#define WDN_WEDNESDAY              2306 /* ERR_NUM(  1,  50) */
#define WDN_THURSDAY               2307 /* ERR_NUM(  1,  51) */
#define WDN_FRIDAY                 2308 /* ERR_NUM(  1,  52) */
#define WDN_SATURDAY               2309 /* ERR_NUM(  1,  53) */
#define IDS_HOUR                   2310 /* ERR_NUM(  1,  54) */
#define IDS_HOURS                  2311 /* ERR_NUM(  1,  55) */
#define IDS_MINUTE                 2312 /* ERR_NUM(  1,  56) */
#define IDS_MINUTES                2313 /* ERR_NUM(  1,  57) */
#define IDS_SECOND                 2314 /* ERR_NUM(  1,  58) */
#define IDS_SECONDS                2315 /* ERR_NUM(  1,  59) */

#define IDS_VXDERR_COULD_NOT_OPEN      2400
#define IDS_VXDERR_FILE_NOT_FOUND      2401
#define IDS_VXDERR_LOADER              2402
#define IDS_VXDERR_COULD_NOT_UNLOAD    2403
#define IDS_VXDERR_UNKNOWN             2404

