////////////////////////
//
// PROPRIETARY / CONFIDENTIAL.
// Use of this product is subject to license terms.
// Copyright © 2006 Symantec Corporation.
// All rights reserved.
//
/////////////////////////////////////////////////////////////////////////////////////////////////

//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SNLogRes.rc
//
#define IDS_PROJNAME                    100
#define IDS_COLTEXT_DATE                101
#define IDS_COLTEXT_USER                102
#define IDS_COLTEXT_MESSAGE             103
#define IDS_COLTEXT_LOCAL_IP            104
#define IDS_COLTEXT_LOCAL_PORT          105
#define IDS_COLTEXT_REMOTE_IP           106
#define IDS_COLTEXT_REMOTE_PORT         107
#define IDS_COLTEXT_SENT                108
#define IDS_COLTEXT_RECV                109
#define IDS_COLTEXT_CONNTIME            110
#define IDS_NO_USER_LOGGED              111
#define IDS_STR_FORMAT_ERROR            112
#define IDS_SYSTEM_CATEGORY             113
#define IDS_CONNECTIONS_CATEGORY        114
#define IDS_FIREWALL_CATEGORY           115
#define IDS_ALERTS_CATEGORY             116
#define IDS_INTRUSIONDETECTION_CATEGORY 117
#define IDS_DEBUG_CATEGORY              118
#define IDS_SYSTEM_CATEGORY_DESCRIPTION 119
#define IDS_FIREWALL_CATEGORY_DESCRIPTION 120
#define IDS_CONNECTIONS_CATEGORY_DESCRIPTION 121
#define IDS_ALERTS_CATEGORY_DESCRIPTION 122
#define IDS_INTRUSIONDETECTION_CATEGORY_DESCRIPTION 123
#define IDS_DEBUG_CATEGORY_DESCRIPTION  124
#define IDS_LOW_STRING                  125
#define IDS_MEDIUM_STRING               126
#define IDS_HIGH_STRING                 127
#define IDS_NONE                        128
#define IDS_INVALID_STR_ID              129
#define IDS_PRODUCT_NAME                130
#define IDB_EVENTICONS                  201
#define IDR_IWP_STYLESHEET              202
#define SN_TDI_SEND_MASK                0x000001E0

//-------------------------------------------------------------------
// TDIT_MSG.H defines
//-------------------------------------------------------------------
//
// misc. string IDs
//
#define SN_EV_STR_NULL                  800
#define SN_EV_STR_INVALID_PARAMETER     801
#define SN_EV_STR_BLANK                 802
#define SN_EV_STR_NOT_VALID             803
#define SN_EV_STR_NA                    804
#define SN_EV_STR_TO                    805
#define SN_EV_STR_FROM                  806
#define SN_EV_NDIS_UNKNOWN              807
//
// tdi set event handler 'event types'
//
#define SN_EV_STR_TDI_EVENT_BASE        1000
#define SN_EV_STR_TDI_EVENT_CONNECT     1000
#define SN_EV_STR_TDI_EVENT_DISCONNECT  1001
#define SN_EV_STR_TDI_EVENT_ERROR       1002
#define SN_EV_STR_TDI_EVENT_RECEIVE     1003
#define SN_EV_STR_TDI_EVENT_RECEIVE_DATAGRAM 1004
#define SN_EV_STR_TDI_EVENT_RECEIVE_EXPEDITED 1005
#define SN_EV_STR_TDI_EVENT_SEND_POSSIBLE 1006
#define SN_EV_STR_TDI_EVENT_CHAINED_RECEIVE 1007
#define SN_EV_STR_TDI_EVENT_CHAINED_RECEIVE_DATAGRAM 1008
#define SN_EV_STR_TDI_EVENT_CHAINED_RECEIVE_EXPEDITED 1009
//                                                 
// query info types
//                                                 
#define SN_EV_STR_TDI_QUERY_BASE        1100
#define SN_EV_STR_TDI_QUERY_BROADCAST_ADDRESS 1101
#define SN_EV_STR_TDI_QUERY_PROVIDER_INFO 1102
#define SN_EV_STR_TDI_QUERY_ADDRESS_INFO 1103
#define SN_EV_STR_TDI_QUERY_CONNECTION_INFO 1104
#define SN_EV_STR_TDI_QUERY_PROVIDER_STATISTICS 1105
#define SN_EV_STR_TDI_QUERY_DATAGRAM_INFO 1106
#define SN_EV_STR_TDI_QUERY_DATA_LINK_ADDRESS 1107
#define SN_EV_STR_TDI_QUERY_NETWORK_ADDRESS 1108
#define SN_EV_STR_TDI_QUERY_MAX_DATAGRAM_INFO 1109
#define SN_EV_STR_TDI_QUERY_ADAPTER_STATUS 1200
#define SN_EV_STR_TDI_QUERY_SESSION_STATUS 1300
#define SN_EV_STR_TDI_QUERY_FIND_NAME   1400
//
// tdi errors
//
#define SN_EV_STR_STATUS_ADDRESS_ALREADY_ASSOCIATED 1500
#define SN_EV_STR_STATUS_ADDRESS_ALREADY_EXISTS 1501
#define SN_EV_STR_STATUS_ADDRESS_CLOSED 1502
#define SN_EV_STR_STATUS_ADDRESS_NOT_ASSOCIATED 1503
#define SN_EV_STR_STATUS_BUFFER_OVERFLOW 1504
#define SN_EV_STR_STATUS_BUFFER_TOO_SMALL 1505
#define SN_EV_STR_STATUS_CANCELLED      1506
#define SN_EV_STR_STATUS_CONNECTION_ABORTED 1507
#define SN_EV_STR_STATUS_CONNECTION_ACTIVE 1508
#define SN_EV_STR_STATUS_CONNECTION_INVALID 1509
#define SN_EV_STR_STATUS_CONNECTION_REFUSED 1510
#define SN_EV_STR_STATUS_CONNECTION_RESET 1511
#define SN_EV_STR_STATUS_DATA_NOT_ACCEPTED 1512
#define SN_EV_STR_STATUS_GRACEFUL_DISCONNECT 1513
#define SN_EV_STR_STATUS_HOST_UNREACHABLE 1514
#define SN_EV_STR_STATUS_IO_TIMEOUT     1515
#define SN_EV_STR_STATUS_INSUFFICIENT_RESOURCES 1516
#define SN_EV_STR_STATUS_INVALID_ADDRESS 1517
#define SN_EV_STR_STATUS_INVALID_ADDRESS_COMPONENT 1518
#define SN_EV_STR_STATUS_INVALID_DEVICE_REQUEST 1519
#define SN_EV_STR_STATUS_INVALID_DEVICE_STATE 1520
#define SN_EV_STR_STATUS_INVALID_PARAMETER 1521
#define SN_EV_STR_STATUS_MORE_PROCESSING_REQUIRED 1522
#define SN_EV_STR_STATUS_NETWORK_UNREACHABLE 1523
#define SN_EV_STR_STATUS_PENDING        1524
#define SN_EV_STR_STATUS_PORT_UNREACHABLE 1525
#define SN_EV_STR_STATUS_PROTOCOL_UNREACHABLE 1526
#define SN_EV_STR_STATUS_REQUEST_ABORTED 1527
#define SN_EV_STR_STATUS_SUCCESS        1528
#define SN_EV_STR_STATUS_TOO_MANY_ADDRESSES 1529
#define SN_EV_STR_STATUS_UNKNOWN        1530
//
// Known Address types
//
#define SN_EV_STR_TDI_ADDRESS_TYPE_BASE 1600
#define SN_EV_STR_TDI_ADDRESS_TYPE_UNSPEC 1600
#define SN_EV_STR_TDI_ADDRESS_TYPE_UNIX 1601
#define SN_EV_STR_TDI_ADDRESS_TYPE_IP   1602
#define SN_EV_STR_TDI_ADDRESS_TYPE_IMPLINK 1603
#define SN_EV_STR_TDI_ADDRESS_TYPE_PUP  1604
#define SN_EV_STR_TDI_ADDRESS_TYPE_CHAOS 1605
#define SN_EV_STR_TDI_ADDRESS_TYPE_IPX  1606
#define SN_EV_STR_TDI_ADDRESS_TYPE_NBS  1607
#define SN_EV_STR_TDI_ADDRESS_TYPE_ECMA 1608
#define SN_EV_STR_TDI_ADDRESS_TYPE_DATAKIT 1609
#define SN_EV_STR_TDI_ADDRESS_TYPE_CCITT 1610
#define SN_EV_STR_TDI_ADDRESS_TYPE_SNA  1611
#define SN_EV_STR_TDI_ADDRESS_TYPE_DECnet 1612
#define SN_EV_STR_TDI_ADDRESS_TYPE_DLI  1613
#define SN_EV_STR_TDI_ADDRESS_TYPE_LAT  1614
#define SN_EV_STR_TDI_ADDRESS_TYPE_HYLINK 1615
#define SN_EV_STR_TDI_ADDRESS_TYPE_APPLETALK 1616
#define SN_EV_STR_TDI_ADDRESS_TYPE_NETBIOS 1617
#define SN_EV_STR_TDI_ADDRESS_TYPE_8022 1618
#define SN_EV_STR_TDI_ADDRESS_TYPE_OSI_TSAP 1619
#define SN_EV_STR_TDI_ADDRESS_TYPE_NETONE 1620
#define SN_EV_STR_TDI_ADDRESS_TYPE_VNS  1621
#define SN_EV_STR_TDI_ADDRESS_TYPE_NETBIOS_EX 1622
//
// Disconnect Flags
//
#define SN_EV_STR_TDI_DISCONNECT_FLAGS  1700
#define SN_EV_STR_TDI_DISCONNECT_WAIT   1700
#define SN_EV_STR_TDI_DISCONNECT_ABORT  1701
#define SN_EV_STR_TDI_DISCONNECT_RELEASE 1702
//
// Device Types
//
#define SN_EV_STR_DEVICE_IP             1750
#define SN_EV_STR_DEVICE_UDP            1751
#define SN_EV_STR_DEVICE_TCP            1752
#define SN_EV_STR_DEVICE_RAW_IP         1753
#define SN_EV_STR_DEVICE_UNKNOWN        1754
#define SN_EV_STR_DEVICE_IPV6			1755	
#define SN_EV_STR_DEVICE_UDPV6			1756
#define	SN_EV_STR_DEVICE_TCPV6			1757




//
// create object types
//
#define SN_EV_STR_OBJECT_ID_BASE        1770
#define SN_EV_STR_TRANSPORT_ADDRESS     1770
#define SN_EV_STR_CONNECTION            1771
#define SN_EV_STR_CONTROL_CHANNEL       1772
#define SN_EV_STR_CONNECTION_CONTEXT    1773
//
// file device types 
//
#define SN_EV_STR_FILE_DEVICE_BASE      1800
#define SN_EV_STR_FILE_DEVICE_BEEP                		1801		// 0x00000001
#define SN_EV_STR_FILE_DEVICE_CD_ROM              		1802		// 0x00000002
#define SN_EV_STR_FILE_DEVICE_CD_ROM_FILE_SYSTEM  		1803		// 0x00000003
#define SN_EV_STR_FILE_DEVICE_CONTROLLER          		1804		// 0x00000004
#define SN_EV_STR_FILE_DEVICE_DATALINK            		1805		// 0x00000005
#define SN_EV_STR_FILE_DEVICE_DFS                 		1806		// 0x00000006
#define SN_EV_STR_FILE_DEVICE_DISK                		1807		// 0x00000007
#define SN_EV_STR_FILE_DEVICE_DISK_FILE_SYSTEM    		1808		// 0x00000008
#define SN_EV_STR_FILE_DEVICE_FILE_SYSTEM         		1809		// 0x00000009
#define SN_EV_STR_FILE_DEVICE_INPORT_PORT         		1810		// 0x0000000a
#define SN_EV_STR_FILE_DEVICE_KEYBOARD            		1811		// 0x0000000b
#define SN_EV_STR_FILE_DEVICE_MAILSLOT            		1812		// 0x0000000c
#define SN_EV_STR_FILE_DEVICE_MIDI_IN             		1813		// 0x0000000d
#define SN_EV_STR_FILE_DEVICE_MIDI_OUT            		1814		// 0x0000000e
#define SN_EV_STR_FILE_DEVICE_MOUSE               		1815		// 0x0000000f
#define SN_EV_STR_FILE_DEVICE_MULTI_UNC_PROVIDER  		1816		// 0x00000010
#define SN_EV_STR_FILE_DEVICE_NAMED_PIPE          		1817		// 0x00000011
#define SN_EV_STR_FILE_DEVICE_NETWORK             		1818		// 0x00000012
#define SN_EV_STR_FILE_DEVICE_NETWORK_BROWSER     		1819		// 0x00000013
#define SN_EV_STR_FILE_DEVICE_NETWORK_FILE_SYSTEM 		1820		// 0x00000014
#define SN_EV_STR_FILE_DEVICE_NULL                		1821		// 0x00000015
#define SN_EV_STR_FILE_DEVICE_PARALLEL_PORT       		1822		// 0x00000016
#define SN_EV_STR_FILE_DEVICE_PHYSICAL_NETCARD    		1823		// 0x00000017
#define SN_EV_STR_FILE_DEVICE_PRINTER             		1824		// 0x00000018
#define SN_EV_STR_FILE_DEVICE_SCANNER             		1825		// 0x00000019
#define SN_EV_STR_FILE_DEVICE_SERIAL_MOUSE_PORT   		1826		// 0x0000001a
#define SN_EV_STR_FILE_DEVICE_SERIAL_PORT         		1827		// 0x0000001b
#define SN_EV_STR_FILE_DEVICE_SCREEN              		1828		// 0x0000001c
#define SN_EV_STR_FILE_DEVICE_SOUND               		1829		// 0x0000001d
#define SN_EV_STR_FILE_DEVICE_STREAMS             		1830		// 0x0000001e
#define SN_EV_STR_FILE_DEVICE_TAPE                		1831		// 0x0000001f
#define SN_EV_STR_FILE_DEVICE_TAPE_FILE_SYSTEM    		1832		// 0x00000020
#define SN_EV_STR_FILE_DEVICE_TRANSPORT           		1833		// 0x00000021
#define SN_EV_STR_FILE_DEVICE_UNKNOWN             		1834		// 0x00000022
#define SN_EV_STR_FILE_DEVICE_VIDEO               		1835		// 0x00000023
#define SN_EV_STR_FILE_DEVICE_VIRTUAL_DISK        		1836		// 0x00000024
#define SN_EV_STR_FILE_DEVICE_WAVE_IN             		1837		// 0x00000025
#define SN_EV_STR_FILE_DEVICE_WAVE_OUT            		1838		// 0x00000026
#define SN_EV_STR_FILE_DEVICE_8042_PORT           		1839		// 0x00000027
#define SN_EV_STR_FILE_DEVICE_NETWORK_REDIRECTOR  		1840		// 0x00000028
#define SN_EV_STR_FILE_DEVICE_BATTERY             		1841		// 0x00000029
#define SN_EV_STR_FILE_DEVICE_BUS_EXTENDER        		1842		// 0x0000002a
#define SN_EV_STR_FILE_DEVICE_MODEM               		1843		// 0x0000002b
#define SN_EV_STR_FILE_DEVICE_VDM 						1844		// 0x0000002c
#define SN_EV_STR_FILE_DEVICE_MASS_STORAGE        		1845		// 0x0000002d
#define SN_EV_STR_FILE_DEVICE_MAX       1845
//
// Define the method codes for how buffers are passed for I/O and FS controls
//
#define SN_EV_STR_METHOD_BASE           1900
#define SN_EV_STR_METHOD_BUFFERED       1900
#define SN_EV_STR_METHOD_IN_DIRECT      1901
#define SN_EV_STR_METHOD_OUT_DIRECT     1902
#define SN_EV_STR_METHOD_NEITHER        1903
//
// Define the access check value for any access
//
#define SN_EV_STR_FILE_ACCESS_BASE      2000
#define SN_EV_STR_FILE_ANY_ACCESS       2000
#define SN_EV_STR_FILE_READ_ACCESS      2001
#define SN_EV_STR_FILE_WRITE_ACCESS     2002
#define SN_EV_STR_FILE_READ_WRITE_ACCESS 2003
//
// Query Information Entities (input)
//
#define SN_EV_STR_GENERIC_ENTITY        2100
#define SN_EV_STR_CO_TL_ENTITY          2101
#define SN_EV_STR_CL_TL_ENTITY          2102
#define SN_EV_STR_ER_ENTITY             2103
#define SN_EV_STR_CO_NL_ENTITY          2104
#define SN_EV_STR_CL_NL_ENTITY          2105
#define SN_EV_STR_AT_ENTITY             2106
#define SN_EV_STR_IF_ENTITY             2107
#define SN_EV_STR_UNKNOWN_ENTITY        2108
//
// Query Information Entities (Output)
//
#define SN_EV_STR_CO_TL_NBF             2150
#define SN_EV_STR_CO_TL_SPX             2151
#define SN_EV_STR_CO_TL_TCP             2152
#define SN_EV_STR_CO_TL_SPP             2153
#define SN_EV_STR_CL_TL_NBF             2154
#define SN_EV_STR_CL_TL_UDP             2155
#define SN_EV_STR_ER_ICMP               2156
#define SN_EV_STR_CL_NL_IPX             2157
#define SN_EV_STR_CL_NL_IP              2158
#define SN_EV_STR_AT_ARP                2159
#define SN_EV_STR_AT_NULL               2160
#define SN_EV_STR_IF_GENERIC            2161
#define SN_EV_STR_IF_MIB                2162
//
// Query Information Classes
//
#define SN_EV_STR_INFO_CLASS_GENERIC    2200
#define SN_EV_STR_INFO_CLASS_PROTOCOL   2201
#define SN_EV_STR_INFO_CLASS_IMPLEMENTATION 2202
#define SN_EV_STR_INFO_CLASS_UNKNOWN    2203
//
// Query Information Types
//
#define SN_EV_STR_INFO_TYPE_PROVIDER    2220
#define SN_EV_STR_INFO_TYPE_ADDRESS_OBJECT 2221
#define SN_EV_STR_INFO_TYPE_CONNECTION  2222
#define SN_EV_STR_INFO_TYPE_UNKNOWN     2223
//
// Query Information IDs
//
#define SN_EV_STR_ENTITY_LIST_ID        2230
#define SN_EV_STR_ENTITY_TYPE_ID        2231
#define SN_EV_STR_IP_MIB_ADDRTABLE_ENTRY_ID 2232
#define SN_EV_STR_IP_INTFC_INFO_ID      2233


//
// Receive Flags
//
#define SN_TDI_RECEIVE_MASK							0x00000FFF	// mask used to isolate
																// supported bits in the
																// received flags
#define SN_EV_STR_TDI_RECEIVE_FLAGS     2300
#define SN_EV_STR_TDI_RECEIVE_TRUNCATED           		2300		// 0x00000001
#define SN_EV_STR_TDI_RECEIVE_FRAGMENT            		2301		// 0x00000002
#define SN_EV_STR_TDI_RECEIVE_BROADCAST           		2302		// 0x00000004
#define SN_EV_STR_TDI_RECEIVE_MULTICAST           		2303		// 0x00000008
#define SN_EV_STR_TDI_RECEIVE_PARTIAL             		2304		// 0x00000010
#define SN_EV_STR_TDI_RECEIVE_NORMAL              		2305		// 0x00000020
#define SN_EV_STR_TDI_RECEIVE_EXPEDITED           		2306		// 0x00000040
#define SN_EV_STR_TDI_RECEIVE_PEEK                		2307		// 0x00000080
#define SN_EV_STR_TDI_RECEIVE_NO_RESPONSE_EXP     		2308		// 0x00000100
#define SN_EV_STR_TDI_RECEIVE_COPY_LOOKAHEAD      		2309		// 0x00000200
#define SN_EV_STR_TDI_RECEIVE_ENTIRE_MESSAGE      		2310		// 0x00000400
#define SN_EV_STR_TDI_RECEIVE_AT_DISPATCH_LEVEL   		2311		// 0x00000800
//
// receive filter flags
//
#define SN_TO_PROTOCOL                  2350
#define SN_FROM_PROTOCOL                2351
#define SN_TO_TDITRACE                  2352
#define SN_FROM_TDITRACE                2353
//
// queue names
//
#define SN_EV_STR_TDI_Q_TRX_RECEIVE     2400
#define SN_EV_STR_TDI_Q_BD_RECEIVE_IN   2401
#define SN_EV_STR_TDI_Q_BD_RECEIVE_OUT  2402
//
// filter status codes
//
#define SN_EV_STR_FILTER_CONNECT_ALLOW  2500
#define SN_EV_STR_FILTER_CONNECT_ALLOW_FILTER 2501
#define SN_EV_STR_FILTER_CONNECT_REJECT 2502
#define SN_EV_STR_FILTER_DATAGRAM_ALLOW 2503
#define SN_EV_STR_FILTER_DATAGRAM_REJECT 2504

//
// Send Flags
//
#define SN_TDI_SEND_MASK							0x000001E0		// mask used to isolate
																// supported bits in the
																// send flags
#define SN_EV_STR_TDI_SEND_FLAGS        2600
#define SN_EV_STR_TDI_SEND_EXPEDITED            		2605		// 0x00000020
#define SN_EV_STR_TDI_SEND_PARTIAL              		2606		// 0x00000040
#define SN_EV_STR_TDI_SEND_NO_RESPONSE_EXPECTED 		2607		// 0x00000080
#define SN_EV_STR_TDI_SEND_NON_BLOCKING         		2608		// 0x00000100

//
//Implict block log reasons
//
#define SN_EV_STR_IMPLICIT_REASON_ALERT_ALREADY_POSTED 2650
#define SN_EV_STR_IMPLICIT_REASON_NO_ALERT_MECHANISM 2651
#define SN_EV_STR_IMPLICIT_REASON_POST_ALERT_FAILED 2652
#define SN_EV_STR_IMPLICIT_REASON_OUTBOUND_CONN_BLOCKED 2653

//-------------------------------------------------------------------
//
//	I P   F I L T E R   D E F I N E S 
//
//------------------------------------------------------------------

#define SN_EV_STR_IP_FILTER_NO_MEMORY   2700
#define SN_EV_STR_IP_FILTER_BAD_TYPE_OBJECT 2701
#define SN_EV_STR_IP_FILTER_BAD_NAME_OBJECT 2702
#define SN_EV_STR_IP_FILTER_HOST        2703
#define SN_EV_STR_IP_FILTER_NETWORK     2704
#define SN_EV_STR_IP_FILTER_RANGE       2705
#define SN_EV_STR_IP_FILTER_GROUP       2706
#define SN_EV_STR_IP_FILTER_SERVICE     2707
#define SN_EV_STR_IP_FILTER_TIME        2708
#define SN_EV_STR_IP_FILTER_GENERIC     2709
#define SN_EV_STR_IP_FILTER_UNKNOWN_IP_OBJECT_TYPE 2710
#define SN_EV_STR_IP_FILTER_APPLICATION 2711
#define SN_EV_STR_IP_FILTER_USER_ACTION_ONCE 2712
#define SN_EV_STR_IP_FILTER_DEFAULT_ACTION 2713
#define SN_EV_STR_IP_FILTER_ALLOW       2714
#define SN_EV_STR_IP_FILTER_DENY        2715
#define SN_EV_STR_IP_FILTER_USER_ACTION_CREATE_RULE 2716
#define SN_EV_IP_IMPLICIT_BLOCK_RULE    2717
#define SN_EV_STR_IP_FILTER_USER_ACTION_CREATE_BOGUS_RULE 2718

//-------------------------------------------------------------------
//
// ICMP Message Types
//
//-------------------------------------------------------------------

#define SN_EV_STR_ICMP_ECHO_REPLY       2800
#define SN_EV_STR_ICMP_DESTINATION_UNREACHABLE 2801
#define SN_EV_STR_ICMP_SOURCH_QUENCH    2802
#define SN_EV_STR_ICMP_REDIRECT         2803
#define SN_EV_STR_ICMP_ECHO_REQUEST     2804
#define SN_EV_STR_ICMP_ROUTER_ADVERTISEMENT 2805
#define SN_EV_STR_ICMP_ROUTER_SOLICITATION 2806
#define SN_EV_STR_ICMP_DATAGRAM_TIME_EXCEEDED 2807
#define SN_EV_STR_ICMP_DATAGRAM_PARAMETER_PROBLEM 2808
#define SN_EV_STR_ICMP_TIMESTAMP_REQUEST 2809
#define SN_EV_STR_ICMP_TIMESTAMP_REPLY  2810
#define SN_EV_STR_ICMP_INFORMATION_REQUEST 2811
#define SN_EV_STR_ICMP_INFORMATION_REPLY 2812
#define SN_EV_STR_ICMP_ADDRESS_MASK_REQUEST 2813
#define SN_EV_STR_ICMP_ADDRESS_MASK_REPLY 2814
#define SN_EV_STR_ICMP_UNKNOWN_INVALID_MESSAGE 2815
#define SN_EV_STR_ICMP_PACKET_TOO_BIG								2816
#define SN_EV_STR_ICMP_MULTICAST_LISTENER_QUERY					2817
#define SN_EV_STR_ICMP_MULTICAST_LISTENER_REPORT					2818
#define SN_EV_STR_ICMP_MULTICAST_LISTENER_DONE						2819
#define SN_EV_STR_ICMP_NEIGHBORHOOD_SOLICITATION					2820
#define SN_EV_STR_ICMP_NEIGHBORHOOD_ADVERTISEMENT					2821
#define SN_EV_STR_ICMP_REDIRECT_MESSAGE							2822
#define SN_EV_STR_ICMP_ROUTE_NUMBERING								2823
#define SN_EV_STR_ICMP_ICMP_NODE_QUERY								2824
#define SN_EV_STR_ICMP_ICMP_NODE_RESPONSE							2825
#define SN_EV_STR_ICMP_INVERSE_DISCOVERY_SOLICITATION				2826
#define SN_EV_STR_ICMP_INVERSE_DISCOVERY_ADVERTISEMENT				2827




//-------------------------------------------------------------------
//
// Settings change strings
//
//-------------------------------------------------------------------

#define SN_EV_STR_AUTOCORRECTENABLED    3000
#define SN_EV_STR_AUTOCORRECTTIMEOUT    3001
#define SN_EV_STR_ICMPFILTERENABLED     3002
#define SN_EV_STR_FRAGMENTEDPKTACTION_FW 3003
#define SN_EV_STR_FRAGMENTEDPKTACTION_IDS 3004
#define SN_EV_STR_LOGIPFRAGMENTS        3005
#define SN_EV_STR_BLOCKIGMP             3006
#define SN_EV_STR_PROTECTEXPLORER       3007
#define SN_EV_STR_DATAGRAMRECEIVEACTION 3008
#define SN_EV_STR_DEFAULTCONNECTRESULT  3009
#define SN_EV_STR_DEFAULTACCEPTRESULT   3010
#define SN_EV_STR_DEFAULTRECEIVEDATAGRAMRESULT 3011
#define SN_EV_STR_DEFAULTSENDDATAGRAMRESULT 3012
#define SN_EV_STR_DEFAULTLISTENRESULT   3013
#define SN_EV_STR_STEALTHBLOCKED        3014
#define SN_EV_STR_MOSTRECENTSIZE        3015
#define SN_EV_STR_SCANDETECTENABLED     3016
#define SN_EV_STR_SCANDETECTAUTOCORRECT 3017
#define SN_EV_STR_SCANDETECTTIMEOUT     3018
#define SN_EV_STR_SCANDETECTTHRESHOLD   3019
#define SN_EV_STR_SCANDETECTPURGEINTERVAL 3020
#define SN_EV_STR_SCANDETECTCLOSEDPORTSONLY 3021
#define SN_EV_STR_ALERTACCESSEDUNUSEDPORTS 3022
#define SN_EV_STR_DISCONNECTEVERYTHING  3023
#define SN_EV_STR_MULTIHOMED            3024
#define SN_EV_STR_ENABLEDDISABLEIDS     3025
#define SN_EV_STR_ENABLEMODULEFINGERPRINTING 3026
#define SN_EV_STR_ENABLEAPPPARENTCHECK  3027
#define SN_EV_STR_SYNSCANSTEALTHING     3028
#define SN_EV_STR_FIREWALLSTATE         3029
#define SN_EV_STR_NDISSTATE             3030
#define SN_EV_STR_ENABLELOCATIONAWARENESS 3031
#define SN_EV_STR_MAXIMUMRULEFILE       3032
#define SN_EV_STR_NDISALERTENABLED      3033
#define SN_EV_STR_PORTBLOCKLISTSIZE     3034
#define SN_EV_STR_PORTBLOCKENABLED      3035
#define SN_EV_STR_FILTERALLOUTBOUND     3036
#define SN_EV_STR_PORTBLOCKALERTFLAG    3037
#define SN_EV_STR_LOGGINGFILTERMASK     3038
#define SN_EV_STR_PORTBLOCKALLOWINBOUNDNETBIOS	3039
#define SN_EV_STR_PORTBLOCKBROADCASTTIMEOUT		3040
#define SN_EV_STR_UNCMNPROTOGATEDIRECTION		3041
#define SN_EV_STR_RULEUPDATEBUFFERSIZE			3042
#define SN_EV_STR_IPV6STATECHANGE	3043
#define SN_EV_STR_AUTOBLOCK_LIMIT	3044
#define SN_EV_STR_AUTOMONITOR_LIMIT	3045
#define SN_EV_STR_NETBIOSNSACTION	3046
#define SN_EV_STR_AUTOBLOCK_SETTINGS_FLAGS	3047
#define SN_EV_STR_UDPCONTIMEOUTMS		3048
#define SN_EV_STR_UDPCONMAXSENDPEND		3049
#define SN_EV_STR_UDPCONMAXRECVPEND		3050
#define SN_EV_STR_FORCEWRITEMODEFILTERING	3051
#define SN_EV_STR_DEBUGALLOWEDGROUPS		3052
#define SN_EV_STR_DEBUGMINIMUMTYPE		3053
#define SN_EV_STR_STARTUPSTATE			3054
#define SN_EV_STR_PRODUCTCURRENTSTATE		3055
#define SN_EV_STR_TRUSTLINKLOCAL1		3056
#define SN_EV_STR_TRUSTLINKLOCAL2		3057
#define SN_EV_STR_RESTRICTLINKLOCAL1		3058
#define SN_EV_STR_RESTRICTLINKLOCAL2		3059
#define SN_EV_STR_IDSINSPECTTRUSTEDPACKETS	3060
#define SN_EV_STR_OEMSTATE			3061



#define SN_TDI_RECEIVE_MASK             0x00000FFF

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        203
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         203
#define _APS_NEXT_SYMED_VALUE           125
#endif
#endif
