
HELP_FILE=NSWNT.HLP
TARGET_TYPE=HLP
.INCLUDE $(QUAKEINC)\PLATFORM.MAK

$(HELP_FILE):       \
    NSNT.HPJ      \
    NSCHELP.RTF    \
    NSINTRO.RTF    \
    NSTASK.RTF     \
    NSHLPBTN.RTF      \
    NSNT.CNT      \
    NAVWHLP.H       \
    SYMW4002.MRB    \
    SYMW4003.MRB    \
    SYMW4005.MRB    \
    SYMW4006.MRB    \
    NSOPTS.RTF      \
    UPGRADE.RTF   \
    SUPPORT.RTF    \
