// Copyright 1995-1999 Symantec Corporation
//***************************************************************************
//
// Description:
//      Provides VERSION numbers for the various NAVVDL resource files.
//
//***************************************************************************

//***************************************************************************
// Version Information
//***************************************************************************
#define NAVVDL_VERSION_MAJOR        4
#define NAVVDL_VERSION_MINOR        0
#define NAVVDL_VERSION_INLINE       0
#define NAVVDL_BUILD_NUMBER         0
#define NAVVDL_BUILD_STRING         "0"
#define NAVVDL_PRODUCT_VERSION      "0.0.0.0"
