// Copyright 1997 Symantec Corporation
//************************************************************************
//
// $Header:   S:/APWCMD/VCS/ApwRes.h_v   1.0   28 May 1997 15:22:12   JBRENNA  $
//
// Description:
//      ApwRes.h -- This provides all of the common resource ids for this
//      project.
//
//************************************************************************
// $Log:   S:/APWCMD/VCS/ApwRes.h_v  $
// 
//    Rev 1.0   28 May 1997 15:22:12   JBRENNA
// Initial revision.
// 
//    Rev 1.0   28 May 1997 12:27:28   JBRENNA
// Initial revision.
// 
//************************************************************************

#ifndef _APWRES_H
#define _APWRES_H

//************************************************************************
// String IDs 
//************************************************************************

#define IDS_APP_CAPTION                     4000
#define IDS_ERR_AP_CANT_EXEC_NAVW_MEM       4001
#define IDS_ERR_AP_CANT_EXEC_NAVW_BAD_FILE  4002
#define IDS_ERR_AP_CANT_EXEC_NAVW           4003

#endif // _APWRES_H
