//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Apw.rc
//
#define IDS_TRAY_ENABLED                1
#define IDS_TRAY_DISABLED               2
#define IDS_MAIN_ENABLE_BUTTON          3
#define IDS_MAIN_DISABLE_BUTTON         4
#define IDS_MAIN_STATUS_ENABLED         5
#define IDS_MAIN_STATUS_DISABLED        6
#define IDS_MAIN_STATUS_LOADING         7
#define IDS_APW_CAPTION                 8
#define IDS_ERR_LOAD_DRIVER             9
#define IDS_APW_LOG_APP_NAME            10
#define IDS_TRAY_ENABLE                 11
#define IDS_TRAY_DISABLE                12
#define IDS_SHUTDOWN_BANNER_WIN         13
#define IDS_SHUTDOWN_BANNER_SAVE        14
#define IDS_SHUTDOWN_BANNER_NAV         15
#define IDS_SHUTDOWN_WAIT_WIN           16
#define IDS_SHUTDOWN_WAIT_SAVE          17
#define IDS_SHUTDOWN_WAIT_NAV           18
#define IDS_WININIT_INI                 19
#define IDS_WININIT_RENAME              20
#define IDS_LICENSEEXPIRED              21
#define IDI_APW_APP_ENABLED             101
#define IDD_APW_MAIN                    102
#define IDR_TRAY_MENU                   103
#define IDI_APW_APP_DISABLED            105
#define IDD_APW_NOTIFY                  106
#define IDB_BITMAP2                     108
#define IDC_MAIN_ICON                   1000
#define IDC_MAIN_STATUS                 1001
#define IDC_MAIN_MINIMIZE               1002
#define IDC_MAIN_ENABLE                 1003
#define IDC_MAIN_OPTIONS                1004
#define IDC_BLOWIE                      1006
#define IDC_BOGUS                       1007
#define IDC_EDIT1                       1009
#define IDM_TRAY_OPEN                   40001
#define IDM_TRAY_ENABLE                 40002
#define IDM_TRAY_OPTIONS                40003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40004
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
