# Copyright 2004-2005 Symantec Corporation. All rights reserved.
# Author: Bertil Askelid <Bertil_Askelid@Symantec.com>
# Intent: VPReg Makefile

Root = ../

Macros = SERVER

Includes = $(PScan)\
			  $(LDVP)/include\
			  $(LDVPmisc)\
			  $(QuarantineServer)/Shared/Include\
			  $(MD5)/include\
			  $(AMS)/include\
			  ./

Sources	  = regmain.cpp
Binary	  = VPReg.bin
Executable = vpreg

include $(Root)Rules.mk
