//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ISUser.RC
//
#define IDC_RESUME_BUTTON               1
#define IDC_EXIT_BUTTON                 2
#define IDD_EXIT_DIALOG                 102
#define IDC_STATIC_NETSCAPE1            1002
#define IDC_NETSCAPE_CHECKBOX           1003
#define IDC_STATIC_NETSCAPE3            1004
#define IDC_SCAN_FOR_VIRUSES2           1006
#define IDC_KEEP_SETTINGS1              1007
#define IDC_KEEP_SETTINGS2              1008
#define IDC_KEEP_SETTINGS_YES           1009
#define IDC_KEEP_SETTINGS_NO            1010
#define IDC_INITIAL_SETTINGS1           1011
#define IDC_SCHEDULE_SCAN_CHECKBOX      1012
#define IDC_AUTO_PROTECT_CHECKBOX       1013
#define IDC_AUTO_PROTECT_TEXT           1014
#define IDC_BUTTON_NETSCAPE_ADVANCED    1015
#define IDC_BOOT_SCAN_CHECKBOX          1015
#define IDC_INITIAL_SETTINGS2           1015
#define IDC_RUN_LIVE_UPDATE_CHECKBOX    1016
#define IDC_BOOT_SCAN_TEXT              1016
#define IDC_INITIAL_SETTINGS3           1016
#define IDC_RUN_NAV_CHECKBOX            1017
#define IDC_RESCUE_CHECKBOX             1018
#define DLG_TEMPLATE                    13029
#define IDD_TEMPLATE                    13029
#define IDD_SCAN_FOR_VIRUSES            13030
#define IDD_KEEP_SETTINGS               13032
#define IDD_INITIAL_SETTINGS            13033
#define IDD_INITIAL_SETTINGS95          13034
#define IDD_SCAN_FOR_VIRUSES95          13035
#define IDD_ADVOTEXT_2                  13036
#define IDD_ADVOTEXT_1                  13037
#define IDD_ADVOTEXT_1_NEC              13038
#define IDD_SCAN_FOR_VIRUSES95_NEC      13039
#define IDC_STATIC_NETSCAPE2            -1
#define IDC_SCAN_FOR_VIRUSES1           -1
#define IDC_SCHEDULE_SCAN_TEXT          -1

#define IDB_BACKGROUND_BMP              20000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1017
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

