/////////////////////////////////////////////////////////////////////
// File: CreatMig.h
// Copyright 1992-1997 Symantec, Peter Norton Product Group
/////////////////////////////////////////////////////////////////////
//
// $Header:   S:/ATMIGRAT/VCS/CREATMIG.H_v   1.0   26 May 1998 14:36:20   SEDWARD  $
//
//
/////////////////////////////////////////////////////////////////////
//
// $Log:   S:/ATMIGRAT/VCS/CREATMIG.H_v  $
// 
//    Rev 1.0   26 May 1998 14:36:20   SEDWARD
// Initial revision.
//
/////////////////////////////////////////////////////////////////////




#ifndef CREATE_MIGRANT_HEADER
#define CREATE_MIGRANT_HEADER

#include    "Migrant.h"

CMigrant*   CreateMigrant(void);

#endif  // CREATE_MIGRANT_HEADER