/////////////////////////////////////////////////////////////////////
// File: registry.h
// Copyright 1992-1997 Symantec, Peter Norton Product Group
/////////////////////////////////////////////////////////////////////
//
// $Header:   S:/ATMIGRAT/VCS/REGISTRY.H_v   1.0   26 May 1998 14:36:16   SEDWARD  $
//
//
/////////////////////////////////////////////////////////////////////
//
// $Log:   S:/ATMIGRAT/VCS/REGISTRY.H_v  $
// 
//    Rev 1.0   26 May 1998 14:36:16   SEDWARD
// Initial revision.
//
/////////////////////////////////////////////////////////////////////



#ifndef NAV_MIGRATE_REGISTRY_HEADER
#define NAV_MIGRATE_REGISTRY_HEADER

// registry keys (do not translate)
#define MSAPP_PATH_KEY                  "Software\\Microsoft\\Windows\\CurrentVersion\\App Paths\\"
#define MSSHARED_DLL_KEY                "Software\\Microsoft\\Windows\\CurrentVersion\\SharedDlls"
#define MSUNINSTALL_KEY                 "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall"
#define MSWINDOWS_KEY                   "Software\\Microsoft\\Windows"
#define MS_WINDOWS_CURRENT_VERSION_KEY  "Software\\Microsoft\\Windows\\CurrentVersion"
#define NAV95_INSTALL_KEY               "Software\\Symantec\\Norton AntiVirus\\Install"
#define NAVNT_KEY                       "Software\\Symantec\\Norton AntiVirus NT"
#define NAV95_KEY                       "Software\\Symantec\\Norton AntiVirus"
#define NAV_INSTALLDIR_VALUENAME        "InstallDir"
#define NAV_KEY                         "Software\\Symantec\\Norton AntiVirus"
#define NAV_LIVE_UPDATE_FILE            "Software\\Classes\\NavLuFile"
#define NAV_LIVE_UPDATE_FILE_SHELL      "Software\\Classes\\NavLuFile\\shell"
#define NAV_LIVE_UPDATE_REGKEY_PATH     "Software\\Symantec\\Norton AntiVirus\\LiveUpdate"
#define NAV_SCANNER_KEY                 "Software\\Symantec\\Norton AntiVirus Scanner"
#define NAV_VIRUS_DEFS_LOCATION_KEY     "Software\\Symantec\\Norton AntiVirus\\Virus Defs\\Location"
#define NETSCAPE_KEY                    "Software\\Netscape\\Netscape Navigator"
#define NETSCAPE_MAIN_REGKEY            "Software\\Netscape\\Netscape Navigator\\Main"
#define SOFTWARE_CLASSES_CLASSID_KEY    "Software\\Classes\\CLSID"
#define SOFTWARE_CLASSES_KEY            "Software\\Classes"
#define SYMANTEC_INSTALLED_APPS_KEY     "Software\\Symantec\\InstalledApps"
#define SYMANTEC_KEY                    "Software\\Symantec"
#define SYMANTEC_SHAREDUSAGE_KEY        "Software\\Symantec\\SharedUsage"
#define SYMANTEC_SHARED_NAV_VALUENAME   "NAVNT"
#define WINDOWS_HELP_KEY                "Software\\Microsoft\\Windows\\Help"

#endif  // NAV_MIGRATE_REGISTRY_HEADER