//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by qscon.rc
//
#define IDS_PROJNAME                    100
#define IDB_QSCONSOLE_16                102
#define IDB_QSCONSOLE_32                103
#define IDR_QSCONSOLE_MENU              104
#define IDR_RESULT_MENU                 104
#define IDD_QSCONSOLE                   105
#define IDS_QSCONSOLE_DESC              106
#define IDS_QSCONSOLE_PROVIDER          107
#define IDD_QSERVER_PAGE                107
#define IDS_QSCONSOLE_VERSION           108
#define IDR_QSCONSOLE                   109
#define IDS_COL_FILENAME                109
#define IDS_COL_USERNAME                110
#define IDS_COL_MACHINE_NAME            111
#define IDS_COL_DOMAIN_NAME             112
#define IDS_COL_RECIEVED                113
#define IDS_COL_SUBMITTED               114
#define IDS_COL_SUBMIT_BY               115
#define IDS_COL_STATUS                  116
#define IDS_NOT_SUBMITTED               117
#define IDS_SERVER_ATTACH_ERROR_CAPTION 118
#define IDS_ERROR                       119
#define IDS_CONFIG_ERROR                120
#define IDS_BAD_QSERVER_FOLDER          121
#define IDS_TITLE                       122
#define IDS_DELETE_WARNING              123
#define IDD_GENERAL_PAGE                124
#define IDS_BYTES_STR                   124
#define IDD_CLIENT_PAGE                 125
#define IDS_KILOBYTES                   125
#define IDS_MEGABYTES                   126
#define IDS_GIGABYTES                   127
#define IDS_BYTES                       128
#define IDS_FILE_TYPE                   129
#define IDS_FILE                        130
#define IDS_NA                          131
#define IDS_COL_VIRUS_NAME              132
#define IDS_UNKNOWN                     133
#define IDS_VIRUS_PAGE                  134
#define IDB_SNAPIN_LARGE                201
#define IDC_SERVER                      201
#define IDB_SNAPIN_SMALL                202
#define IDC_USER                        202
#define IDD_SERVER                      203
#define IDC_DOMAIN                      203
#define IDC_PASSWORD                    204
#define IDD_VIRUS_PAGE                  204
#define IDC_Q_FOLDER                    205
#define IDB_VIRUS_BMPS                  205
#define IDC_QFOLDER_SIZE                206
#define IDR_ITEM_TOOLBAR                206
#define IDC_SPIN1                       207
#define IDC_IP_CHECK                    208
#define IDD_RESTORE_DIALOG              208
#define IDC_IPX_CHECK                   209
#define IDI_RESTORE                     209
#define IDC_IP_PORT                     210
#define IDI_REPAIR                      210
#define IDC_IP_STATIC                   211
#define IDR_SCOPE_MENU                  211
#define IDC_IPX_STATIC                  212
#define IDR_SCOPE_TOOLBAR               212
#define IDC_SPX_PORT                    213
#define IDC_ICON_BUTTON                 214
#define IDD_FETCH_FILE_DIALOG           214
#define IDC_NAME_EDIT                   215
#define IDC_SIZE_EDIT                   216
#define IDD_SELECT_COMPUTER_PAGE        216
#define IDC_LOCATION_EDIT               217
#define IDC_TYPE_EDIT                   218
#define IDC_QUARANTINE_EDIT             219
#define IDI_MAIN_ICON                   219
#define IDC_SUBMITTED_EDIT              220
#define IDR_HELP_MENU                   220
#define IDC_STATUS_EDIT                 221
#define IDC_INFORMATION_EDIT            222
#define IDC_USERNAME_EDIT               223
#define IDC_DESCR_STATIC                223
#define IDC_SUBMITTEDBY_EDIT            223
#define IDC_COMPUTER_EDIT               224
#define IDC_ITEM_LIST                   224
#define IDC_DOMAIN_EDIT                 225
#define IDC_PROGRESS                    225
#define IDC_COMMENTS_STATIC             226
#define IDC_IPADDRESS_EDIT              226
#define IDC_VIRUS_NAME_STATIC           227
#define IDC_PROGRESS_STATIC             227
#define IDC_NACADDRESS_EDIT             227
#define IDC_ALIASES_STATIC              228
#define IDC_ICON_STATIC                 228
#define IDC_PLATFORM_EDIT               228
#define IDC_INFECTS_STATIC              229
#define IDC_SERVER_STATIC               229
#define IDC_PRODUCT_EDIT                229
#define IDC_LIKELIHOOD_STATIC           230
#define IDC_LENGTH_STATIC               231
#define IDC_MEMORY_PICTURE              232
#define IDC_USERNAME_STATIC             232
#define IDC_SIZE_STEALTH_PICTURE        233
#define IDC_PASSWORD_STATIC             233
#define IDC_FULL_STEALTH_PICTURE        234
#define IDC_DOMAIN_STATIC               234
#define IDC_TRIGGER_PICTURE             235
#define IDC_FOLDER_STATIC               235
#define IDC_ENCRYPTING_PICTURE          236
#define IDC_MAX_STATIC                  236
#define IDC_POLY_PICTURE                237
#define IDC_MEGABYTES_STATIC            237
#define IDC_CHOOSER_STATIC              10017
#define IDC_CHOOSER_GROUP_TARGET_MACHINE 10018
#define IDC_CHOOSER_RADIO_LOCAL_MACHINE 10019
#define IDC_CHOOSER_RADIO_SPECIFIC_MACHINE 10020
#define IDC_CHOOSER_EDIT_MACHINE_NAME   10021
#define IDC_CHOOSER_BUTTON_BROWSE_MACHINENAMES 10022
#define ID_TASK_RESTOREITEM             32768
#define ID_TASK_REPAIRITEM              32770
#define ID_TASK_SUBMITITEMTOSARC        32771
#define IDS_REPAIR_DESCR                32772
#define IDS_RESTORE_DESCR               32773
#define ID_TOP_ATTACHTOSERVER           32774
#define IDS_RESTORE_FILENAME_HEADER     32775
#define IDS_RESTORE_STATUS_HEADER       32776
#define IDS_MULTI_DELETE_WARNING        32777
#define IDS_WORKING                     32778
#define IDS_SAVE_AS_FILTER              32779
#define IDS_RESTORE_OVERWRITE_TITLE     32780
#define IDS_RESTORE_OVERWRITE_FORMAT    32781
#define IDS_CLOSE                       32782
#define IDS_ACTION_COMPLETED            32783
#define IDS_PROGRESS_FORMAT             32784
#define IDS_REPAIRED                    32785
#define IDS_RESTORED                    32786
#define IDS_ERROR_TITLE                 32787
#define IDS_ERROR_FETCHING_FILES        32788
#define IDS_DESTINATION_DIR             32789
#define IDS_DESCRIPTION_FORMAT          32790
#define IDS_RESTORE_WARNING             32791
#define IDS_REPAIR_ITEM                 32792
#define IDS_MULTI_REPAIR_ITEM           32793
#define IDS_NOACTION                    32794
#define IDS_CANT_REPAIR                 32795
#define IDS_NO_VIRUS_FOUND              32796
#define IDS_COMMON                      32797
#define IDS_RARE                        32798
#define IDS_BYTES_STR_FORMAT            32799
#define IDS_1FILE                       32800
#define IDS_2FILE                       32801
#define IDS_3FILE                       32802
#define IDS_1BOOT                       32803
#define IDS_2BOOT                       32804
#define IDS_3BOOT                       32805
#define IDS_COM                         32806
#define IDS_EXE                         32807
#define IDS_SYS                         32808
#define IDS_FLOPPY                      32809
#define IDS_HARDDISK                    32810
#define IDS_MASTER                      32811
#define IDS_SUBMIT_PROMPT_FORMAT        32812
#define IDS_SUBMIT_PROMPT               32813
#define IDS_DELETE_PROPERTY_WARNING     32814
#define IDS_COMPUTER_BROWSER_CAPTION    32815
#define IDS_CONNECT_FAILIRE_FMT         32816
#define IDS_NODE_NAME                   32817
#define IDS_EXTENSION_SNAPIN            32818
#define IDS_NODE_DESC                   32819
#define IDS_NONE                        32820
#define IDS_NODE_NAME_FMT               32821
#define IDS_STATUS_HELD                 32822
#define IDS_LOCAL_NODE_NAME             32823
#define IDS_ERROR_FILE_GONE_FMT         32824
#define IDS_FILE_DOES_NOT_EXIST         32825
#define IDS_ERROR_ACCESS_DENIED         32826
#define IDS_ERROR_INITIALIZING_SND      32827
#define IDS_ERROR_OUTOFMEMORY           32828
#define IDS_ERROR_NO_DEFS               32829
#define IDS_SCANANDDELIVER              32830
#define IDS_AVIS                        32831
#define IDS_QUARANTINED                 32832
#define IDS_SUBMITTED                   32833
#define ID_HELP_WHATSTHIS               32834
#define IDS_STATUS_RELEASED             32835
#define IDS_STATUS_UNNEEDED             32836
#define IDS_STATUS_NEEDED               32837
#define IDS_STATUS_AVAILIABLE           32838
#define IDS_STATUS_DISTRIBUTED          32839
#define IDS_STATUS_INSTALLED            32840
#define IDS_STATUS_ATTENTION            32841
#define IDS_STATUS_ERROR                32842
#define IDS_BROWSE_FOR_SAVE_LOCATION    32900
#define IDS_BY                          32901
#define IDS_RECOMMEND_SUBMITTED         32902
#define IDS_RECOMMEND_QUARANTINE        32903
#define IDS_ERROR_MULTI_CONFIG          32904
#define IDS_BAD_PORT                    32905
#define IDS_BAD_MAX_SIZE                32906
#define IDS_ERROR_ITEM_GONE             32907
#define IDS_ERROR_ITEMS_GONE            32908
#define IDS_STATUS_BAR_FORMAT           32909
#define IDS_STATUS_BAR_FORMAT_NODEFS    32910
#define IDS_REPAIR_ITEMS                32911
#define IDS_LOCAL                       32912
#define IDS_LOCAL_LANGUAGE              32913

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        221
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         238
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
