// Copyright 1996-1997 Symantec, Peter Norton Product Group
//****************************************************************************
//
// $Header:   S:/NAVLU/VCS/StdAfx.cpv   1.0   26 Jun 1997 18:11:22   JBRENNA  $
//
// Description:
//   Source file that includes just the standard includes.
//	 StdAfx.pch will be the pre-compiled header.
//	 StdAfx.obj will contain the pre-compiled type information.
//
//****************************************************************************
// $Log:   S:/NAVLU/VCS/StdAfx.cpv  $
// 
//    Rev 1.0   26 Jun 1997 18:11:22   JBRENNA
// Initial revision.
// 
//****************************************************************************

#include "stdafx.h"
