// PROPRIETARY/CONFIDENTIAL. Use of this product is subject to license terms.
// Copyright (c) 2005 Symantec Corporation. All rights reserved.
#if !defined(_VCD_UTILITYERRORS_INCLUDED_)
#define _VCD_UTILITYERRORS_INCLUDED_

#define COMPRESSED_FILE_SIGNATURE		"MSI_COMPRESSED_CD_IMAGE"

#define UTILITYERROR_OPENINPUT			0x00000001
#define UTILITYERROR_OPENOUTPUT		0x00000002
#define UTILITYERROR_ALREADYUTILITYED	0x00000004
#define UTILITYERROR_NOTUTILITYED		0x00000008
#define UTILITYERROR_WRITEERROR		0x00000010
#define UTILITYERROR_POSTCOPYERROR		0x00000020

#endif
