// Copyright 1997 Symantec Corporation
//************************************************************************
//
// $Header:   S:/APWCMD/VCS/apw95res.h_v   1.3   21 Aug 1997 00:17:24   DALLEE  $
//
// Description:
//      Apw95res.h -- This provides all of the Win 95 resource ids for this
//      project.
//      See also Apwres.h
//
//************************************************************************
// $Log:   S:/APWCMD/VCS/apw95res.h_v  $
// 
//    Rev 1.3   21 Aug 1997 00:17:24   DALLEE
// Added AP driver's spooled event progress filename.
// 
//    Rev 1.2   23 Jun 1997 21:00:30   DALLEE
// Added IDS_MEMORY_ALERT for object text for memory alerts.
// 
//    Rev 1.1   05 Jun 1997 17:20:04   DALLEE
// Added string for default activity log name.
// 
//    Rev 1.0   02 Jun 1997 03:41:56   DALLEE
// Initial revision.
//************************************************************************

#ifndef __APW95RES_H
#define __APW95RES_H


//************************************************************************
// String IDs 
//************************************************************************

#define IDS_ACTIVITY_LOG            3000
#define IDS_MEMORY_ALERT            3001
#define IDS_AP_SPOOL_FILE           3002

#endif // __APW95RES_H
