// Copyright 1997 Symantec Corporation
//************************************************************************
//
// $Header:   S:/APWCMD/VCS/ApwNtRes.h_v   1.0   28 May 1997 12:27:28   JBRENNA  $
//
// Description:
//      ApwNtRes.h -- This provides all of the resource ids for this
//      project.
//
//************************************************************************
// $Log:   S:/APWCMD/VCS/ApwNtRes.h_v  $
// 
//    Rev 1.0   28 May 1997 12:27:28   JBRENNA
// Initial revision.
// 
//************************************************************************

#ifndef _APWNTRES_H
#define _APWNTRES_H

//************************************************************************
// String IDs 
//************************************************************************

#define IDS_NAVAP_SERVICE_NAME      3000
#define IDS_NAVAP_FLOPPYAINFECTED   3001
#define IDS_NAVAP_INFECTION_TITLE   3002

#endif // _APWNTRES_H
