# This file was automatically generated by SWIG
package navapi;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package navapi;
bootstrap navapi;
var_navapi_init();
@EXPORT = qw( );
1;
