//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by avScanUIRes.rc
//
#define IDR_MAINFRAME                   100
#define IDS_TL_LOW                      101
#define IDS_TL_MED                      102
#define IDS_TL_HIGH                     103
#define IDS_HAS_DEPENDENCIES            104
#define IDS_HAS_NO_DEPENDENCIES         105
#define IDS_PERFORMANCE                 106
#define IDS_STEALTH                     107
#define IDS_REMOVAL                     108
#define IDS_PRIVACY                     109
#define IDS_OVERALL                     110
#define IDS_TPROC_FAILURE               111
#define IDS_TPROC_STARTING              114
#define IDS_TITLE_TPROC                 115
#define IDS_OPT_CHOOSE                  118
#define IDS_OPT_EXCLUDE                 119
#define IDS_OPT_FIX                     120
#define IDS_TYPE_ANOMALY                121
#define IDS_TYPE_COMPRESSED             122
#define IDS_TYPE_EMAIL                  123
#define IDS_TYPE_BR                     124
#define IDS_TYPE_MBR                    125
#define IDS_STATE_FULLREMOVE            126
#define IDS_STATE_PARTREMOVE            127
#define IDS_STATE_REMOVENOTATTEMPTED    128
#define IDS_STATE_PROCESSING            129
#define IDS_STATE_REMOVEFAILED          130
#define IDS_STATE_DND                   131
#define IDS_ITEMSREMAIN_PROMPT          133
#define IDS_PAUSE                       135
#define IDS_RESUME                      136
#define IDS_EXPORT_FILTER               137
#define IDS_EXPORT_TITLE                138
#define IDS_ATTN_TH                     139
#define IDS_ATTN_TEMPLATE               140
#define IDS_DETAILS_TH                  141
#define IDS_DETAILS_TEMPLATE            142
#define IDS_EXPORT_TXT_TEMPLATE         144
#define IDS_STATE_PENDING               145
#define IDS_OPT_REVIEW                  147
#define IDS_REMDETAILS_TH               148
#define IDS_REMTYPES_TH                 149
#define IDS_REM_REG                     150
#define IDS_REM_REGS                    151
#define IDS_REM_FILE                    152
#define IDS_REM_FILES                   153
#define IDS_REM_PROC                    154
#define IDS_REM_PROCS                   155
#define IDS_REM_BATCH                   156
#define IDS_REM_BATCHS                  157
#define IDS_REM_INI                     158
#define IDS_REM_INIS                    159
#define IDS_REM_SERV                    160
#define IDS_REM_SERVS                   161
#define IDS_REM_COM                     162
#define IDS_REM_COMS                    163
#define IDS_REM_HOST                    164
#define IDS_REM_HOSTS                   165
#define IDS_REM_LSP                     166
#define IDS_REM_LSPS                    167
#define IDS_REM_CACHE                   168
#define IDS_REM_CACHES                  169
#define IDS_REM_SYS                     170
#define IDS_REM_SYSS                    171
#define IDS_THREAT_MATRIX_DESC_OVERALL_HIGH 172
#define IDS_THREAT_MATRIX_DESC_OVERALL_MED 173
#define IDS_THREAT_MATRIX_DESC_OVERALL_LOW 174
#define IDS_THREAT_MATRIX_DESC_PERF_HIGH 175
#define IDS_THREAT_MATRIX_DESC_PERF_MED 176
#define IDS_THREAT_MATRIX_DESC_PERF_LOW 177
#define IDS_THREAT_MATRIX_DESC_PRIV_HIGH 178
#define IDS_THREAT_MATRIX_DESC_PRIV_MED 179
#define IDS_THREAT_MATRIX_DESC_PRIV_LOW 180
#define IDS_THREAT_MATRIX_DESC_REMOVE_HIGH 181
#define IDS_THREAT_MATRIX_DESC_REMOVE_MED 182
#define IDS_THREAT_MATRIX_DESC_REMOVE_LOW 183
#define IDS_THREAT_MATRIX_DESC_STEALTH_HIGH 184
#define IDS_THREAT_MATRIX_DESC_STEALTH_MED 185
#define IDS_THREAT_MATRIX_DESC_STEALTH_LOW 186
#define IDS_ATTN_TEMPLATE_EMAIL         187
#define IDS_OPT_FIX_EMAIL               188
#define IDS_SUBSTATS_FOUND              189
#define IDS_SUBSTATS_FIXED              190
#define IDS_SUBSTATS_NONE               191
#define IDS_SUBSTATS_NONE_FIXED         192
#define IDS_STATE_EXCLUDED              193
#define IDS_STATE_BACKUPONLY            194
#define IDS_EXPORT_XML_TEMPLATE         195
#define IDS_EXPORT_TXT_BODY             196
#define IDS_EXPORT_XML_BODY             197
#define IDS_QUAR_FILTER                 198
#define IDS_QUAR_TITLE                  199
#define IDS_QBADD_FAILURE               200
#define IDS_QBADD_SUCCEESS              201
#define IDS_QBADD_POSTFAIL              202
#define IDS_QBREST_FAILURE              203
#define IDS_QBREST_SUCCEESS             204
#define IDS_QBREST_POSTFAIL             205
#define IDS_QBREST_BROWSETITLE          206
#define IDS_QBREST_CANCELMSG            207
#define IDS_QBREST_CANCELTITLE          208
#define IDS_ERASER_SUCCESS              209
#define IDS_ERASER_FAILURE              210
#define IDS_QBREST_ITEM                 211
#define IDS_REM_COOKIE                  212
#define IDS_REM_COOKIES                 213
#define IDS_STATE_RESTORED              214
#define IDS_TITLE_EXPORTPROG            215
#define IDS_TITLE_LOWPRIORITY           216
#define IDS_TITLE_MQUARANTINE           217
#define IDS_TITLE_QRESTORE              218
#define IDS_TITLE_RISKDETAILS           219
#define IDS_TITLE_EMAIL                 220
#define IDS_ERASER_NOTHINGTODO          221
#define IDS_UNSUPPORTEDTYPE             222
#define IDS_UNDONOTSUPPORTED            223
#define IDS_PROCESSINGTHREAT            224
#define IDS_PROCESSINGTHREATS           225
#define IDS_THREATREMAINING             226
#define IDS_THREATSREMAINING            227
#define IDS_PROCESSING_MSG              228
#define IDS_USERSTOPSCAN_PROMPT         229
#define IDS_HAS_DEPENDENCIES_PLAIN      230
#define IDS_STATE_REBOOTREQ             231
#define IDB_OEHALERT_TITLE_RED          232
#define IDS_REBOOTREQUEST_TITLE         233
#define IDS_REBOOTREQUEST_BRIEF_DESC    234
#define IDS_REBOOTREQUEST_PROMPT_TEXT   235
#define IDS_REBOOTREQUEST_REBOOT_NOW    236
#define IDS_REBOOTREQUEST_REBOOT_LATER  237
#define IDS_PROCTERM_PROMPT_TEXT        238
#define IDS_PROCTERM_CANCEL_BUTTON_TEXT 239
#define IDS_PROCTERM_OK_BUTTON_TEXT     240
#define IDS_PROCTERM_MOREINFO_BUTTON_TEXT 241
#define IDS_PROCTERM_DONTASKAGAIN_TEXT  242
#define IDS_PROCTERM_PROMPT_TITLE       243
#define IDS_NOTSECURE                   244
#define IDS_SECURE                      245
#define IDS_WORKING                     246
#define IDS_OPT_IGNORE                  247
#define IDS_EXPORT_XML_INFO             248
#define IDS_EXPORT_TXT_INFO             249
#define IDS_ABORTED                     250
#define IDS_MQUAR_DESCRIPTION           251
#define IDS_MQUAR_LONGDESC              252
#define IDS_STATE_IGNOREONCE            253
#define IDS_SDESC_FULLREMOVE            254
#define IDS_SDESC_PARTREMOVE            255
#define IDS_SDESC_REMOVENOTATTEMPTED    256
#define IDS_SDESC_PROCESSING            257
#define IDS_SDESC_REMOVEFAILED          258
#define IDS_SDESC_DND                   259
#define IDS_SDESC_EXCLUDED              260
#define IDS_SDESC_BACKUPONLY            261
#define IDS_SDESC_RESTORED              262
#define IDS_SDESC_REBOOTREQ             263
#define IDS_SDESC_PENDING               264
#define IDS_SDESC_IGNOREONCE            265
#define IDS_DONE_ATTN                   266
#define IDS_DONE_FIXED                  267
#define IDS_DONE_CLEAN                  268
#define IDS_INVALID_PATH                269
#define IDS_PATH_MISSING                270
#define IDS_DESC_MISSING                271
#define IDS_STATUS_ACTIVE_CCE           272
#define IDS_STATUS_INACTIVE             273
#define IDS_STATUS_STARTING             274
#define IDS_STATUS_ACTIVE               275
#define IDS_STATUS_PAUSING              276
#define IDS_STATUS_PAUSED               277
#define IDS_STATUS_RESUMING             278
#define IDS_STATUS_STOPPING             279
#define IDS_STATUS_STOPPED              280
#define IDS_STATUS_FINISHING            281
#define IDS_STATUS_DONE                 282
#define IDS_STATUS_ERROR                283
#define IDS_FEATURE_DISABLED            284
#define IDS_BAD_DEFS                    285
#define IDS_OLD_DEFS                    286
#define IDS_ATTN_TEMPLATE_NONE          287
#define IDS_EXISTS                      288
#define IDS_INSIDEOF                    289
#define IDS_REVERSEINSIDEOF             290
#define IDS_INVALID_READONLY            291
#define IDS_INVALID_NETWORK             292
#define IDS_FILENAME_TOOLONG            293
#define IDS_TPROC_FIXSUCCEEDED          300
#define IDS_TPROC_FIXPARTIALLYSUCCEEDED 301
#define IDS_TPROC_FIXPREVIOUSLYREMOVED  302
#define IDS_TPROC_FIXREQUIRESPROCTERM   303
#define IDS_TPROC_FIXTHREATNOLONGERFOUND 304
#define IDS_TPROC_FIXBACKUPFAILED       305
#define IDS_TPROC_FIXFAILED             306
#define IDS_TPROC_FIXINVALIDTHREATID    307
#define IDS_TPROC_FIXINVALIDTHEATTYPE   308
#define IDS_TPROC_FIXINVALIDANOMALYBACKUP 309
#define IDS_TPROC_FIXFAILEDTOLOADISCANNERW 310
#define IDS_TPROC_FIXFAILEDTOLOADIERASER4 311
#define IDS_TPROC_FIXFAILEDTOREDETECTWOIMPERSONATION 312
#define IDS_TPROC_FIXCANNOTREMEDIATE    313
#define IDS_TPROC_FIXDONOTDELETE        314
#define IDS_NOACCESS_TO_OBJECT          315
#define IDS_STATE_REVIEWED              316
#define IDS_DETAILS_TEMPLATE_NONE       317
#define IDS_ERASER_ABORT                318
#define IDS_NA                          319
#define IDS_INFECTED                    320
#define IDS_REPAIRED                    321
#define IDS_DELETED                     322
#define IDS_TERM_FAILED                 323
#define IDS_QUAR_FAILED                 324
#define IDS_DELETE_FAILED               325
#define IDS_QUARANTINED                 326
#define IDS_ACCESS_DENIED               327
#define IDS_NOACTION_REQUIRED           328
#define IDS_DETECTED                    329
#define IDS_NOT_DETECTED                330
#define IDS_TERMINATED                  331
#define IDS_OPERATION_FAILED            332
#define IDS_NOACTION_TAKEN              333
#define IDS_EXPORT_XML_COUNTS           334
#define IDS_EXPORT_TXT_COUNTS           335
#define IDS_SDESC_CANTRECOMPOSE         336

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        337
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           501
#endif
#endif
